/*
  # Production Pests Seed - Part 1 (65 pests)

  Comprehensive Australian agricultural pest database.
  pest_type must be one of: 'insect', 'mite', 'nematode', 'vertebrate', 'mollusc', 'other', ''
*/

INSERT INTO agro_pests (pest_name, common_name, pest_type, affected_crops, identification_details, damage_caused, damage_symptoms, lifecycle_notes, monitoring_notes, spray_threshold, treatment_options) VALUES

('Helicoverpa armigera', 'Cotton Bollworm / Corn Earworm', 'insect', ARRAY['Cotton','Tomato','Chickpea','Maize','Sorghum','Capsicum','Soybean'], 'Yellow-green to brown caterpillar up to 45mm. Variable colour. Pale lateral stripe. Smooth skin. Egg is ribbed dome shape on leaf surfaces.', 'Bores into bolls, pods, fruit and ears. Direct feeding on reproductive structures. 100% loss of infested boll or fruit. One of the most economically important pests in Australia.', 'Circular entry holes in cotton bolls with frass. Caterpillars inside fruit. Internal feeding damage. Wilting growing points. Pin-hole entry in tomato fruit.', 'Moth lays eggs singly on foliage and growing tips. Larvae feed 3-4 weeks before pupating in soil. Multiple generations per season. Overwinters as pupa.', 'Use pheromone traps to monitor adult flights. Check growing tips and egg counts in cotton. Sweep nets and beat sheets for pupae counts. Beat sheet counts twice weekly in sorghum.', '0.1 eggs per plant in susceptible cotton. 15% infestation in chickpea. Consult Beatsheet app for cotton thresholds.', 'Bacillus thuringiensis (Dipel), spinosad (Tracer), indoxacarb (Avatar), chlorantraniliprole (Altacor), emamectin benzoate (Proclaim). Avoid pyrethroids where resistance is high.'),

('Helicoverpa punctigera', 'Native Budworm', 'insect', ARRAY['Cotton','Chickpea','Canola','Lucerne','Sunflower','Wheat'], 'Similar to H. armigera. Pale olive to brown caterpillar with pale lateral stripe. Generally lighter in colour. Distinguished by pale sub-dorsal stripe and lack of coarse setae.', 'Feeds on flowers, buds, pods and seeds. Serious pest of chickpea and canola at flowering. Less resistant to insecticides than H. armigera.', 'Eaten flowers and buds. Pods with feeding damage and frass. Growing tip damage.', 'Migrates into southern Australia from tropical regions annually. Less resistant to insecticides than H. armigera. Multiple generations annually.', 'Use pheromone traps. Beat sheets in chickpea. Visual inspection of canola flowers.', '1-2 larvae per plant in chickpea (1-5 node stage). 5+ larvae per 10 sweeps in canola.', 'Pyrethroids, spinosad, indoxacarb, chlorantraniliprole. Less resistance than H. armigera - check resistance status.'),

('Myzus persicae', 'Green Peach Aphid', 'insect', ARRAY['Potato','Brassica','Capsicum','Tomato','Peach','Canola','Lettuce','Wheat'], 'Soft-bodied pear-shaped insect 1-2mm. Pale green to yellow-green. Long cornicles (tubes at rear). Winged and wingless forms. May be pink in cold conditions.', 'Direct sap-sucking stunts growth. Virus transmission (BYDV, CMV, PVY, PLRV). Honeydew and sooty mould. High economic impact through virus spread.', 'Curled distorted leaves. Yellow mottled foliage from virus. Stunted growth. Sooty mould on honeydew deposits. Distorted growing tips.', 'Overwintered eggs on peach trees. Winged migrants colonise crops in spring and autumn. Many generations per year. Key virus vector in potato and vegetable crops.', 'Regular scouting from crop emergence. Use yellow sticky traps for winged aphids. Count aphid colonies on 20+ plants.', '500 aphids per plant in potato before canopy closure. 20% plant infestation (5+ aphids per plant) early in season. Virus risk alters thresholds.', 'Pirimicarb (Pirimor - selective), imidacloprid, acetamiprid, thiamethoxam, cyantraniliprole (Exirel). Avoid pyrethroids which are irritants that disperse aphids.'),

('Bemisia tabaci', 'Silverleaf Whitefly (Biotype B)', 'insect', ARRAY['Cotton','Tomato','Capsicum','Cucumber','Zucchini','Brassica','Beans'], 'Tiny 1mm white insect. Adult covered with waxy white powder. Yellow body. Eggs on leaf undersurface. Immature stages (crawlers, nymphs) are flat, oval, pale yellow-green.', 'Sap sucking causes leaf yellowing and distortion. Honeydew leads to sooty mould. Silvering of fruit in cucurbits (silverleaf symptom). Virus transmission (TYLCV, CYSDV).', 'Leaf yellowing and silvering. Sooty mould growth on honeydew. Whiteflies fly up when disturbed. Irregular ripening in tomato. Viruses spread rapidly.', 'All life stages present on leaf undersurface. Pupae on lower leaves. Adults preferentially on upper canopy. Many generations per year in warm conditions.', 'Count adults on leaf undersurfaces on 10 plants. Use yellow sticky traps. Check for immature stages under leaves.', '10 adults per plant in capsicum. 5% of leaves with immature stages. Check cotton canopy regularly.', 'Spiromesifen (Oberon), buprofezin, pyriproxyfen, thiamethoxam (Actara), cyantraniliprole (Exirel). Rotate modes of action due to rapid resistance development.'),

('Tetranychus urticae', 'Two-spotted Mite', 'mite', ARRAY['Cotton','Grape','Strawberry','Cucumber','Tomato','Apple','Bean','Rose'], 'Tiny 0.5mm oval mite. Pale green to red with two dark spots on body. Minute eggs. Webbing may be visible in high populations. Stages: egg, larva, two nymph stages, adult.', 'Sap feeding causes pale stippling on leaves. Heavy infestations cause bronzing, defoliation and plant death. High summer temperatures promote rapid population growth.', 'Pale stippling on upper leaf surface. Bronze-coloured leaves in heavy infestations. Fine webbing between leaves. Premature defoliation. Leaf edges curl under.', 'Overwinters as diapause adults under bark and in leaf litter. Populations explode in hot dry conditions. Many generations per year (10-20).', 'Use a hand lens to examine lower leaf surface. Count mites per leaf (10 leaves). Predatory mites reduce populations naturally.', '20-30 mites per leaf in grape (depends on time of season). 5 mites per leaflet in strawberry. 10 mites per leaf in cotton.', 'Abamectin (Vertimec), hexythiazox (Miticide), spirodiclofen (Envidor), spiromesifen (Oberon), bifenazate, fenpyroximate (Portal). Sulphur and petroleum oils.'),

('Panonychus ulmi', 'European Red Mite', 'mite', ARRAY['Apple','Pear','Stone Fruit','Grape'], 'Dark red to brown mite 0.4mm. Distinctive red colour with white-tipped setae (hairs). Brick-red rounded eggs. Overwintering eggs on bark are diagnostic.', 'Sap feeding causes grey-bronze stippling on leaves. Heavy infestations stunt shoots and reduce fruit size. Impacts photosynthesis.', 'Grey-bronze stippling on upper leaf surface. Silvery-grey appearance to foliage. Premature leaf fall.', 'Overwinters as eggs on bark of young wood. Eggs hatch at budburst. 3-4 generations per year in orchard.', 'Count eggs on 10 spurs in winter. Monitor leaf mite populations from budburst using hand lens. Economic thresholds vary by time of season.', '15-20 mites per leaf mid-season in apple. 5 eggs per spur in winter monitoring.', 'Petroleum oil (winter sprays for eggs), clofentezine (Acaricide), hexythiazox (Nissorum), spirodiclofen (Envidor). Preserve predatory mites (Typhlodromus).'),

('Panonychus citri', 'Citrus Red Mite', 'mite', ARRAY['Citrus','Orange','Lemon','Grapefruit','Mandarin'], 'Globular dark red mite with long white-tipped setae. Bright red eggs on leaf surface. Similar to European red mite but on citrus.', 'Sap feeding causes silvery stippling. Heavy infestations reduce photosynthesis and fruit quality. Premature leaf drop in severe cases.', 'Silvery stippling on leaves. Foliage appears dull silver. Leaf drop in severe infestations.', 'Continuous breeding in warm conditions. Up to 12 generations per year. Populations peak in late spring to summer.', 'Count mites per leaf using hand lens (10-20 leaves per sample). Record proportion of leaves infested.', '60-80% leaves infested or 5+ mites per leaf in spring. Adjust for time of season and predator presence.', 'Petroleum oil, abamectin (Agri-Mectin), spirodiclofen (Envidor), fenpyroximate (Portal). Preserve natural enemies.'),

('Frankliniella occidentalis', 'Western Flower Thrips', 'insect', ARRAY['Strawberry','Capsicum','Cucumber','Grape','Tomato','Chrysanthemum','Rose'], 'Slender 1.5mm insect. Golden-yellow to light brown. Two pairs of feathery wings. Larvae yellow-white. Pupae in soil. Very difficult to see with naked eye.', 'Direct feeding causes silvering, streaking and scarring of flowers and fruit. Transmits Tomato Spotted Wilt Virus (TSWV) a major plant pathogen. Distorts growing tips.', 'Silver streaking on flowers and fruit. Distorted and scarred fruit. Calyx damage. Bronze mottling on leaves. Russet on grape berries.', 'Adults shelter inside flowers. Larvae feed on leaves and flowers. Pupate in soil. Many generations per year. Very difficult to control inside flowers.', 'Blue sticky traps for adult monitoring. Open flowers and tap onto white paper to count thrips. Count 5 flowers per plant.', '5-10 thrips per flower in strawberry. 1-2 per flower during critical periods for virus risk crops.', 'Spinosad (Tracer, Success), cyantraniliprole (Exirel), spinetoram (Delegate), abamectin. Difficult to control inside flowers. Rotate modes of action.'),

('Thrips tabaci', 'Plague Thrips / Onion Thrips', 'insect', ARRAY['Onion','Garlic','Leek','Cotton','Wheat','Grape','Soybean'], 'Pale yellow slender thrips 1mm. Similar to western flower thrips but slightly smaller and paler. Larvae white-yellow.', 'Silvery streaking on onion leaves. Deformed bulbs. Feeding reduces photosynthesis. Transmits TSWV in some crops. Key pest of onion in Australia.', 'Silver streaking and scarring on onion leaves. Dry sheath damage. Distorted leaves with silver patches. Reduced bulb size and quality.', 'Overwinters in crop residues and weeds. Breeds continuously in warm conditions. Many generations per year.', 'Check 10 plants (inner leaves) counting thrips per plant. Adults congregate near leaf bases.', '20+ thrips per plant in onion. Economic threshold varies with growth stage and market.', 'Spinosad, cyantraniliprole, dimethoate, chlorpyrifos. Rotate modes of action. Systemic products most effective for protected populations.'),

('Spodoptera frugiperda', 'Fall Armyworm', 'insect', ARRAY['Maize','Sorghum','Wheat','Rice','Sugarcane','Pasture'], 'Green-yellow to dark brown caterpillar with inverted Y shape on head capsule (diagnostic). Dark bands along body. Square head with Y-pattern.', 'Leaf feeding causes windowpaning then ragged holes. Bore into maize whorl causing dead heart symptom. Rapid defoliation. Serious invasive pest arrived Australia 2020.', 'Windowpane feeding on young leaves. Ragged holes. Frass and webbing in whorl. Dead heart in maize. Rapid defoliation of young plants.', 'Adult moth is nocturnal. Multiple generations per year. Migrates long distances. Caterpillars are cannibalistic. Pupate in soil. Serious new invasive pest.', 'Regular field monitoring from crop emergence. Check 20+ plants per hectare. Use pheromone traps for adult moths. Report unusual armyworm activity.', '1 larva per plant in maize whorl stage. 25% defoliation in post-whorl stage. Consult local advisories for current thresholds.', 'Chlorantraniliprole (Altacor, Coragen), spinosad (Tracer), spinetoram (Delegate), emamectin benzoate, Bt (Dipel). Check resistance status. Report outbreaks.'),

('Plutella xylostella', 'Diamondback Moth', 'insect', ARRAY['Cabbage','Broccoli','Cauliflower','Brussels Sprouts','Kale','Canola'], 'Small grey-brown moth. Larvae are pale green 8-12mm. Distinctive wriggling behaviour when disturbed. Diamond pattern on folded wings of adult.', 'Larvae skeletonise leaves leaving papery windows. Heavy infestations cause complete defoliation. Bores into heads causing quality loss. Most serious brassica pest globally.', 'Windowed leaves with papery epidermis intact. Small round holes in leaves. Head penetration in broccoli and cauliflower. Frass on leaves.', 'Short lifecycle (2-3 weeks in warm weather). Many generations per year. Year-round in tropical areas. Rapid resistance development to most insecticide classes documented.', 'Examine undersides of leaves for larvae and pupae cases. Count larvae per plant on 10 plants. Sticky traps for adult monitoring.', '1 larva per plant before heading. 2-3 per plant after heading in broccoli. Adjust for growth stage.', 'Bacillus thuringiensis (Dipel), spinosad (Tracer), indoxacarb (Avatar), chlorantraniliprole (Belt), emamectin. Rotate modes of action rigorously due to resistance.'),

('Lipaphis erysimi', 'Turnip Aphid / Canola Aphid', 'insect', ARRAY['Canola','Brassica','Radish','Turnip'], 'Blue-grey to green small aphid 1.3-2mm. Waxy grey coating. Cornicles short and dark. Forms dense colonies on stem and leaves.', 'Colonises growing tips and pods. Sap sucking stunts growth. Pod damage causes seed shrivel. Transmits brassica viruses. Can cause significant yield losses in canola.', 'Dense blue-grey colonies on stems and pods. Distorted growing tips. Honeydew and sooty mould. Pod abortion. Premature senescence.', 'Overwinters as eggs and actively reproducing colonies in mild climates. Populations build rapidly in spring.', 'Regular inspections from seedling to pod stage. Count colonies per plant or aphids per stem section.', '10-15% of stems or pods infested. 500+ aphids per plant at flowering.', 'Pirimicarb (selective), imidacloprid, dimethoate, pyrethroids. Use selective products to preserve natural enemies where possible.'),

('Halotydeus destructor', 'Red-legged Earth Mite', 'mite', ARRAY['Canola','Legume','Pasture','Lupins','Cereal'], 'Black velvet body with orange-red legs. 1mm. Overwinters as diapause eggs. Active autumn through spring. Forms dense populations on leaf surfaces.', 'Grazes on leaf surfaces causing silvery stippling. Heavy infestations cause leaf bleaching and death. Significant pest in Mediterranean climate areas.', 'Silvery stippling on leaves. Leaves appear silver-grey. Plant death in seedlings. Grazing damage on young plants. Pasture and crop establishment failure.', 'Eggs hatch with autumn rains. Active autumn through to December then diapause. One generation per year.', 'Check plant surfaces for mites using hand lens in autumn and spring. Beat crops onto white paper to dislodge mites.', '5+ mites per plant in seedling crops. Check in autumn after germination.', 'Organophosphates (dimethoate, chlorpyrifos), pyrethroid seed treatment, sulfur dust. Apply at germination if monitoring indicates populations building.'),

('Nysius vinitor', 'Rutherglen Bug', 'insect', ARRAY['Canola','Sunflower','Cotton','Sorghum','Strawberry'], 'Small oval bug 3-4mm. Grey-brown with dark markings. Rapid movement when disturbed. Wings held flat over abdomen.', 'Sap feeding on ripening seeds and fruit. Causes grain shrivel and light grain in cereals. Fruit quality damage in strawberry. Explosive populations in hot dry conditions.', 'Shrivelled lightweight grain. Distorted ripening seeds. Grain shedding. Fruit dimpling and premature ripening. Sharp fluctuations in population size.', 'Nomadic pest breeding on weeds. Moves to crops as weeds dry off in hot weather. Multiple generations per year. Populations build rapidly.', 'Monitor at paddock edges near dry native vegetation. Beat sweep crops near harvest.', '1 bug per plant at grain fill in canola. High numbers at strawberry harvest require action.', 'Pyrethroids (deltamethrin, lambda-cyhalothrin), dimethoate. Hard to control due to continuous movement into crops.'),

('Bactrocera tryoni', 'Queensland Fruit Fly', 'insect', ARRAY['Stone Fruit','Apple','Citrus','Tomato','Capsicum','Mango','Avocado'], 'Red-brown fly 8mm with yellow markings. T-shaped yellow mark on thorax. Female has pointed ovipositor for egg laying into fruit. Maggots white.', 'Female punctures fruit skin to lay eggs. Maggots develop inside fruit causing rotting and premature drop. Renders fruit unmarketable. Major export barrier.', 'Puncture marks on fruit skin. Premature fruit drop. Internal maggots in fruit. Flesh breakdown and rot around larval galleries.', 'Overwinters as adults in sheltered areas. Eggs laid into ripening fruit. Larvae develop inside fruit falling to ground to pupate. Multiple generations in warm climates.', 'Use Lynfield traps with cuelure attractant. Check 2-3 times weekly during ripening season. Yellow panel traps with protein bait.', 'Presence in traps requires management when fruit is susceptible. Protein bait spray threshold at 1 fly per trap per day.', 'Protein bait sprays (Success/Naturalyte with yeast hydrolysate). Cover sprays with malathion. Post-harvest treatments (heat or cold). Male annihilation technique (cuelure + malathion).'),

('Bactrocera cucumis', 'Cucumber Fly', 'insect', ARRAY['Cucumber','Zucchini','Pumpkin','Rockmelon','Watermelon'], 'Similar to Queensland fruit fly. Dark markings on thorax. Key cucurbit pest in tropical and subtropical Australia.', 'Eggs laid into developing cucurbit fruit. Larvae cause internal rotting. Premature fruit drop.', 'Internal fruit rotting with maggots. Premature drop of cucurbit fruit. Puncture wounds on fruit skin.', 'Multiple generations in warm climates. Populations build with warm weather.', 'Use Lynfield traps with Capilure attractant in cucurbit crops. Monitor trap catches twice weekly.', 'Presence of flies when fruit is susceptible requires management.', 'Protein bait sprays with spinosad. Cover sprays. Similar management to QLD fruit fly.'),

('Agrotis infusa', 'Bogong Moth Cutworm', 'insect', ARRAY['Vegetable','Canola','Brassica','Legume','Corn'], 'Larvae are grey-brown to black cutworms 30-45mm. Smooth oily skin. Curl into C shape when disturbed. Moth is large brown-grey.', 'Cut seedlings at soil level at night. Entire paddocks can be destroyed in days. Older larvae climb plants to feed on leaves and stems.', 'Seedlings cut at ground level and wilted. Irregular patches of missing plants. Cutworms found under soil surface. Night feeding.', 'Moth migrates south from inland in autumn. Eggs laid on bare soil. Larvae overwinter. One generation per year.', 'Check paddock edges and newly germinated crops at night. Look for cut seedlings and search soil surface for cutworms.', '1 cutworm per square metre. Check paddock edges in autumn before sowing.', 'Chlorpyrifos, cypermethrin, chlorantraniliprole (Coragen). Baiting with insecticide-wheat bran mixture. Evening sprays most effective.'),

('Mythimna convecta', 'Common Armyworm', 'insect', ARRAY['Wheat','Barley','Maize','Sorghum','Pasture','Rice'], 'Pale green to brown striped caterpillar 30-40mm. Pale lateral stripes along body. Cream-yellow underside. Marches in masses in plague conditions.', 'Strips leaves and cuts stems. Attacks maturing cereal crops. Head stripping near harvest. Moves between crops in large numbers.', 'Stripped leaves. Stem cutting and head loss near harvest. Armyworm march visible as masses of caterpillars. Green frass on ground.', 'Adults active in spring. Eggs on grass and cereal leaves. Can build very rapidly in 3-4 weeks. Plague infestations occur periodically.', 'Check paddock perimeters and crop base. Sticky traps for adult monitoring. Visual inspection of grass areas near crops.', '2-3 larvae per square metre before harvest. 1 per square metre in young crops.', 'Pyrethroids (lambda-cyhalothrin, deltamethrin), chlorpyrifos, diazinon. Apply at dusk or dawn when larvae are most active.'),

('Locusta migratoria', 'Migratory Locust', 'insect', ARRAY['All crops','Pasture'], 'Large grasshopper 35-50mm. Adults have yellow-green body. Can form dense migratory swarms. Gregarious phase differs in colouring from solitary phase.', 'Strips crops and pasture rapidly in swarms. Moves in large groups. Complete crop destruction possible. Major agricultural emergency pest.', 'Complete defoliation. Stripped stems. Crops reduced to stubble. Pasture completely consumed. Moves as swarm into new areas.', 'Usually solitary in Australia. Can form plagues under favourable breeding conditions. Report swarms to authorities.', 'Monitor grassland areas for egg pod laying sites. Report any swarms immediately to DPIRD or state agriculture department.', 'Any swarm near crops requires immediate action.', 'Aerial application of chlorpyrifos, malathion or lambda-cyhalothrin. Australian Plague Locust Commission (APLC) coordinates management.'),

('Xanthogaleruca luteola', 'Elm Leaf Beetle', 'insect', ARRAY['Elm Trees','Ornamental'], 'Yellow-olive beetle 6mm with black stripes. Larvae are yellow-black striped grubs. Pupae bright yellow at base of trunk.', 'Larvae skeletonise leaves from undersurface. Defoliation in summer. Adults chew irregular holes. Trees defoliated multiple times become stressed and die.', 'Skeletonised leaves with transparent windows. Complete defoliation. Larvae on undersides of leaves.', 'Two generations per year. Adults overwinter. Eggs on leaf undersides. Larvae fall from trees to pupate in bark and soil.', 'Inspect elm trees for larvae and skeletonised leaves. Inspect base of trunks for pupae.', 'Significant defoliation or first detection of larvae in spring.', 'Imidacloprid trunk injection (long-lasting systemic). Pyrethroids for rapid knockdown. Dipel (Bt) applied to young larvae.'),

('Tetranychus cinnabarinus', 'Carmine Spider Mite', 'mite', ARRAY['Tomato','Capsicum','Strawberry','Ornamental'], 'Bright red to carmine mite 0.5mm. Dense webbing on leaves. Similar to two-spotted mite but more red.', 'Sap feeding causes stippling and bronzing. Dense webbing. Plant death in severe infestations. Prefers warm conditions.', 'Carmine-red mites visible on leaf undersurface. Dense webbing. Bronze stippled leaves. Premature defoliation.', 'Many generations per year in warm conditions. Populations explode in summer.', 'Check leaf undersurfaces with hand lens. Count mites per leaf on 10-20 leaves.', '20+ mites per leaf. 50% leaves infested.', 'Abamectin, hexythiazox, bifenazate, fenpyroximate. Rotate acaricide groups to prevent resistance.'),

('Phenacoccus solenopsis', 'Cotton Mealybug', 'insect', ARRAY['Cotton','Vegetable','Ornamental','Hibiscus'], 'White waxy oval insect 3-4mm. Dense white waxy filaments especially at rear. Female wingless. Male tiny winged fly. Colonies in leaf axils and on roots.', 'Sap feeding weakens plants. Honeydew and sooty mould. Causes deformation and wilting. High populations can kill plants.', 'White waxy colonies on stems and leaf axils. Yellowing and wilting. Sooty mould. Distorted growing tips.', 'Many generations per year. Parthenogenetic reproduction. Spreads by crawlers on wind, tools and clothing. Invasive pest.', 'Check stems and leaf axils for waxy colonies. Yellow sticky traps for winged males.', 'Any significant colony presence warrants treatment in vegetables.', 'Spirotetramat (Movento - systemic), imidacloprid, chlorpyrifos. Natural enemies: Cryptolaemus mealybug destroyer. Difficult to control with contact insecticides.'),

('Melanotus communis', 'Wireworm', 'insect', ARRAY['Potato','Maize','Wheat','Sugar Beet','Carrot','Onion'], 'Slender hard-bodied yellow to orange larvae 15-25mm. Click beetle adult. Larvae in soil for 3-5 years. Smooth cylindrical body.', 'Bore into potato tubers and root crops. Feed on germinating seeds and seedling roots. Cause internal tunnelling in tubers.', 'Tunnels in potato tubers and carrots. Germination failure. Seedling death. Entry holes in tubers and root crops.', 'Long lifecycle - 3-5 years as larva in soil. Adults emerge in spring. Eggs laid in soil near grass roots.', 'Pre-plant soil sampling for wireworm larvae. Monitor potato seed pieces post-planting. Previous grass history increases risk.', 'Check soil sampling - 1 per square metre warrants treatment in potato.', 'Chlorpyrifos soil treatment. Clothianidin or imidacloprid seed treatment. No highly effective control once crop established.'),

('Pediculus humanus', 'Headlouse (grain storage)', 'insect', ARRAY['Stored Grain','Wheat','Barley','Sorghum'], 'Very small 1-2mm brown louse-like insect. Flat body. Feeds in stored grain and flour products.', 'Contaminates grain. Quality downgrade. Psocids cause grain heating and musty smell. Can penetrate sealed sacks.', 'Grain infested with insects. Musty smell. Hot spots in grain storage. Visual insects in grain sample.', 'Multiple generations in warm grain storage. Spreads rapidly in warm conditions.', 'Check grain samples regularly. Use probe traps. Test for insects at receival.', 'Any psocid presence in grain requires treatment.', 'Phosphine fumigation. Pirimiphos-methyl (Actellic). Grain cooling to below 15C.'),

('Sitophilus oryzae', 'Rice Weevil', 'insect', ARRAY['Stored Grain','Rice','Wheat','Maize'], 'Small brown weevil 2.5-3.5mm with characteristic snout. Four pale spots on wing covers. Breeds inside grain kernels. Larvae inside kernel.', 'Internal kernel feeding reduces grain quality and germination. Grain heating from feeding activity.', 'Hollow grain. Weight loss. Grain heating. Webbing in severe infestations. Distinctive weevil smell.', 'Eggs laid inside grain kernel. Larvae develop inside. Multiple generations in warm stored grain. Major storage pest.', 'Check grain samples at receival. Probe traps during storage. Test germination of seed grain.', 'Any rice weevil presence in seed grain is a concern. Tolerance depends on grade and use.', 'Phosphine fumigation. Grain protectants at receival (pirimiphos-methyl, chlorpyrifos). Grain cooling below 18C stops breeding.'),

('Tribolium castaneum', 'Rust-red Flour Beetle', 'insect', ARRAY['Flour','Stored Grain','Wheat','Processed Grain Products'], 'Rust-red oval beetle 3-4mm. Feeds on broken grain, flour and grain products. Distinguishable from confused flour beetle by 3-segmented club on antennae.', 'Infests flour and broken grain. Quality downgrade. Off-flavours. Cannot attack whole grain directly. Secondary pest.', 'Reddish beetles in flour and grain products. Off-flavour. Brown discolouration of flour.', 'Multiple generations per year. Spreads throughout mill and storage.', 'Pheromone traps for adults. Sieve grain samples. Inspect mills and storage facilities.', 'Any detection in food-grade products or seed.', 'Phosphine fumigation. Surface treatments with pyrethrin or permethrin. Sanitation of storage and mill.'),

('Gryllotalpa orientalis', 'Mole Cricket', 'insect', ARRAY['Turf','Vegetable','Pasture','Sugarcane'], 'Brown cricket 30-45mm with powerful digging forelegs. Mole-like in appearance. Distinctive chirping in spring.', 'Tunnels through soil damaging roots. Lifts turf and vegetable plants. Severs roots causing plant death. Also feeds directly on roots.', 'Raised soil tunnels. Plants wilting and dying. Turf lifting. Root damage visible when plants pulled up.', 'Overwinters as nymphs in soil. Adults emerge and mate in spring. One generation per year. Lay eggs in soil chambers.', 'Listen for chirping at night. Use soap flush (soapy water poured on soil) to bring to surface. Probe traps.', '1 per square metre in turf. Any significant presence in vegetable crops.', 'Chlorpyrifos granules. Entomopathogenic nematodes (Steinernema). Mole cricket bait. Apply in evening.'),

('Schizaphis graminum', 'Russian Wheat Aphid', 'insect', ARRAY['Wheat','Barley','Oats','Triticale'], 'Long narrow pale green aphid with pointed abdomen. Small cornicles barely visible. Causes distinctive leaf rolling.', 'Causes longitudinal leaf rolling (characteristic). Injects toxins causing white-purple streaking. Severe yield loss in susceptible varieties.', 'Longitudinal leaf rolling trapping aphids inside. White-purple striping on rolled leaves. Tillering reduced. Significant yield loss in susceptible varieties.', 'Primarily parthenogens in Australia. Overwinters as actively breeding colonies. Multiple generations from autumn through winter and spring.', 'Check rolled leaves for aphid colonies. Count infested tillers per square metre. Very difficult to detect due to leaf rolling.', '10% tillers infested during vegetative stages. Lower thresholds in susceptible varieties.', 'Dimethoate, pirimicarb, imidacloprid. Roll resistance makes contact insecticides less effective. Systemic products preferred.'),

('Thrips imaginis', 'Rose Thrips / Apple Thrips', 'insect', ARRAY['Apple','Stone Fruit','Rose','Grape'], 'Golden yellow thrips 1mm. Common flower feeder. Female slightly larger than male.', 'Feeding in flowers causes scarring and fruit surface distortion. Creates distinctive russeting and scarring on apple and stone fruit skin.', 'Russet scarring on fruit skin. Distorted apple fruitlets. Flower damage. Calyx end scarring on apple.', 'Population builds in flowers in spring. Breeds in flowers of many plants. Moves to crop flowers during bloom.', 'Count thrips in blossoms by shaking flowers onto white paper. 5 flowers per tree in 10 trees.', '10 thrips per flower in apple blossom. Lower thresholds if scarring is a market concern.', 'Spinosad, spinetoram, dimethoate (pre-bloom). Difficult to treat in open flowers. Timing pre-bloom critical.'),

('Nezara viridula', 'Green Vegetable Bug', 'insect', ARRAY['Tomato','Bean','Capsicum','Soybean','Sunflower','Cotton'], 'Shield-shaped green bug 13-17mm. Nymphs have distinctive colouring - black/red/white markings. Piercing mouthparts. Distinctive stink bug smell when disturbed.', 'Piercing feeding on fruit and pods. Catfacing and distortion of tomato fruit. Seed damage in legumes and cotton. Transmits bacterial pathogens.', 'Distorted catfaced tomato fruit. Puncture wounds with surrounding discolouration. Internal fruit damage. Photosynthate drain from feeding.', 'Overwinters as adults. Multiple generations per year. Adults and nymphs present from spring through autumn.', 'Beat sweep counts. Visual inspection of fruit and foliage. Pheromone traps for monitoring adult flight.', '1 bug per plant in tomato or capsicum. 5% infestation in soybean pods.', 'Pyrethroids (lambda-cyhalothrin, deltamethrin), chlorpyrifos, dimethoate. Difficult to control - adults move rapidly. Early morning applications most effective.'),

('Pseudococcus longispinus', 'Long-tailed Mealybug', 'insect', ARRAY['Grape','Apple','Citrus','Avocado','Ornamental'], 'White waxy mealybug with long tail filaments extending from body. 3-4mm body length. Forms colonies under bark and in bunches.', 'Sap feeding. Honeydew and sooty mould. Contamination of grape bunches. Virus transmission in grape (Grapevine Leafroll Associated Virus).', 'White waxy colonies in grape bunches. Sooty mould on honeydew. Contamination preventing harvest. Vine dieback.', 'Females reproduce ovoviviparously. Year-round breeding in warm climates. Multiple generations. Spread by crawlers and bird movement.', 'Check under bark in winter. Monitor bunches in summer. Sample 10 vines per block checking multiple sites.', 'Any significant colony presence in grape bunches during ripening requires action.', 'Spirotetramat (Movento - most effective systemic), buprofezin, chlorpyrifos. Biological control with Cryptolaemus and parasitic wasps.'),

('Whitefly - Trialeurodes vaporariorum', 'Greenhouse Whitefly', 'insect', ARRAY['Tomato','Capsicum','Cucumber','Lettuce','Ornamental'], 'Similar to silverleaf whitefly but holds wings more parallel (horizontal) to leaf. White waxy scales. Yellow body. Glasshouse and open crop pest.', 'Sap sucking causes yellowing. Honeydew and sooty mould. Virus transmission (particularly in glasshouse crops).', 'Yellowing leaves. Sooty mould. Whiteflies fly when disturbed. Reduced plant vigour.', 'Multiple generations in warm conditions. Glasshouse populations breed year-round. Common in protected cropping.', 'Yellow sticky traps. Count adults per leaf on systematic plant samples.', '10 adults per leaf or 20% of leaves infested.', 'Pyriproxyfen, buprofezin, spiromesifen, cyantraniliprole. Biological control with Encarsia formosa parasitoid in glasshouse.'),

('Deroceras reticulatum', 'Grey Field Slug', 'mollusc', ARRAY['Canola','Wheat','Vegetable','Strawberry','Lettuce'], 'Grey-brown slug 25-50mm. Network pattern on body (reticulate). Mucus colourless to pale. Noctural feeder. Found under debris and in cracks.', 'Rasp leaves, stems and seedlings. Canola seedlings destroyed at establishment. Slime trails. Circular feeding damage with irregular margins.', 'Irregular holes in leaves. Seedling loss at establishment. Slime trails visible in morning. Under debris in daytime.', 'Overwinters as eggs in soil. Eggs hatch in autumn. Most damage at germination. Multiple generations per year in cool moist conditions.', 'Bait traps (tiles or bags) checked at night. Check emerging crop at night or early morning. Rain and cool conditions increase activity.', '1 slug per square metre at crop emergence. Higher thresholds in established crops.', 'Metaldehyde or iron chelate (ferric phosphate) slug pellets. Copper barriers for small areas. Reduce trash at soil surface.'),

('Rattus rattus', 'Black Rat (crop raider)', 'vertebrate', ARRAY['Sugarcane','Maize','Macadamia','Avocado','Poultry'], 'Black to dark brown rat. Long tail longer than body. Large ears. Urban and agricultural pest.', 'Gnaws stalks of sugarcane and maize. Damages macadamia and avocado fruit. Contamination. Disease transmission.', 'Gnawed cane stalks. Opened nut cases. Contamination droppings. Tracks in soft soil. Damage at base of plants.', 'Breeds year-round in warm conditions. Nocturnal. Nests in canopy and structures.', 'Wax blocks, tracking cards, footprint tracking tunnels. Check at dusk for movement.', 'Any detection in crop requires management.', 'Brodifacoum, bromadiolone baits. Zinc phosphide bait. Traps. Habitat reduction.'),

('Mus musculus', 'House Mouse (mouse plague)', 'vertebrate', ARRAY['Wheat','Canola','Sorghum','Stored Grain','Sunflower'], 'Small grey-brown mouse. Musky smell. Distinctive notch in upper incisor.', 'Eats grain and seeds. Ring-barks young trees. Contamination of stored grain. Widespread crop damage in plague years.', 'Gnawed grain heads. Ring-barked seedlings. Droppings in grain storage. Burrow entrances in paddock. Grain loss at sowing.', 'Breeds year-round under good conditions. Rapid population growth in plague years (>1000 per hectare possible). One of the most damaging agricultural pest events.', 'Track tunnels and wax blocks. Mouse paddock counts. Report plague conditions to state department.', '1 mouse per trap night. Paddock populations above 25 per hectare warrant baiting.', 'Zinc phosphide grain bait at sowing. Bromadiolone bait stations. Surface baiting during plague. Fumigation of burrows.'),

('Urophora stylata', 'Thistle Stem Gall Fly (biocontrol agent)', 'insect', ARRAY['Pasture','Non-crop'], 'Small fly 5mm. Brown with patterned wings. Used for biological control of Carduus and Cirsium thistles.', 'Larvae form galls in thistle stems. Reduces seed production. Biocontrol agent - does not damage crops.', 'Galls on thistle stems. Stunted and weakened thistle plants. Reduced seed set.', 'Introduced biocontrol agent. Annual lifecycle.', 'Monitor thistle populations in relation to gall fly presence.', 'Biocontrol agent - no threshold applies.', 'Release and redistribution of biocontrol agents. Not managed with pesticides.'),

('Otiorhynchus sulcatus', 'Vine Weevil / Black Vine Weevil', 'insect', ARRAY['Strawberry','Grape','Ornamental','Nursery'], 'Dull black weevil 8-10mm with fused wing covers. All female (parthenogenetic). Larvae C-shaped white grubs in soil around roots.', 'Adults notch leaf edges (characteristic U-shaped notches). Larvae devour roots causing wilting and plant death.', 'U-shaped notches on leaf margins (adult feeding). Wilting and plant death (larval root damage). White C-shaped grubs in root zone.', 'Parthenogenetic - all females. Eggs laid in summer. Larvae active autumn through spring. Adults feed at night.', 'Check leaf edges for notching. Examine root zones for larvae. Use sticky tape traps on pot rims.', 'Any notching or larval presence warrants treatment in nursery or strawberry.', 'Entomopathogenic nematodes (Steinernema kraussei, Heterorhabditis). Imidacloprid soil application. Thiacloprid. Adults difficult to control.'),

('Eriophyes sheldoni', 'Citrus Bud Mite', 'mite', ARRAY['Citrus','Lemon'], 'Microscopic elongate eriophyid mite. Only visible with hand lens (0.1-0.2mm). Pale cream. Lives inside buds and flowers.', 'Infested buds fail to develop or produce distorted leaves and fruit. Causes distinctive twisting and distortion of shoots and fruit.', 'Distorted and twisted leaves. Corky scarring of lemon fruit. Failed bud development. Hook-shaped young shoots.', 'Continuous breeding inside buds. Many generations per year. Spread by wind and contact.', 'Examine developing buds and new growth with 10x hand lens. Distorted shoots indicate presence.', 'Any significant shoot distortion in susceptible lemon blocks.', 'Petroleum oil, wettable sulfur during new flush periods. Abamectin has some activity. Difficult to control inside buds.'),

('Pseudaulacaspis pentagona', 'White Peach Scale', 'insect', ARRAY['Peach','Nectarine','Plum','Cherry','Mulberry'], 'White oyster-shaped scale 2-3mm. Male scales elongated white. Females circular with yellow body under scale cover. Dense infestations coat bark white.', 'Encrusts bark. Sap feeding weakens branches. Heavy infestations kill branches and trees. Bark splitting and dieback.', 'White encrustation on bark. Branch dieback. Bark splitting. Amber ooze from bark under scale.', 'Two to three generations per year. Crawlers emerge in spring and summer. Spreads by crawlers and on prunings.', 'Examine bark for scale colonies. Count infested wood per sample. Check new orchards at planting.', '25% of shoots infested. Any heavy infestations on young trees.', 'Petroleum oil dormant spray (kills overwintering population). Carbaryl, chlorpyrifos at crawler emergence. Organic options include oils.'),

('Phyllocnistis citrella', 'Citrus Leafminer', 'insect', ARRAY['Citrus','Orange','Lemon','Mandarin','Lime'], 'Tiny moth 2mm with distinctive silver-white wings. Larvae mine inside leaf surface. Characteristic irregular serpentine mines.', 'Larvae create serpentine mines in leaves. Leaf curling and distortion. Provides entry wounds for Citrus canker. Reduces photosynthesis in young trees.', 'Silvery serpentine mines on leaf surface. Distorted curled leaves. Larvae visible inside mine. Young trees most affected.', 'Multiple generations per year in warm conditions. Attacks new flushes of growth. Adult moth is nocturnal.', 'Inspect new growth for mining damage. Peak pressure during summer flushes.', '40-50% of new shoots mined in young trees (under 3 years). Higher tolerance in bearing trees.', 'Spinosad (Tracer), abamectin, imidacloprid (systemic for young trees). Control new flush timing - synchronized flushes easier to protect.'),

('Coccus hesperidum', 'Brown Soft Scale', 'insect', ARRAY['Citrus','Stone Fruit','Mango','Avocado','Ornamental'], 'Flat oval brown scale 3-4mm. Soft - does not have a hard cover. Lives on stems and leaf undersides. Produces copious honeydew.', 'Sap feeding weakens plants. Honeydew leads to severe sooty mould contamination. Reduces photosynthesis significantly.', 'Brown scales on stems and leaves. Black sooty mould. Leaves covered in mould reducing light. Ants tending colonies.', 'Live-bearing scale. Multiple generations in warm climates. Ants protect from predators.', 'Check stems and leaves for scale colonies. Monitor sooty mould build-up. Check for ants (indicator of honeydew-producing pest).', 'Any significant sooty mould build-up or scale colony on young trees.', 'Petroleum oil, white oil, imidacloprid, spirotetramat (Movento). Control ants to allow natural enemies to work.'),

('Aphis gossypii', 'Cotton Aphid / Melon Aphid', 'insect', ARRAY['Cotton','Cucumber','Melon','Capsicum','Watermelon','Zucchini'], 'Small yellow-green to dark green aphid 1-2mm. Variable colour from pale yellow to dark olive. Cornicles black. Common in cucurbits and cotton.', 'Sap feeding stunts growth. Honeydew and sooty mould. Transmits CMV, BYMV and other viruses in cucurbits.', 'Curled or distorted leaves. Dense aphid colonies under leaves. Yellowing. Sooty mould on honeydew. Virus symptoms including mosaic.', 'Many generations per year. Parthenogenetic. Winged forms disperse. Colony build-up rapid in warm conditions.', 'Check undersides of leaves regularly. Yellow sticky traps for winged forms. Count colonies on 20+ plants.', '10% plants infested early. 50% plants with colonisation at later stages.', 'Pirimicarb (selective for aphids), imidacloprid, acetamiprid, cyantraniliprole, pyrethroids. Insecticidal soaps for organic options.'),

('Brevicoryne brassicae', 'Cabbage Aphid', 'insect', ARRAY['Cabbage','Broccoli','Cauliflower','Canola','Brussels Sprouts'], 'Grey-green aphid with waxy white coating. 2mm. Forms large dense colonies on stems, leaves and heads. Produces wax.', 'Dense colony feeding stunts growth. Head contamination ruins broccoli and cauliflower heads. Virus transmission. Honeydew and mould.', 'Dense grey-green colonies on stems and leaves. Wax-coated appearance. Stunted yellow heads. Contamination of harvested product.', 'Overwinters as eggs in mild climates. Parthenogenetic. Rapid colony build-up. Many generations per year.', 'Check growing tips and developing heads for colonies. Count infested plants per 10 checked.', '10% plants with colonies before head formation. Any colonies in developing broccoli heads.', 'Pirimicarb (most selective), dimethoate, pyrethroids. Pirimicarb spares parasitoids and lacewings. Check head contamination regularly near harvest.'),

('Macrosiphum euphorbiae', 'Potato Aphid', 'insect', ARRAY['Potato','Tomato','Capsicum','Lettuce'], 'Large green or pink aphid 3mm. Distinctive long cornicles. Spindle-shaped body. Lives on leaves and growing tips.', 'Direct sap feeding stunts growth. Transmits PVY, PLRV and CMV viruses in potato. Honeydew and sooty mould.', 'Curled leaves. Virus symptoms (mosaic, rolling). Stunted plants. Colonies on growing tips.', 'Overwinters as eggs on Rosa. Winged migrants colonise crops. Many generations. Key virus vector in potato seed crops.', 'Regular monitoring of growing tips. Count per plant or proportion of plants colonised. Yellow sticky traps for winged migrants.', '10% plants colonised in seed potato crops. Lower threshold when virus risk is high.', 'Pirimicarb, pymetrozine, imidacloprid, mineral oils (reduce virus transmission). Mineral oil sprays as stylet oil to prevent virus transmission.'),

('Daktulosphaira vitifoliae', 'Grape Phylloxera', 'insect', ARRAY['Grape','Vitis vinifera'], 'Tiny yellow aphid-like insect 1mm. Leaf galls and root nodules. Devastated European viticulture historically. Present in some Australian viticultural regions.', 'Root feeding causes root nodules (tuberosities) that rot and kill roots. Leaf galls in some varieties. Vine decline and death.', 'Root nodules and tuberosities visible on roots. Vine decline. Leaf galls in some varieties. General vine weakness and reduced cropping.', 'Parthenogenetic and sexual reproduction. Spreads by machinery, boots and infected planting material. Long-lived established populations.', 'Annual monitoring of vine health and root inspection. Boundary monitoring in clean regions. DNA testing for presence.', 'Any presence in Phylloxera Exclusion Zone regions requires immediate notification.', 'No effective insecticide control. Use resistant rootstocks (primary long-term management). Quarantine and biosecurity.'),

('Cephus cinctus', 'Wheat Stem Sawfly', 'insect', ARRAY['Wheat','Barley','Rye'], 'Slender yellow-black wasp 9-12mm. Larvae cream-white inside stems. Adults active during grain fill.', 'Larvae cut stems from inside near base causing lodging (cut stem). Significant yield losses in some regions.', 'Lodged wheat stems. Cut stems at ground level. Cream larvae inside stems.', 'Adults lay eggs inside stems at tillering. One generation per year. Pupate inside stem near soil.', 'Check stems for larval presence after harvest. Count cut stems at harvest.', '3-5% stems infested.', 'Solid-stemmed varieties resist larval movement. Parasitic wasps (Bracon cephi) provide biocontrol. Few effective insecticide options.'),

('Heliothrips haemorrhoidalis', 'Greenhouse Thrips', 'insect', ARRAY['Avocado','Mango','Stone Fruit','Ornamental'], 'Dark brown to black thrips 1.3mm. White fringed wings. Larvae pale yellow. Pupae in white waxy material. Lives on leaf underside.', 'Silvery feeding scars on leaf underside. Varnish-like excreta on leaves. Premature leaf fall. Fruit surface damage.', 'Silver feeding damage on leaf underside with characteristic dark faecal drops (varnish marks). Premature leaf drop.', 'Multiple generations per year. All stages present simultaneously. Spread by wind and plant movement.', 'Examine leaf undersurfaces for feeding damage and all stages.', 'Any significant infestation on avocado or mango.', 'Spinosad, abamectin, horticultural oil. Natural enemies (Thripobius parasitoid wasp) important.'),

('Paropsis charybdis', 'Eucalyptus Tortoise Beetle', 'insect', ARRAY['Eucalyptus plantation'], 'Bronze-brown oval beetle 10mm. Larvae orange-yellow with rows of black spots. Eggs laid in clusters.', 'Defoliates young eucalyptus plantations. Larvae and adults both feed. Multiple defoliations kill young trees.', 'Defoliated eucalyptus shoots. Larvae and adults on foliage. Egg clusters on leaves.', 'Two to three generations per year. Major plantation pest in SE Australia.', 'Monitor with beating tray. Inspect new plantations regularly in spring and summer.', '50% leaf area removed. Any defoliation in first-year plantations.', 'Pyrethroids for spray. Biological control with Eadya paropsidis parasitoid wasp.'),

('Aspidiotus nerii', 'Oleander Scale / Ivy Scale', 'insect', ARRAY['Citrus','Ornamental','Oleander'], 'Circular flat scale 1.5-2mm with white-yellow cover. Female beneath cover is yellow. Males smaller elongated.', 'Sap feeding on bark and leaves. Weakens plant. Dense infestations cause yellowing and dieback.', 'Circular white-yellow scales on bark and leaves. Yellowing and stunting. Dieback in heavy infestations.', 'Two to three generations per year. Crawlers dispersed by wind.', 'Check bark and leaves for scale infestations. Look for yellowing indicating infestation.', 'Any moderate infestation level on susceptible hosts.', 'White oil, petroleum oil at crawler stage. Imidacloprid systemic. Natural enemies (parasitic wasps) can provide good control.'),

('Spodoptera exempta', 'African Black Armyworm', 'insect', ARRAY['Maize','Sorghum','Millet','Pasture'], 'Dark black caterpillar with pale lateral stripe. 35-40mm. Mass movement behaviour. Characteristic armyworm.', 'Rapid defoliation of grasses and crops. Can devastate maize and sorghum in large numbers.', 'Stripped leaves. Mass movement of caterpillars at crop edges. Frass on soil surface.', 'Multiple generations. Long-distance migration. Outbreak pest periodic in northern Australia.', 'Monitor perimeter paddock edges. Check grass areas adjacent to crops.', '2+ per square metre or advancing fronts detected.', 'Pyrethroids, chlorpyrifos, spinosad. Apply at dusk.'),

('Cryptolaemus montrouzieri', 'Mealybug Destroyer (Beneficial)', 'insect', ARRAY['Glasshouse','Citrus','Grape','Ornamental'], 'Black ladybird 4mm with orange head and rear. Larvae look like mealybugs (white waxy). Predator of mealybugs.', 'Predator - consumes mealybug eggs and crawlers. Beneficial insect - do not spray with broad-spectrum insecticides.', 'Adult and larva both consume mealybugs. Larvae often mistaken for mealybugs.', 'Adult lays eggs in mealybug colonies. One generation per 25 days at 24C. Used in augmentative biocontrol.', 'Monitor presence in crops. Beneficial predator - protect from broad-spectrum sprays.', 'Biocontrol agent - release when mealybug colonies detected.', 'No chemical control needed - release and maintain population. Avoid broad-spectrum insecticides that kill this predator.'),

('Hippodamia variegata', 'Spotted Amber Ladybird (Beneficial)', 'insect', ARRAY['Canola','Cereal','Vegetable'], 'Orange ladybird with variable black spots. 4-5mm. Common aphid predator in Australian crops.', 'Predator of aphids. Each adult can consume 200+ aphids per day. Important natural enemy.', 'Beneficial predator - presence indicates aphid populations. Larvae resemble small alligators.', 'Multiple generations per year. Synchronised with aphid populations.', 'Record presence when scouting. Presence may indicate aphid populations but also natural suppression.', 'Biocontrol agent - protect from broad-spectrum sprays.', 'Protect natural enemies by using selective products (pirimicarb for aphids). Avoid broad-spectrum pyrethroids when ladybird populations are high.'),

('Neomaskellia andropogonis', 'Sugarcane Aphid', 'insect', ARRAY['Sorghum','Sugarcane'], 'Pale yellow to white aphid forming dense colonies on sorghum. New invasive pest established in Queensland from 2016.', 'Dense colony feeding causes stunting, honeydew sooty mould and yield loss. Severe infestations can kill plants.', 'Dense white-yellow colonies under sorghum leaves. Sooty mould from honeydew. Stunted plants. Plant death in severe cases.', 'Multiple generations per year. Explosive population growth in warm conditions. Relatively new pest in Australia.', 'Check lower leaf surface of sorghum from emergence. Count aphids per leaf on systematic samples.', '50-125 aphids per leaf in sorghum. Consult current state-specific thresholds.', 'Flupyradifurone (Sivanto), sulfoxaflor (Transform), imidacloprid, pyrethroids. Preserve natural enemies including parasitoids and lacewings.'),

('Aceria guerreronis', 'Coconut Mite', 'mite', ARRAY['Coconut'], 'Microscopic eriophyid mite. Invisible to naked eye. Lives under husk of young coconuts.', 'Feeding causes brown scarring of husk. Reduced nut quality. Husk splitting. Nut fall.', 'Brown scarring of husk under perianth. Distorted and disfigured nuts. Premature nut fall.', 'Continuous breeding under tropical conditions. Dispersed by wind and insects.', 'Remove perianth of young nuts to inspect for mites. Check percentage of nuts affected.', 'Any significant infestation in commercial coconut plantations.', 'Wettable sulfur, petroleum oil. Difficult to control under perianth. No highly effective chemicals available.');
