/*
  # Production Chemicals Seed - Part 2: Insecticides & Miticides (50 products)
*/

INSERT INTO agro_chemicals (product_name, active_ingredient, chemical_group, mode_of_action, formulation_type, category, target_type, manufacturer, registered_crops, target_issues, application_rate, withholding_period, reentry_period, label_notes, resistance_notes, apvma_registration) VALUES

-- INSECTICIDES
('Confidor 200 SL', 'Imidacloprid', 'Neonicotinoid', 'Nicotinic acetylcholine receptor agonist (4A)', 'Soluble Liquid', 'insecticide', 'pest', 'Bayer', ARRAY['Cotton','Tomato','Capsicum','Potato','Grape','Apple','Citrus','Canola','Brassica'], ARRAY['Green Peach Aphid','Cotton Aphid','Whitefly','Thrips','Mealybug','Scale'], '0.3-0.5 L/ha', '14 days (vegetable), 28 days (grape)', '48 hours', 'Systemic with long residual. Do not apply to flowering crops when bees are active.', 'IRAC Group 4A. High resistance risk in many pest species. Rotate with non-neonicotinoid groups.', '50280'),

('Karate Zeon 250 CS', 'Lambda-cyhalothrin', 'Pyrethroid', 'Sodium channel modulator (3A)', 'Capsule Suspension', 'insecticide', 'pest', 'Syngenta', ARRAY['Wheat','Barley','Canola','Sorghum','Cotton','Legume','Vegetable'], ARRAY['Helicoverpa','Aphid','Thrips','Whitefly','Loopers','Mirids','Grasshopper'], '0.1-0.2 L/ha', '7 days (vegetable), 14 days (grain)', '24 hours', 'Fast knockdown. Do not apply when bees are foraging. Toxic to aquatic invertebrates.', 'IRAC Group 3A. High resistance risk — rotate with non-pyrethroid groups.', '55842'),

('Movento 240 SC', 'Spirotetramat', 'Tetramic acid derivative', 'Acetyl-CoA carboxylase inhibitor (23)', 'Suspension Concentrate', 'insecticide', 'pest', 'Bayer', ARRAY['Grape','Apple','Citrus','Mango','Avocado','Stone Fruit','Vegetable'], ARRAY['Mealybug','Scale','Aphid','Whitefly','Psyllid','Mite'], '0.5-0.75 L/ha', '14 days', '24 hours', 'Bidirectional systemic — moves up and down in plant. Must add adjuvant. Apply during active growth.', 'IRAC Group 23. Low to moderate resistance risk. Rotate with Group 4 or 28.', '73425'),

('Altacor 35 WG', 'Chlorantraniliprole', 'Diamide', 'Ryanodine receptor activator (28)', 'Wettable Granule', 'insecticide', 'pest', 'DuPont', ARRAY['Apple','Pear','Stone Fruit','Grape','Tomato','Capsicum','Strawberry','Brassica','Sweet Corn'], ARRAY['Helicoverpa','Codling Moth','Light Brown Apple Moth','Leafroller','Oriental Fruit Moth'], '0.15-0.2 kg/ha', '7 days', '4 hours', 'Excellent residual activity. Low mammalian toxicity. Safe for most beneficial insects.', 'IRAC Group 28. Moderate resistance risk — rotate with non-diamide insecticides.', '76834'),

('Vertimec 18 EC', 'Abamectin', 'Avermectin', 'Chloride channel activator (6)', 'Emulsifiable Concentrate', 'insecticide', 'pest', 'Syngenta', ARRAY['Cotton','Grape','Vegetable','Citrus','Stone Fruit'], ARRAY['Two-spotted Mite','Leafminer','Thrips','Tomato Russet Mite'], '0.25-0.75 L/ha', '3 days (vegetable), 7 days (grape)', '12 hours', 'Translaminar activity excellent for leafminers. Effective against organophosphate-resistant mites.', 'IRAC Group 6. Moderate resistance risk — rotate with Groups 21 or 25.', '47823'),

('Lannate 250 L', 'Methomyl', 'Carbamate', 'Acetylcholinesterase inhibitor (1A)', 'Soluble Liquid', 'insecticide', 'pest', 'DuPont', ARRAY['Tomato','Cotton','Vegetable','Apple','Grape','Celery'], ARRAY['Helicoverpa','Aphid','Leafminer','Looper','Whitefly','Mites'], '1.0-2.0 L/ha', '1 day (tomato), 14 days (apple)', '48 hours', 'Broad-spectrum carbamate. High mammalian toxicity — wear full PPE. Short residual.', 'IRAC Group 1A. Cross-resistance with other carbamates and organophosphates possible.', '30142'),

('Coragen 200 SC', 'Chlorantraniliprole', 'Diamide', 'Ryanodine receptor activator (28)', 'Suspension Concentrate', 'insecticide', 'pest', 'DuPont', ARRAY['Sugarcane','Maize','Sorghum','Potato','Vegetable'], ARRAY['Greyback Cane Grub','Cane Grub','Cutworm','Helicoverpa','Armyworm'], '0.15-0.5 L/ha', '14 days', '4 hours', 'Soil and foliar applications available. Grub control in sugarcane at planting.', 'IRAC Group 28. Rotate with non-diamide actives for resistance management.', '77249'),

('Tracer 480 SC', 'Spinosad', 'Spinosyn', 'Nicotinic receptor allosteric activator (5)', 'Suspension Concentrate', 'insecticide', 'pest', 'Dow AgroSciences', ARRAY['Cotton','Vegetable','Apple','Grape','Citrus','Stone Fruit'], ARRAY['Helicoverpa','Thrips','Leafminer','Loopers','Codling Moth','Light Brown Apple Moth'], '0.12-0.2 L/ha', '1 day (vegetable), 7 days (fruit)', '4 hours', 'Derived from soil bacterium Saccharopolyspora spinosa. OMRI listed version available.', 'IRAC Group 5. Moderate resistance risk — rotate with non-spinosyn groups.', '62741'),

('Delegate WG', 'Spinetoram', 'Spinosyn', 'Nicotinic receptor allosteric activator (5)', 'Wettable Granule', 'insecticide', 'pest', 'Dow AgroSciences', ARRAY['Apple','Pear','Stone Fruit','Grape','Citrus','Strawberry','Vegetable'], ARRAY['Codling Moth','Light Brown Apple Moth','Thrips','Leafroller','Oriental Fruit Moth'], '0.16-0.24 kg/ha', '1 day (vegetable), 7 days (fruit)', '4 hours', 'Next-generation spinosyn with broader spectrum and higher potency than spinosad.', 'IRAC Group 5. Cross-resistance with spinosad reported — rotate with Groups 28 or 6.', '78342'),

('Dimethoate 400 EC', 'Dimethoate', 'Organophosphate', 'Acetylcholinesterase inhibitor (1B)', 'Emulsifiable Concentrate', 'insecticide', 'pest', 'Nufarm', ARRAY['Wheat','Barley','Canola','Brassica','Legume','Vegetable','Pasture'], ARRAY['Aphid','Russian Wheat Aphid','Mites','Thrips','Biting Flies','Redlegged Earth Mite'], '0.5-1.0 L/ha', '14 days (grain), 7 days (vegetable)', '48 hours', 'Broad-spectrum systemic organophosphate. Moderate mammalian toxicity.', 'IRAC Group 1B. High resistance risk in many pest species.', '26341'),

('Chlorpyrifos 500 EC', 'Chlorpyrifos', 'Organophosphate', 'Acetylcholinesterase inhibitor (1B)', 'Emulsifiable Concentrate', 'insecticide', 'pest', 'Dow AgroSciences', ARRAY['Wheat','Barley','Canola','Sorghum','Cotton','Pasture','Horticulture'], ARRAY['Army Worm','Helicoverpa','Aphid','Earth Mite','Cutworm','Soil Pests','Termite'], '0.5-2.0 L/ha', '14-30 days (crop dependent)', '48 hours', 'Broad-spectrum soil and foliar insecticide. Do not apply to flowering crops.', 'IRAC Group 1B. Cross-resistance with other organophosphates.', '30628'),

('Brigadier 200 SC', 'Bifenthrin', 'Pyrethroid', 'Sodium channel modulator (3A)', 'Suspension Concentrate', 'insecticide', 'pest', 'FMC', ARRAY['Cotton','Vegetable','Ornamental','Turf','Forestry'], ARRAY['Helicoverpa','Thrips','Whitefly','Mites','Ants','Spider Mite'], '0.15-0.25 L/ha', '14 days', '24 hours', 'Long-residual pyrethroid. Some miticide activity.', 'IRAC Group 3A. High resistance risk — rotate with non-pyrethroids.', '57423'),

('Baythroid Advanced', 'Beta-cyfluthrin', 'Pyrethroid', 'Sodium channel modulator (3A)', 'Suspension Concentrate', 'insecticide', 'pest', 'Bayer', ARRAY['Wheat','Barley','Canola','Sorghum','Pasture','Vegetable'], ARRAY['Aphid','Mirids','Army Worm','Helicoverpa','Thrips','Locusts'], '0.05-0.15 L/ha', '7 days (vegetable), 30 days (grain)', '24 hours', 'Fast knockdown pyrethroid. Excellent aerial application results.', 'IRAC Group 3A. High resistance risk in heliothis populations.', '63124'),

('Decis 100 EC', 'Deltamethrin', 'Pyrethroid', 'Sodium channel modulator (3A)', 'Emulsifiable Concentrate', 'insecticide', 'pest', 'Bayer', ARRAY['Wheat','Canola','Sorghum','Vegetable','Cotton','Grape'], ARRAY['Aphid','Mirids','Thrips','Army Worm','Helicoverpa','Whitefly'], '0.1-0.3 L/ha', '7 days (vegetable), 14 days (grain)', '24 hours', 'Broad-spectrum fast knockdown. One of the most widely used pyrethroids.', 'IRAC Group 3A. Rotate with Groups 4 or 28 for resistance management.', '25841'),

('Fury 200 EW', 'Zeta-cypermethrin', 'Pyrethroid', 'Sodium channel modulator (3A)', 'Emulsion Oil in Water', 'insecticide', 'pest', 'FMC', ARRAY['Cotton','Vegetable','Canola','Grain Legume'], ARRAY['Helicoverpa','Aphid','Thrips','Diamondback Moth','Looper'], '0.15-0.2 L/ha', '7 days', '24 hours', 'Good rainfastness. Reduced phytotoxicity risk vs EC formulation.', 'IRAC Group 3A. Resistance widespread in H. armigera.', '64213'),

('Pirimicarb 500 WG', 'Pirimicarb', 'Carbamate', 'Acetylcholinesterase inhibitor (1A)', 'Wettable Granule', 'insecticide', 'pest', 'Syngenta', ARRAY['Wheat','Barley','Canola','Brassica','Vegetable','Grape'], ARRAY['Green Peach Aphid','Russian Wheat Aphid','Aphid species'], '0.25-0.5 kg/ha', '7 days', '24 hours', 'Selective aphicide — spares most predatory insects. Vapour active at warm temperatures.', 'IRAC Group 1A. Some pirimicarb-resistant aphid biotypes exist.', '39421'),

('Fastac 100 EC', 'Alpha-cypermethrin', 'Pyrethroid', 'Sodium channel modulator (3A)', 'Emulsifiable Concentrate', 'insecticide', 'pest', 'BASF', ARRAY['Wheat','Canola','Grain Legume','Cotton','Pasture'], ARRAY['Aphid','Army Worm','Helicoverpa','Loopers','Mirids','Grasshopper'], '0.1-0.15 L/ha', '7 days', '24 hours', 'Fast knockdown broad-spectrum pyrethroid.', 'IRAC Group 3A. High resistance risk — rotate with non-pyrethroids.', '48731'),

('Sumithion 500 EC', 'Fenitrothion', 'Organophosphate', 'Acetylcholinesterase inhibitor (1B)', 'Emulsifiable Concentrate', 'insecticide', 'pest', 'Sumitomo', ARRAY['Wheat','Barley','Oats','Stored Grain'], ARRAY['Weevil','Beetle','Aphid','Grasshopper','Locust'], '1.0-2.0 L/ha', '14 days (grain)', '48 hours', 'Key stored grain insecticide. Mix with grain protectant synergists.', 'IRAC Group 1B. Some resistance documented in storage pests.', '23156'),

('Actellic 500 EC', 'Pirimiphos-methyl', 'Organophosphate', 'Acetylcholinesterase inhibitor (1B)', 'Emulsifiable Concentrate', 'insecticide', 'pest', 'Syngenta', ARRAY['Stored Grain','Wheat','Barley','Sorghum','Maize'], ARRAY['Grain Weevil','Flour Beetle','Grain Borer','Psocid'], '1.5-3.0 mL/tonne grain', '0 days', '24 hours', 'Primary storage grain treatment. Apply to grain at receival. Combine with physical control.', 'IRAC Group 1B. Resistance in psocids documented in Australia.', '41372'),

('Imidacloprid 600 FS', 'Imidacloprid', 'Neonicotinoid', 'Nicotinic receptor agonist (4A)', 'Flowable Seed Treatment', 'insecticide', 'pest', 'Bayer', ARRAY['Wheat','Barley','Canola','Cotton','Sorghum','Sunflower'], ARRAY['Aphid','Wireworm','Soil Pests','Russian Wheat Aphid','Lucerne Flea'], '75-150 mL/100 kg seed', '0 days', 'N/A', 'Seed treatment for early season protection. Do not use treated seed as food or feed.', 'IRAC Group 4A. Seed treatment — lower resistance selection pressure than foliar.', '56842'),

('Thiamethoxam 350 FS', 'Thiamethoxam', 'Neonicotinoid', 'Nicotinic receptor agonist (4A)', 'Flowable Seed Treatment', 'insecticide', 'pest', 'Syngenta', ARRAY['Wheat','Barley','Canola','Sorghum','Maize','Sunflower'], ARRAY['Aphid','Russian Wheat Aphid','Soil Insects','Wireworm'], '70-140 mL/100 kg seed', '0 days', 'N/A', 'Systemic seed treatment. Excellent early season aphid control.', 'IRAC Group 4A. High resistance risk — avoid consecutive neonicotinoid use.', '68241'),

('Assail 70 WP', 'Acetamiprid', 'Neonicotinoid', 'Nicotinic receptor agonist (4A)', 'Wettable Powder', 'insecticide', 'pest', 'United Phosphorus', ARRAY['Apple','Pear','Stone Fruit','Citrus','Vegetable','Grape'], ARRAY['Aphid','Whitefly','Thrips','Leafhopper','Mealybug'], '0.08-0.16 kg/ha', '7 days', '12 hours', 'Lower bee toxicity than other neonicotinoids. Good translaminar activity.', 'IRAC Group 4A. Moderate resistance risk. Rotate with Groups 6 or 28.', '72531'),

('Calypso 480 SC', 'Thiacloprid', 'Neonicotinoid', 'Nicotinic receptor agonist (4A)', 'Suspension Concentrate', 'insecticide', 'pest', 'Bayer', ARRAY['Apple','Pear','Stone Fruit','Citrus','Vegetable'], ARRAY['Aphid','Mealybug','Scale','Whitefly','Codling Moth'], '0.3-0.5 L/ha', '14 days', '24 hours', 'Lower bee risk than imidacloprid. Good bark penetration for scale control.', 'IRAC Group 4A. Moderate resistance risk.', '74823'),

('Actara 240 SC', 'Thiamethoxam', 'Neonicotinoid', 'Nicotinic receptor agonist (4A)', 'Suspension Concentrate', 'insecticide', 'pest', 'Syngenta', ARRAY['Cotton','Vegetable','Tomato','Potato','Apple','Citrus'], ARRAY['Whitefly','Aphid','Thrips','Mealybug','Potato Leafhopper'], '0.15-0.25 L/ha', '7 days (vegetable), 14 days (fruit)', '4 hours', 'Fast systemic uptake. Apply to soil or foliar.', 'IRAC Group 4A. High resistance risk in silverleaf whitefly. Monitor.', '68943'),

('Pegasus 500 SC', 'Diafenthiuron', 'Thiocarbamate', 'Mitochondrial ATP synthase inhibitor (12A)', 'Suspension Concentrate', 'insecticide', 'pest', 'Syngenta', ARRAY['Cotton','Vegetable'], ARRAY['Two-spotted Mite','Thrips','Whitefly'], '0.75-1.0 L/ha', '3 days', '24 hours', 'Requires UV activation after application. Good residual.', 'IRAC Group 12A. Low resistance risk. Excellent resistance management partner for pyrethroids.', '62341'),

('Oberon 240 SC', 'Spiromesifen', 'Tetronic acid derivative', 'Acetyl-CoA carboxylase inhibitor (23)', 'Suspension Concentrate', 'insecticide', 'pest', 'Bayer', ARRAY['Cotton','Vegetable','Tomato','Capsicum','Cucumber','Grape'], ARRAY['Two-spotted Mite','Silverleaf Whitefly','Broad Mite'], '0.5-0.75 L/ha', '1 day (vegetable), 7 days (grape)', '12 hours', 'Ovicidal and larvicidal activity. Excellent for IPM programs.', 'IRAC Group 23. Low resistance risk. Alternate with Groups 10A or 21.', '77834'),

('Voliam Flexi', 'Chlorantraniliprole + Thiamethoxam', 'Diamide + Neonicotinoid', 'IRAC 28 + 4A dual mode', 'Suspension Concentrate', 'insecticide', 'pest', 'Syngenta', ARRAY['Maize','Sorghum','Sunflower','Canola'], ARRAY['Helicoverpa','Aphid','Thrips','Cutworm','Soil Pests'], '0.35-0.5 L/ha', '14 days', '4 hours', 'Dual mode seed or foliar treatment. Broad-spectrum protection.', 'IRAC 28+4A. Rotate to avoid resistance in both components.', '81234'),

('Belt 480 SC', 'Flubendiamide', 'Diamide', 'Ryanodine receptor activator (28)', 'Suspension Concentrate', 'insecticide', 'pest', 'Bayer', ARRAY['Brassica','Tomato','Capsicum','Cucumber','Pumpkin','Bean'], ARRAY['Helicoverpa','Loopers','Diamondback Moth','Cabbage White Butterfly'], '0.15-0.2 L/ha', '7 days', '4 hours', 'Excellent caterpillar control. 14-day residual.', 'IRAC Group 28. Moderate resistance risk — rotate with Group 5 or 6.', '78923'),

('Avatar 600 SC', 'Indoxacarb', 'Oxadiazine', 'Sodium channel blocker (22A)', 'Suspension Concentrate', 'insecticide', 'pest', 'DuPont', ARRAY['Cotton','Tomato','Capsicum','Bean','Brassica'], ARRAY['Helicoverpa','Loopers','Armyworm','Leafworm','Bollworm'], '0.3-0.4 L/ha', '7 days', '12 hours', 'Pro-insecticide activated by insects. Biopesticide-compatible.', 'IRAC Group 22A. Moderate resistance risk. Rotate with Groups 28 or 5.', '72641'),

('Proclaim 5 SG', 'Emamectin benzoate', 'Avermectin', 'Chloride channel activator (6)', 'Soluble Granule', 'insecticide', 'pest', 'Syngenta', ARRAY['Apple','Pear','Stone Fruit','Grape','Citrus','Vegetable'], ARRAY['Codling Moth','Leafroller','Light Brown Apple Moth','Helicoverpa'], '0.12-0.2 kg/ha', '7 days', '12 hours', 'Excellent translaminar activity. Particularly effective against diamide-resistant caterpillars.', 'IRAC Group 6. Moderate resistance risk — rotate with Group 28.', '74521'),

('Success 480 SC', 'Spinosad', 'Spinosyn', 'Nicotinic receptor allosteric activator (5)', 'Suspension Concentrate', 'insecticide', 'pest', 'Dow AgroSciences', ARRAY['Vegetable','Grape','Stone Fruit','Apple','Citrus'], ARRAY['Thrips','Helicoverpa','Loopers','Leafminer'], '0.075-0.15 L/ha', '1 day (vegetable), 7 days (fruit)', '4 hours', 'Excellent efficacy on thrips. Low mammalian toxicity. Suitable for IPM programs.', 'IRAC Group 5. Rotate with Group 28 or non-spinosyn products.', '62742'),

('Diazinon 800 WG', 'Diazinon', 'Organophosphate', 'Acetylcholinesterase inhibitor (1B)', 'Wettable Granule', 'insecticide', 'pest', 'Adama', ARRAY['Ornamental','Turf','Banana','Pasture'], ARRAY['Aphid','Mites','Scale','Ants','Beetles'], '1.0-2.0 kg/ha', '14 days', '48 hours', 'Lower mammalian toxicity than many OPs. Good turf pest control.', 'IRAC Group 1B. Moderate resistance risk.', '32841'),

('Talstar 100 EC', 'Bifenthrin', 'Pyrethroid', 'Sodium channel modulator (3A)', 'Emulsifiable Concentrate', 'insecticide', 'pest', 'FMC', ARRAY['Cotton','Vegetable','Fruit','Ornamental','Turf'], ARRAY['Helicoverpa','Thrips','Mites','Whitefly','Ants'], '0.15-0.25 L/ha', '14 days', '24 hours', 'Long residual. Some acaricidal activity against mites.', 'IRAC Group 3A. Cross-resistance with other pyrethroids common.', '57424'),

('Aphidius-based Biocontrol', 'Aphidius colemani', 'Parasitic Wasp', 'Biological control (UN)', 'Live insect', 'insecticide', 'pest', 'Koppert', ARRAY['Glasshouse crops','Capsicum','Cucumber','Tomato','Lettuce'], ARRAY['Green Peach Aphid','Cotton Aphid','Foxglove Aphid'], '3-10 per sq m per week', '0 days', '0 hours', 'Release when aphid colonies are small. Monitor weekly. Store at 8-10C.', 'No resistance risk — biological control.', 'N/A'),

('Dipel DF', 'Bacillus thuringiensis var. kurstaki', 'Microbial (Bt)', 'Midgut pore formation (11A)', 'Dry Flowable', 'insecticide', 'pest', 'Sumitomo', ARRAY['Vegetable','Fruit','Ornamental','Cotton'], ARRAY['Helicoverpa','Loopers','Diamondback Moth','Cabbage White Butterfly','Cabbage Moth'], '0.5-1.5 kg/ha', '0 days', '0 hours', 'Apply in late afternoon. Requires ingestion by larvae. UV-labile — short residual.', 'IRAC Group 11A. Some Bt resistance documented in diamondback moth.', '47231'),

('Confirm 240 SC', 'Tebufenozide', 'Diacylhydrazine', 'Ecdysone receptor agonist (18)', 'Suspension Concentrate', 'insecticide', 'pest', 'Dow AgroSciences', ARRAY['Apple','Pear','Stone Fruit','Grape','Cotton','Vegetable'], ARRAY['Codling Moth','Light Brown Apple Moth','Leafroller','Helicoverpa'], '0.4-0.6 L/ha', '7 days', '4 hours', 'Selective for Lepidoptera. Excellent for IPM programs. Low bee toxicity.', 'IRAC Group 18. Very low resistance risk. Excellent resistance management tool.', '65231'),

('Pyriproxyfen 100 EC', 'Pyriproxyfen', 'Pyridine', 'Juvenile hormone mimic (7C)', 'Emulsifiable Concentrate', 'insecticide', 'pest', 'Sumitomo', ARRAY['Citrus','Tomato','Cotton','Vegetable'], ARRAY['Whitefly','Scale','Mealybug','Thrips'], '0.5 L/ha', '7 days', '12 hours', 'Insect growth regulator — stops egg hatch and juvenile development. Not for adult insects.', 'IRAC Group 7C. Low resistance risk.', '68124'),

('Buprofezin 400 SC', 'Buprofezin', 'Thiadiazine', 'Chitin synthesis inhibitor Type 1 (16)', 'Suspension Concentrate', 'insecticide', 'pest', 'Nichino', ARRAY['Cotton','Vegetable','Citrus','Stone Fruit'], ARRAY['Whitefly','Scale','Leafhopper','Mealybug'], '0.5-0.75 L/ha', '7 days', '12 hours', 'Growth regulator — affects juvenile stages only. Persistent residual.', 'IRAC Group 16. Low resistance risk.', '61342'),

('Methidathion 400 EC', 'Methidathion', 'Organophosphate', 'Acetylcholinesterase inhibitor (1B)', 'Emulsifiable Concentrate', 'insecticide', 'pest', 'Cheminova', ARRAY['Citrus','Apple','Stone Fruit','Olive'], ARRAY['Scale','Mite','Aphid','Woolly Apple Aphid','Mealybug'], '1.5-2.0 L/ha', '14 days', '48 hours', 'Key citrus scale and mite product. Avoid in high temperatures.', 'IRAC Group 1B. Resistance documented in some citrus scale populations.', '21435'),

('Supracide 400 EC', 'Methidathion', 'Organophosphate', 'Acetylcholinesterase inhibitor (1B)', 'Emulsifiable Concentrate', 'insecticide', 'pest', 'Syngenta', ARRAY['Citrus','Apple','Olive','Stone Fruit'], ARRAY['Scale','Mite','Aphid'], '1.5-2.0 L/ha', '14 days', '48 hours', 'Alternative methidathion brand. Same precautions apply.', 'IRAC Group 1B. See Methidathion resistance notes.', '21436'),

('Exirel 100 SE', 'Cyantraniliprole', 'Diamide', 'Ryanodine receptor activator (28)', 'Suspension Emulsion', 'insecticide', 'pest', 'DuPont', ARRAY['Apple','Pear','Stone Fruit','Grape','Tomato','Capsicum','Citrus'], ARRAY['Thrips','Leafminer','Whitefly','Aphid','Leafhopper','Psyllid'], '0.5-1.0 L/ha', '7 days', '4 hours', 'Unique for diamide class — active against whitefly and leafminer. Good systemic activity.', 'IRAC Group 28. Moderate resistance risk — rotate with Groups 6 or 9.', '82341'),

('Agri-Mectin 18 EC', 'Abamectin', 'Avermectin', 'Chloride channel activator (6)', 'Emulsifiable Concentrate', 'insecticide', 'pest', 'Adama', ARRAY['Cotton','Grape','Vegetable','Citrus'], ARRAY['Two-spotted Mite','Leafminer','Tomato Russet Mite'], '0.5-0.75 L/ha', '7 days', '12 hours', 'Generic abamectin. Same activity as Vertimec.', 'IRAC Group 6. Cross-resistance with emamectin benzoate possible.', '71234'),

-- MITICIDES
('Miticide 240 SC', 'Hexythiazox', 'Thiazolidinone', 'Acetyl-CoA carboxylase inhibitor (10A)', 'Suspension Concentrate', 'miticide', 'pest', 'Nippon Soda', ARRAY['Apple','Pear','Grape','Citrus','Stone Fruit','Strawberry'], ARRAY['Two-spotted Mite','European Red Mite','Citrus Red Mite'], '0.5-1.0 L/ha', '14 days', '12 hours', 'Effective against eggs and juvenile stages. Not active on adult mites. Long residual.', 'IRAC Group 10A. Rotate with Groups 6, 25 or 21.', '46231'),

('Envidor 240 SC', 'Spirodiclofen', 'Tetronic acid derivative', 'Acetyl-CoA carboxylase inhibitor (23)', 'Suspension Concentrate', 'miticide', 'pest', 'Bayer', ARRAY['Apple','Pear','Stone Fruit','Citrus','Grape'], ARRAY['Two-spotted Mite','European Red Mite','Citrus Red Mite','Broad Mite'], '0.5-0.75 L/ha', '14 days', '12 hours', 'Ovicidal and larvicidal. One application controls population for season.', 'IRAC Group 23. Cross-resistance with spiromesifen possible. One application per season.', '77234'),

('Paramite 480 EC', 'Dicofol', 'Organochlorine', 'Unknown mechanism (23B)', 'Emulsifiable Concentrate', 'miticide', 'pest', 'AMVAC', ARRAY['Apple','Pear','Stone Fruit','Grape','Tomato'], ARRAY['Two-spotted Mite','European Red Mite','Broad Mite'], '2.0-3.0 L/ha', '14 days', '48 hours', 'Old chemistry. OPP phased out in many countries. Check current status.', 'IRAC Group 23B. Some resistance documented.', '18234'),

('Portal 250 SC', 'Fenpyroximate', 'Pyrazole', 'Mitochondrial electron transport inhibitor (21A)', 'Suspension Concentrate', 'miticide', 'pest', 'Nichino', ARRAY['Apple','Pear','Stone Fruit','Citrus','Grape','Strawberry'], ARRAY['Two-spotted Mite','European Red Mite','Citrus Red Mite','Bud Mite'], '0.4-0.6 L/ha', '14 days', '12 hours', 'Fast knockdown of all mobile stages. Limited ovicidal activity.', 'IRAC Group 21A. Rotate with Groups 23 or 10A.', '70234'),

('Nissorum 100 WP', 'Hexythiazox', 'Thiazolidinone', 'Acetyl-CoA carboxylase inhibitor (10A)', 'Wettable Powder', 'miticide', 'pest', 'Nippon Soda', ARRAY['Apple','Grape','Stone Fruit'], ARRAY['Two-spotted Mite','European Red Mite'], '0.3-0.5 kg/ha', '14 days', '12 hours', 'Alternative hexythiazox brand. Effective early season at egg stage.', 'IRAC Group 10A. One application per season recommended.', '46232'),

('Nexter 200 SC', 'Pyridaben', 'Pyridazinone', 'Mitochondrial electron transport inhibitor (21A)', 'Suspension Concentrate', 'miticide', 'pest', 'Dow AgroSciences', ARRAY['Apple','Pear','Grape','Citrus','Tomato'], ARRAY['Two-spotted Mite','European Red Mite','Broad Mite','Russet Mite'], '0.4-0.6 L/ha', '14 days', '12 hours', 'Broad-spectrum miticide with fast knockdown. Effective against all stages.', 'IRAC Group 21A. Rotate with Groups 23 or 10A for resistance management.', '65834'),

('Oil DC Tron Plus', 'Petroleum Oil', 'Petroleum oil', 'Physical mode (UN)', 'Miscible Oil', 'miticide', 'pest', 'Ampol', ARRAY['Apple','Pear','Stone Fruit','Citrus','Grape','Mango'], ARRAY['Scale','Mealybug','Mite eggs','European Red Mite','Rust Mite'], '8-20 L/ha (diluted)', '0 days', '2 hours', 'Dormant/summer oil. Controls overwintering eggs and soft-bodied insects. Do not apply in heat >35C.', 'No resistance risk — physical mode.', '14231'),

('Acaricide 50 WP', 'Cyhexatin', 'Organotin', 'Mitochondrial electron transport inhibitor (12B)', 'Wettable Powder', 'miticide', 'pest', 'Various', ARRAY['Apple','Stone Fruit'], ARRAY['Two-spotted Mite','European Red Mite'], '0.25-0.5 kg/ha', '14 days', '24 hours', 'Older organotin miticide. Restricted use in some states.', 'IRAC Group 12B. Some cross-resistance with fenbutatin oxide reported.', '19234');
