/*
  # Production Chemicals Seed - Part 3: Herbicides (60 products)
*/

INSERT INTO agro_chemicals (product_name, active_ingredient, chemical_group, mode_of_action, formulation_type, category, target_type, manufacturer, registered_crops, target_issues, application_rate, withholding_period, reentry_period, label_notes, resistance_notes, apvma_registration) VALUES

('Roundup Ultra MAX', 'Glyphosate', 'Glycine', 'EPSPS inhibitor (9)', 'Soluble Liquid', 'herbicide', 'weed', 'Monsanto', ARRAY['Fallow','Pasture','All crops (pre-plant)','Non-crop'], ARRAY['Annual Ryegrass','Wild Radish','Capeweed','Barnyard Grass','Bindweed','Fleabane','Sowthistle'], '1.5-3.0 L/ha', '0 days', '4 hours', 'Broad-spectrum non-selective. Apply to actively growing weeds. Do not apply to drought-stressed weeds.', 'HRAC Group 9. Widespread glyphosate resistance in Australia — particularly ryegrass and fleabane.', '49321'),

('Atrazine 900 WG', 'Atrazine', 'Triazine', 'Photosynthesis inhibitor (PS II) (C1)', 'Wettable Granule', 'herbicide', 'weed', 'Nufarm', ARRAY['Maize','Sorghum','Sugarcane'], ARRAY['Barnyard Grass','Crabgrass','Fat Hen','Annual Ryegrass','Pigweed'], '1.5-2.5 kg/ha', '0 days (post-plant, pre-emergent)', '24 hours', 'Apply pre-emergent or very early post-emergent. Do not use on sandy soils or near waterways.', 'HRAC Group C1. Widespread resistance in Australia — particularly in ryegrass.', '24821'),

('Topik 240 EC', 'Clodinafop-propargyl', 'Aryloxyphenoxypropionate (AOPP)', 'ACCase inhibitor (A)', 'Emulsifiable Concentrate', 'herbicide', 'weed', 'Syngenta', ARRAY['Wheat','Barley','Oats','Triticale'], ARRAY['Annual Ryegrass','Wild Oat','Canary Grass'], '0.3-0.4 L/ha', '60 days', '12 hours', 'Post-emergent grass-selective. Add adjuvant for improved uptake. Do not apply in frost or extreme heat.', 'HRAC Group A. Very high resistance risk — resistance widespread in ryegrass. Rotate to non-FOP.', '55241'),

('Sakura 850 WG', 'Pyroxasulfone', 'Isoxazoline', 'VLCFA inhibitor (K3)', 'Wettable Granule', 'herbicide', 'weed', 'Kumiai', ARRAY['Wheat','Barley','Canola','Chickpea'], ARRAY['Annual Ryegrass','Wild Oat','Brome Grass','Canary Grass','Phalaris'], '0.12-0.18 kg/ha', '0 days (pre-emergent)', '12 hours', 'Pre-emergent application — requires rainfall or irrigation for activation. Excellent ryegrass control.', 'HRAC Group K3. Relatively new — monitor for resistance development.', '78342'),

('Intervix', 'Imazamox + Imazapyr', 'Imidazolinone', 'ALS inhibitor (B)', 'Soluble Concentrate', 'herbicide', 'weed', 'BASF', ARRAY['Clearfield Wheat','Clearfield Canola','Clearfield Barley'], ARRAY['Annual Ryegrass','Wild Radish','Prickly Lettuce','Brome Grass','Wild Oat'], '0.6 L/ha', '60 days', '12 hours', 'Only use in Clearfield varieties. Do not follow with sensitive crops for 12 months.', 'HRAC Group B. Cross-resistance with sulfonylureas widespread. Do not use where B-group resistance detected.', '75234'),

('Amicide 625', 'Amine 625 (2,4-D)', '2,4-D', 'Auxin mimic (O)', 'Soluble Concentrate', 'herbicide', 'weed', 'Nufarm', ARRAY['Wheat','Barley','Oats','Pasture','Non-crop'], ARRAY['Capeweed','Sowthistle','Bindweed','Wild Radish','Clover'], '0.5-2.0 L/ha', '7 days', '24 hours', 'Apply in 3-4 leaf stage of cereal. Avoid drift to sensitive broadleaf crops. Do not use in high temperatures.', 'HRAC Group O. Some resistance documented in wild radish in WA.', '12481'),

('Verdict 520 EC', 'Haloxyfop-P-methyl', 'AOPP', 'ACCase inhibitor (A)', 'Emulsifiable Concentrate', 'herbicide', 'weed', 'Dow AgroSciences', ARRAY['Canola','Chickpea','Faba Bean','Lupin','Sunflower','Lentil','Brassica'], ARRAY['Annual Ryegrass','Wild Oat','Brome Grass','Barley Grass','Barnyard Grass'], '0.3-0.5 L/ha', '7 days', '12 hours', 'Selective grass herbicide for broadleaf crops. Add crop oil or adjuvant. Highly effective on resistant ryegrass biotypes.', 'HRAC Group A. Resistance in ryegrass documented — always use in rotation with other modes.', '47821'),

('Tigrex', 'Metribuzin + Trifluralin', 'Triazinone + Dinitroaniline', 'PS II + Tubulin inhibitor (C1 + K1)', 'Suspension Concentrate', 'herbicide', 'weed', 'Adama', ARRAY['Chickpea','Lentil','Faba Bean'], ARRAY['Annual Ryegrass','Prickly Lettuce','Fumitory','Sowthistle','Capeweed','Wire Weed'], '1.0-2.0 L/ha', '0 days (pre-emergent)', '12 hours', 'Pre-emergent twin-mode herbicide. Apply before weed emergence on moist soil.', 'HRAC C1+K1. Dual mode helps reduce resistance risk.', '63241'),

('Broadstrike', 'Flumetsulam', 'Triazolopyrimidine sulfonamide', 'ALS inhibitor (B)', 'Dry Flowable', 'herbicide', 'weed', 'Dow AgroSciences', ARRAY['Chickpea','Faba Bean','Lupin','Soybean'], ARRAY['Capeweed','Prickly Lettuce','Wild Radish','Sowthistle','Fumitory'], '0.03-0.04 kg/ha', '0 days', '12 hours', 'Very low use rate ALS inhibitor for broadleaf crops.', 'HRAC Group B. High resistance risk — do not use consecutively.', '55824'),

('Boxer Gold', 'Prosulfocarb + S-metolachlor', 'Thiocarbamate + Chloroacetamide', 'VLCFA inhibitor (N + K3)', 'Emulsifiable Concentrate', 'herbicide', 'weed', 'Syngenta', ARRAY['Wheat','Barley','Triticale'], ARRAY['Annual Ryegrass','Brome Grass','Barley Grass','Wild Oat','Canary Grass'], '3.5-4.5 L/ha', '0 days (pre-emergent)', '24 hours', 'Pre-emergent. Apply to moist soil and incorporate with rainfall within 7 days.', 'HRAC N+K3. Excellent resistance management tool — dual non-ALS, non-FOP mode.', '76542'),

('Trifluralin 480 EC', 'Trifluralin', 'Dinitroaniline', 'Tubulin polymerisation inhibitor (K1)', 'Emulsifiable Concentrate', 'herbicide', 'weed', 'Nufarm', ARRAY['Canola','Chickpea','Lupin','Soybean','Cotton','Sunflower'], ARRAY['Annual Ryegrass','Brome Grass','Wild Oat','Barnyard Grass','Pigweed','Crabgrass'], '1.2-2.4 L/ha', '0 days', '24 hours', 'Pre-emergent — must be incorporated into soil within 8 hours of application. Cannot be used on sand.', 'HRAC Group K1. Resistance documented in annual ryegrass in Australia.', '22341'),

('Eclipse 700 WG', 'Metribuzin', 'Triazinone', 'Photosynthesis inhibitor (PS II) (C1)', 'Wettable Granule', 'herbicide', 'weed', 'Adama', ARRAY['Potato','Tomato','Asparagus','Wheat (winter)'], ARRAY['Annual Ryegrass','Chickweed','Sowthistle','Capeweed','Prickly Lettuce'], '0.35-1.0 kg/ha', '60 days (wheat)', '12 hours', 'Pre or early post-emergent. Do not use on stressed crops.', 'HRAC Group C1. Resistance risk in ryegrass. Rotate with non-PS II actives.', '41234'),

('Matador 500 EC', 'Quizalofop-p-ethyl', 'AOPP', 'ACCase inhibitor (A)', 'Emulsifiable Concentrate', 'herbicide', 'weed', 'Syngenta', ARRAY['Canola','Chickpea','Lupin','Sunflower','Lentil'], ARRAY['Annual Ryegrass','Wild Oat','Barley Grass','Brome Grass'], '0.25-0.75 L/ha', '0 days', '12 hours', 'Post-emergent grass control in broadleaf crops. Add crop oil.', 'HRAC Group A. Resistance to FOPs widespread in annual ryegrass.', '46321'),

('Grazon Extra', 'Triclopyr + Picloram', 'Pyridine carboxylic acid', 'Auxin mimic (O)', 'Soluble Liquid', 'herbicide', 'weed', 'Dow AgroSciences', ARRAY['Pasture','Non-crop','Native vegetation management'], ARRAY['Serrated Tussock','St Johns Wort','Blackberry','Woody Weeds','Lantana','Scotch Thistle'], '1.5-10.0 L/ha', '12 weeks (before grazing)', '24 hours', 'Do not apply near desirable trees — picloram root uptake risk. Check soil persistence.', 'HRAC Group O. Low resistance risk in target species.', '52342'),

('Paraquat 250 SL', 'Paraquat', 'Bipyridinium', 'PS I electron diverter (D)', 'Soluble Liquid', 'herbicide', 'weed', 'Syngenta', ARRAY['Fallow','Non-crop','Orchards (under tree)','Vineyards'], ARRAY['Annual Ryegrass','Capeweed','Sowthistle','Barnyard Grass','Wild Radish'], '1.0-3.0 L/ha', '0 days', '24 hours', 'Rapid contact knockdown. No soil activity. Combination with soil-acting herbicides gives best results.', 'HRAC Group D. Highly toxic to humans — strict PPE required. Do not use in windy conditions.', '34891'),

('Spray.Seed 250', 'Paraquat + Diquat', 'Bipyridinium mix', 'PS I electron diverter (D)', 'Soluble Concentrate', 'herbicide', 'weed', 'Syngenta', ARRAY['Fallow','Non-crop','Pasture renovation'], ARRAY['Annual Ryegrass','Wild Radish','Sowthistle','Capeweed','Many annuals'], '1.5-3.5 L/ha', '0 days', '24 hours', 'Faster brownout than paraquat alone. No residual soil activity.', 'HRAC Group D. Resistance documented in annual ryegrass — paraquat resistant biotypes exist.', '42183'),

('Ignite 150 SL', 'Glufosinate-ammonium', 'Glutamine synthetase inhibitor (H)', 'Glutamine synthetase inhibitor (10)', 'Soluble Liquid', 'herbicide', 'weed', 'Bayer', ARRAY['Liberty Link Canola','Non-crop','Fallow'], ARRAY['Annual Ryegrass','Capeweed','Wild Radish','Barnyard Grass','Fat Hen'], '2.0-5.0 L/ha', '0 days', '12 hours', 'Non-selective contact herbicide. Add surfactant. Must apply in warm conditions >15C.', 'HRAC Group H. No resistance documented yet — important resistance management tool vs glyphosate.', '67524'),

('MCPA 750 SL', 'MCPA', 'Phenoxyacetic acid', 'Auxin mimic (O)', 'Soluble Liquid', 'herbicide', 'weed', 'Nufarm', ARRAY['Wheat','Barley','Oats','Pasture','Rice'], ARRAY['Capeweed','Wild Radish','Sowthistle','Dock','Clover','Bindweed'], '0.5-1.5 L/ha', '7 days', '24 hours', 'Alternative to 2,4-D. Less volatile — better for use near sensitive crops.', 'HRAC Group O. Low resistance risk.', '18421'),

('Dicamba 700 WG', 'Dicamba', 'Benzoic acid', 'Auxin mimic (O)', 'Wettable Granule', 'herbicide', 'weed', 'BASF', ARRAY['Wheat','Barley','Oats','Pasture'], ARRAY['Bindweed','Wild Radish','Capeweed','Cleavers','Dock'], '0.2-0.5 kg/ha', '14 days', '24 hours', 'Effective on difficult broadleaf weeds. High vapour drift risk — do not use near sensitive crops.', 'HRAC Group O. Low resistance risk.', '24631'),

('Logran 750 WG', 'Triasulfuron', 'Sulfonylurea', 'ALS inhibitor (B)', 'Wettable Granule', 'herbicide', 'weed', 'Syngenta', ARRAY['Wheat','Barley','Triticale'], ARRAY['Capeweed','Wild Radish','Sowthistle','Prickly Lettuce','Annual Ryegrass'], '0.02-0.03 kg/ha', '0 days', '12 hours', 'Very low use rate. Apply in 2-6 leaf stage of cereal.', 'HRAC Group B. High resistance risk — widespread in Australia.', '47821'),

('Glean 750 DF', 'Chlorsulfuron', 'Sulfonylurea', 'ALS inhibitor (B)', 'Dry Flowable', 'herbicide', 'weed', 'DuPont', ARRAY['Wheat','Barley','Oats','Triticale'], ARRAY['Wild Radish','Capeweed','Sowthistle','Prickly Lettuce','Ryegrass'], '0.015 kg/ha', '0 days', '12 hours', 'Very low use rate. Long soil persistence — follow crop rotation restrictions carefully.', 'HRAC Group B. High resistance risk.', '25841'),

('Ally Max', 'Metsulfuron-methyl', 'Sulfonylurea', 'ALS inhibitor (B)', 'Dry Flowable', 'herbicide', 'weed', 'DuPont', ARRAY['Wheat','Barley','Triticale','Oats','Pasture'], ARRAY['Wild Radish','Capeweed','Cleavers','Bedstraw','Wild Turnip'], '0.004-0.006 kg/ha', '0 days', '12 hours', 'Extremely low use rate. Some soil residual — check plant-back periods.', 'HRAC Group B. High resistance risk. Check for resistance before use.', '45821'),

('Spinnaker 500', 'Imazethapyr', 'Imidazolinone', 'ALS inhibitor (B)', 'Soluble Concentrate', 'herbicide', 'weed', 'BASF', ARRAY['Soybean','Faba Bean','Lupin','Lentil'], ARRAY['Annual Ryegrass','Brome Grass','Wild Oat','Barnyard Grass','Fat Hen','Sowthistle'], '0.7-1.0 L/ha', '0 days', '12 hours', 'Pre or post-emergent in pulse crops. Do not follow with cereal crops without 12-month interval.', 'HRAC Group B. Cross-resistance with other imidazolinones and some sulfonylureas.', '55241'),

('Raptor', 'Imazamox', 'Imidazolinone', 'ALS inhibitor (B)', 'Soluble Concentrate', 'herbicide', 'weed', 'BASF', ARRAY['Soybean','Bean','Lupin'], ARRAY['Annual Ryegrass','Wild Oat','Barnyard Grass','Brome Grass','Smartweed'], '0.5-0.75 L/ha', '0 days', '12 hours', 'Post-emergent in legume crops. Add adjuvant.', 'HRAC Group B. Cross-resistance with other ALS inhibitors common.', '62841'),

('Weedmaster Duo', 'Dicamba + 2,4-D', 'Benzoic + Phenoxyacetic', 'Auxin mimic (O)', 'Soluble Concentrate', 'herbicide', 'weed', 'Nufarm', ARRAY['Wheat','Barley','Pasture','Fallow'], ARRAY['Wild Radish','Capeweed','Cleavers','Dock','Bindweed','Wild Turnip'], '1.5-2.5 L/ha', '7 days', '24 hours', 'Excellent broadleaf broadspectrum control. Dicamba enhances activity of 2,4-D.', 'HRAC Group O. Low resistance risk in most species.', '60234'),

('Pixxaro EC', 'Arylex + Florasulam', 'Pyridine carboxylic acid + Triazolopyrimidine', 'Auxin + ALS inhibitor (O + B)', 'Emulsifiable Concentrate', 'herbicide', 'weed', 'Dow AgroSciences', ARRAY['Wheat','Barley','Triticale','Oats'], ARRAY['Wild Radish','Wild Turnip','Capeweed','Bedstraw','Cleavers','Prickly Lettuce'], '0.25-0.35 L/ha', '60 days', '12 hours', 'Dual mode broadleaf herbicide. Excellent activity on Group B-resistant radish.', 'HRAC O+B. Arylex component provides Group O activity for B-resistant weeds.', '82341'),

('Talinor 400 SC', 'Bicyclopyrone + Bromoxynil', 'HPPD + Nitrile', 'HPPD inhibitor + PS II (F2 + C3)', 'Suspension Concentrate', 'herbicide', 'weed', 'Syngenta', ARRAY['Wheat','Barley','Triticale'], ARRAY['Wild Radish','Capeweed','Annual Ryegrass','Wild Turnip','Cleavers'], '0.5-0.7 L/ha', '60 days', '12 hours', 'New HPPD chemistry for cereals — particularly effective on ALS-resistant radish.', 'HRAC F2+C3. New mode for cereals — important resistance management tool.', '83142'),

('Sakura Duo', 'Pyroxasulfone + Prosulfocarb', 'Isoxazoline + Thiocarbamate', 'VLCFA inhibitor (K3 + N)', 'Suspension Concentrate', 'herbicide', 'weed', 'Kumiai + Syngenta', ARRAY['Wheat','Barley'], ARRAY['Annual Ryegrass','Brome Grass','Wild Oat','Canary Grass'], '2.5-3.5 L/ha', '0 days (pre-emergent)', '24 hours', 'Dual pre-emergent grass herbicide. Strong ryegrass control.', 'HRAC K3+N. Excellent resistance management combination.', '84231'),

('Avadex Xtra', 'Tri-allate', 'Thiocarbamate', 'VLCFA inhibitor (N)', 'Granule', 'herbicide', 'weed', 'Gowan', ARRAY['Wheat','Barley','Chickpea','Lentil'], ARRAY['Wild Oat','Canary Grass'], '5.0-7.5 kg/ha', '0 days', '24 hours', 'Granular soil-incorporated herbicide. Effective against wild oat even at depth.', 'HRAC Group N. Resistance documented in wild oat. Rotate with different modes of action.', '32841'),

('Dual Gold 960 EC', 'S-Metolachlor', 'Chloroacetamide', 'VLCFA inhibitor (K3)', 'Emulsifiable Concentrate', 'herbicide', 'weed', 'Syngenta', ARRAY['Maize','Sorghum','Sunflower','Cotton','Soybean','Peanut'], ARRAY['Barnyard Grass','Crabgrass','Pigweed','Fat Hen','Smartweed'], '1.5-2.5 L/ha', '0 days (pre-emergent)', '12 hours', 'Pre-emergent soil herbicide. Requires moist conditions for activation.', 'HRAC Group K3. Low resistance risk.', '62341'),

('Stomp Aqua', 'Pendimethalin', 'Dinitroaniline', 'Tubulin polymerisation inhibitor (K1)', 'Capsule Suspension', 'herbicide', 'weed', 'BASF', ARRAY['Onion','Garlic','Tomato','Capsicum','Cotton','Maize'], ARRAY['Annual Ryegrass','Barnyard Grass','Crabgrass','Pigweed','Purslane'], '3.0-5.0 L/ha', '0 days (pre-emergent)', '24 hours', 'Pre-emergent surface application. Rainfastness excellent. No soil incorporation needed.', 'HRAC Group K1. Low resistance risk.', '70842'),

('Terbyne XT', 'Terbuthylazine', 'Triazine', 'PS II inhibitor (C1)', 'Water Dispersible Granule', 'herbicide', 'weed', 'Adama', ARRAY['Sorghum','Maize','Sugarcane'], ARRAY['Barnyard Grass','Crabgrass','Pigweed','Fat Hen','Amaranth'], '1.5-2.5 kg/ha', '0 days (pre-emergent)', '24 hours', 'Residual triazine herbicide. Reduced resistance issues compared to atrazine.', 'HRAC Group C1. Resistance documented in some biotypes.', '58341'),

('Diuron 900 WG', 'Diuron', 'Phenylurea', 'PS II inhibitor (C2)', 'Wettable Granule', 'herbicide', 'weed', 'Nufarm', ARRAY['Sugarcane','Cotton','Asparagus','Non-crop'], ARRAY['Annual Ryegrass','Barnyard Grass','Pigweed','Fat Hen'], '1.5-3.0 kg/ha', '0 days (pre-emergent)', '24 hours', 'Residual pre-emergent. Long soil half-life — beware carryover to sensitive crops.', 'HRAC Group C2. Some resistance documented.', '18623'),

('Bromicide MA', 'Bromoxynil', 'Benzonitrile', 'PS II inhibitor (C3)', 'Emulsifiable Concentrate', 'herbicide', 'weed', 'Nufarm', ARRAY['Wheat','Barley','Maize','Sorghum'], ARRAY['Wild Radish','Capeweed','Annual Ryegrass','Bedstraw'], '0.6-1.0 L/ha', '7 days', '24 hours', 'Post-emergent broadleaf herbicide. Apply to young weeds. Volatile — avoid tank mixing with phenoxy herbicides.', 'HRAC Group C3. Low resistance risk.', '21842'),

('Pix Plus', 'Mepiquat + Cyclanilide', 'Growth regulator mix', 'Auxin transport inhibitor (plant growth regulator)', 'Soluble Concentrate', 'herbicide', 'weed', 'Bayer', ARRAY['Cotton'], ARRAY['Excessive vegetative growth'], '0.5-1.0 L/ha', '0 days', '12 hours', 'Plant growth regulator for cotton canopy management. Not a traditional herbicide.', 'No standard resistance HRAC classification. Low risk.', '47621'),

('Valor 500 SC', 'Flumioxazin', 'N-phenylphthalimide', 'PPO inhibitor (E)', 'Suspension Concentrate', 'herbicide', 'weed', 'Valent', ARRAY['Grape','Apple','Non-crop','Asparagus'], ARRAY['Annual Ryegrass','Barnyard Grass','Pigweed','Capeweed','Sowthistle'], '0.5-0.75 L/ha', '0 days (pre-emergent)', '12 hours', 'Pre-emergent with some burndown activity. Excellent under-vine weed control.', 'HRAC Group E. Moderate resistance risk.', '71234'),

('Amitrole 250 SC', 'Amitrole', 'Triazole', 'PS II + Carotenoid inhibitor (F3)', 'Suspension Concentrate', 'herbicide', 'weed', 'Nufarm', ARRAY['Non-crop','Grape','Orchard (under-tree)'], ARRAY['Annual Ryegrass','Capeweed','Sowthistle','Barnyard Grass'], '4.0-8.0 L/ha', '0 days', '24 hours', 'Non-selective contact and residual herbicide. Do not apply to weeds under moisture stress.', 'HRAC F3. Low resistance risk.', '13241'),

('Reflex 240 SC', 'Fomesafen', 'Diphenyl ether', 'PPO inhibitor (E)', 'Suspension Concentrate', 'herbicide', 'weed', 'Syngenta', ARRAY['Soybean','Cotton'], ARRAY['Pigweed','Barnyard Grass','Crabgrass','Fat Hen','Lambsquarters'], '0.8-1.25 L/ha', '0 days', '24 hours', 'Post-emergent for soybean. Broadleaf and some grass weeds.', 'HRAC Group E. Moderate resistance risk — rotate with non-PPO herbicides.', '54231'),

('Lexone 750 WG', 'Metribuzin', 'Triazinone', 'PS II inhibitor (C1)', 'Wettable Granule', 'herbicide', 'weed', 'DuPont', ARRAY['Tomato','Asparagus','Potato','Wheat'], ARRAY['Annual Ryegrass','Capeweed','Sowthistle','Prickly Lettuce'], '0.35-1.0 kg/ha', '0 days', '12 hours', 'Soil residual. Do not use on light sandy soils. Sensitive to temperature inversions.', 'HRAC Group C1. Moderate resistance risk in ryegrass.', '41235'),

('Simazine 900 WG', 'Simazine', 'Triazine', 'PS II inhibitor (C1)', 'Wettable Granule', 'herbicide', 'weed', 'Nufarm', ARRAY['Grape','Orchard','Non-crop'], ARRAY['Annual Ryegrass','Barnyard Grass','Fat Hen','Pigweed','Capeweed'], '1.5-3.0 kg/ha', '0 days (pre-emergent)', '24 hours', 'Pre-emergent. Do not apply to sandy soils. Good residual under vine.', 'HRAC Group C1. Resistance widespread in annual ryegrass.', '13942'),

('Gesaprime 900 WG', 'Atrazine', 'Triazine', 'PS II inhibitor (C1)', 'Wettable Granule', 'herbicide', 'weed', 'Syngenta', ARRAY['Maize','Sorghum','Sugarcane'], ARRAY['Barnyard Grass','Fat Hen','Crabgrass','Annual Ryegrass'], '1.5-2.5 kg/ha', '0 days (pre-emergent)', '24 hours', 'Generic atrazine brand. Apply pre-emergent.', 'HRAC Group C1. Widespread resistance.', '24822'),

('Aramo 50 EC', 'Tepraloxydim', 'Cyclohexanedione (CHD/DIM)', 'ACCase inhibitor (A)', 'Emulsifiable Concentrate', 'herbicide', 'weed', 'BASF', ARRAY['Cotton','Soybean','Sunflower','Peanut','Canola'], ARRAY['Annual Ryegrass','Brome Grass','Wild Oat','Barnyard Grass','Barley Grass'], '1.0-3.0 L/ha', '0 days', '12 hours', 'Post-emergent grass control in broadleaf crops. Add adjuvant. Selective for grasses.', 'HRAC Group A. High resistance risk — widespread FOP/DIM resistance in ryegrass.', '64521'),

('Select 240 EC', 'Clethodim', 'Cyclohexanedione (CHD)', 'ACCase inhibitor (A)', 'Emulsifiable Concentrate', 'herbicide', 'weed', 'Arysta', ARRAY['Soybean','Cotton','Canola','Vegetable'], ARRAY['Annual Ryegrass','Wild Oat','Brome Grass','Barley Grass'], '0.25-0.75 L/ha', '0 days', '12 hours', 'Post-emergent grass killer in broadleaf crops. Add crop oil. Good on ryegrass. Limited efficacy on FOP-resistant biotypes.', 'HRAC Group A. Resistance documented in annual ryegrass but less than to FOPs.', '47241'),

('Fusilade Forte', 'Fluazifop-P-butyl', 'AOPP', 'ACCase inhibitor (A)', 'Emulsifiable Concentrate', 'herbicide', 'weed', 'Syngenta', ARRAY['Grape','Orchard','Vegetable','Cotton','Soybean'], ARRAY['Annual Ryegrass','Wild Oat','Barley Grass','Barnyard Grass','Brome Grass'], '1.5-2.0 L/ha', '14 days', '12 hours', 'Post-emergent graminicide for use around broadleaf crops and perennials.', 'HRAC Group A. Resistance widespread in annual ryegrass — use with non-FOP alternation.', '27431'),

('EPTC 720 EC', 'EPTC', 'Thiocarbamate', 'VLCFA inhibitor (N)', 'Emulsifiable Concentrate', 'herbicide', 'weed', 'Nufarm', ARRAY['Maize','Sunflower','Potato','Bean'], ARRAY['Barnyard Grass','Nutsedge','Crabgrass','Pigweed','Wireweed'], '4.0-8.0 L/ha', '0 days', '24 hours', 'Soil incorporated thiocarbamate. Apply and incorporate immediately.', 'HRAC Group N. Moderate resistance risk.', '26841'),

('Gesagard 500 FW', 'Prometryn', 'Triazine', 'PS II inhibitor (C1)', 'Flowable Wettable', 'herbicide', 'weed', 'Syngenta', ARRAY['Cotton','Celery','Parsley','Carrot'], ARRAY['Barnyard Grass','Fat Hen','Crabgrass','Pigweed'], '2.5-5.0 L/ha', '0 days (pre-emergent)', '24 hours', 'Pre-emergent in cotton and vegetables.', 'HRAC Group C1. Resistance documented.', '15432'),

('Nugrass 200 EC', 'Imazapic', 'Imidazolinone', 'ALS inhibitor (B)', 'Emulsifiable Concentrate', 'herbicide', 'weed', 'BASF', ARRAY['Peanut','Sugarcane','Non-crop'], ARRAY['Barnyard Grass','Crabgrass','Purple Nutsedge','Pigweed'], '0.5-0.75 L/ha', '0 days', '12 hours', 'Selective in peanuts and sugarcane. Good nutsedge activity.', 'HRAC Group B. Moderate resistance risk.', '67341'),

('Halosulfuron 750 WG', 'Halosulfuron-methyl', 'Sulfonylurea', 'ALS inhibitor (B)', 'Wettable Granule', 'herbicide', 'weed', 'Nissan', ARRAY['Maize','Sorghum','Sugarcane','Turf'], ARRAY['Purple Nutsedge','Yellow Nutsedge','Ryegrass'], '0.065 kg/ha', '0 days', '12 hours', 'Best sulfonylurea for nutsedge control. Selective in grasses when applied at correct timing.', 'HRAC Group B. High resistance risk — do not use consecutively.', '73124'),

('Spinnaker 700 WG', 'Imazethapyr', 'Imidazolinone', 'ALS inhibitor (B)', 'Wettable Granule', 'herbicide', 'weed', 'BASF', ARRAY['Soybean','Chickpea','Lentil','Faba Bean'], ARRAY['Annual Ryegrass','Wild Oat','Barnyard Grass','Brome Grass','Fat Hen'], '0.075-0.12 kg/ha', '0 days', '12 hours', 'WG formulation of imazethapyr. Pre or post-emergent in legumes.', 'HRAC Group B. Rotation restrictions — do not follow with sensitive crops.', '55242'),

('Banvel 200 SL', 'Dicamba', 'Benzoic acid', 'Auxin mimic (O)', 'Soluble Liquid', 'herbicide', 'weed', 'BASF', ARRAY['Wheat','Barley','Oats','Pasture'], ARRAY['Wild Radish','Capeweed','Bindweed','Dock','Cleavers'], '0.25-0.5 L/ha', '14 days', '24 hours', 'Highly volatile — do not use near sensitive crops or in warm conditions.', 'HRAC Group O. Low resistance risk.', '24632'),

('Broadside', 'Bromoxynil + MCPA', 'Benzonitrile + Phenoxyacetic', 'PS II + Auxin mimic (C3 + O)', 'Emulsifiable Concentrate', 'herbicide', 'weed', 'Dow AgroSciences', ARRAY['Wheat','Barley','Oats','Sorghum','Maize'], ARRAY['Wild Radish','Wild Turnip','Capeweed','Sowthistle','Annual Ryegrass'], '1.0-1.5 L/ha', '7 days', '24 hours', 'Dual mode broadleaf control in cereals. Apply early post-emergent.', 'HRAC C3+O. Low resistance risk.', '52341'),

('Xtreme Herbicide', 'Glyphosate + Oxyfluorfen', 'Glycine + Diphenyl ether', 'EPSPS + PPO inhibitor (9 + E)', 'Suspension Concentrate', 'herbicide', 'weed', 'Nufarm', ARRAY['Non-crop','Orchard','Vineyard'], ARRAY['Annual Ryegrass','Capeweed','Barnyard Grass','Fleabane'], '3.0-5.0 L/ha', '0 days', '24 hours', 'Burndown plus residual. Good for glyphosate-resistant fleabane when combined with residual.', 'HRAC 9+E. The glyphosate component may fail on resistant biotypes.', '75341'),

('Hussar OD', 'Iodosulfuron-methyl + Mefenpyr-diethyl', 'Sulfonylurea + Safener', 'ALS inhibitor + Safener (B)', 'Oil Dispersion', 'herbicide', 'weed', 'Bayer', ARRAY['Wheat','Barley'], ARRAY['Annual Ryegrass','Wild Oat','Brome Grass','Canary Grass'], '0.1-0.15 L/ha', '60 days', '12 hours', 'Sulfonylurea with safener for cereal safety. Mefenpyr enhances crop tolerance.', 'HRAC Group B. High resistance risk in annual ryegrass.', '75342'),

('Montor WG', 'Triflusulfuron-methyl', 'Sulfonylurea', 'ALS inhibitor (B)', 'Wettable Granule', 'herbicide', 'weed', 'DuPont', ARRAY['Sugarcane','Beet'], ARRAY['Fat Hen','Pigweed','Bindweed','Sowthistle'], '0.03 kg/ha', '0 days', '12 hours', 'Highly selective in sugarcane. Very low use rate.', 'HRAC Group B. Resistance risk.', '61234'),

('Terrain 750 WG', 'Imazapyr', 'Imidazolinone', 'ALS inhibitor (B)', 'Wettable Granule', 'herbicide', 'weed', 'BASF', ARRAY['Non-crop','Forestry','Rights-of-way'], ARRAY['Serrated Tussock','Paspalum','Annual Ryegrass','Blackberry','Woody Weeds'], '0.2-0.4 kg/ha', '0 days', '12 hours', 'Extremely long soil residual — up to 3 years. Broad-spectrum non-selective.', 'HRAC Group B. Long soil activity reduces resistance risk.', '54231'),

('Zinc Phosphide 8 TB', 'Zinc Phosphide', 'Inorganic toxicant', 'Mitochondrial electron transport (phosphine gas)', 'Tablet', 'insecticide', 'pest', 'Nufarm', ARRAY['Stored Grain','Structures'], ARRAY['Mice','Rats','Vertebrate pests'], '3-6 tablets/tonne', '0 days', '24 hours', 'Restricted use fumigant. Requires operator certification. Generate toxic phosphine gas.', 'N/A — fumigant mode.', '36841'),

('Dichlorvos 500 EC', 'Dichlorvos (DDVP)', 'Organophosphate', 'Acetylcholinesterase inhibitor (1B)', 'Emulsifiable Concentrate', 'insecticide', 'pest', 'Various', ARRAY['Stored Products','Glasshouse'], ARRAY['Aphid','Thrips','Spider Mite','Whitefly','Mites'], '0.5-1.0 L/ha', '3 days', '48 hours', 'Highly volatile OP — vapour activity. Very high mammalian toxicity. Restricted use.', 'IRAC Group 1B. Resistance documented.', '14231');
