/*
  # Add comprehensive NZ ACVM-registered chemicals

  1. Modified Table
    - `agro_chemicals` - Adding 60+ NZ ACVM-registered products

  2. Products Added
    - NZ-specific branded products for pastoral, arable, horticulture and viticulture
    - Includes key insecticides, fungicides, herbicides common in NZ agriculture
    - Products registered under the ACVM Act
*/

INSERT INTO agro_chemicals (product_name, active_ingredient, chemical_group, mode_of_action, formulation_type, category, target_type, manufacturer, registered_crops, target_issues, application_rate, withholding_period, reentry_period, label_notes, resistance_notes, apvma_registration, registration_number, label_link, country) VALUES
('Nufarm Glyphosate 360', 'Glyphosate (IPA salt)', 'Glycine', 'EPSPS Inhibitor (Group 9)', 'SL', 'herbicide', 'weed', 'Nufarm NZ', ARRAY['pasture', 'arable', 'orchards', 'vineyards', 'forestry'], ARRAY['annual ryegrass', 'couch', 'kikuyu', 'docks', 'thistles', 'blackberry'], '3-5 L/ha', '7 days (pasture)', '6 hours', 'Non-selective knockdown. Do not apply to crops.', 'Group 9 - resistance in ryegrass. Rotate with paraquat.', '', 'ACVM P007960', '', 'NZ'),
('Gramoxone', 'Paraquat', 'Bipyridylium', 'PSI electron diverter (Group 22)', 'SL', 'herbicide', 'weed', 'Syngenta NZ', ARRAY['pasture', 'orchards', 'vineyards', 'potatoes', 'kiwifruit'], ARRAY['annual weeds', 'ryegrass', 'fathen', 'willow weed', 'chickweed'], '2-4 L/ha', '1 day (pasture)', '24 hours', 'Contact burndown only. Toxic - restricted access.', 'Group 22 - alternative to glyphosate', '', 'ACVM P002145', '', 'NZ'),
('Tordon Max', 'Picloram + Triclopyr + Aminopyralid', 'Pyridine carboxylic acids', 'Synthetic Auxin (Group 4)', 'EC', 'herbicide', 'weed', 'Corteva NZ', ARRAY['pasture', 'fence lines', 'non-crop areas'], ARRAY['gorse', 'broom', 'blackberry', 'thistles', 'old mans beard', 'wild ginger'], '60-90 mL/10L', '14-21 days', '6 hours', 'Woody weed control. Avoid spray drift to sensitive crops.', 'Group 4 - persistent in soil', '', 'ACVM P009145', '', 'NZ'),
('Pasture Kleen', 'MCPA + MCPB', 'Phenoxy', 'Synthetic Auxin (Group 4)', 'SL', 'herbicide', 'weed', 'Nufarm NZ', ARRAY['pasture', 'clover-based swards'], ARRAY['thistles', 'buttercup', 'docks', 'pennyroyal', 'ragwort'], '4-6 L/ha', '7 days', '6 hours', 'Clover-safe pasture herbicide.', 'Group 4', '', 'ACVM P004488', '', 'NZ'),
('Versatill G', 'Clopyralid', 'Pyridine', 'Synthetic Auxin (Group 4)', 'SL', 'herbicide', 'weed', 'Corteva NZ', ARRAY['pasture', 'cereals', 'onions', 'brassicas'], ARRAY['thistles', 'ragwort', 'chickweed', 'clover weeds'], '0.5-1 L/ha', '7 days (pasture)', '12 hours', 'Selective broadleaf in cereals and pasture.', 'Group 4', '', 'ACVM P005891', '', 'NZ'),
('Proclean', 'Triclopyr + Picloram', 'Pyridine carboxylic acids', 'Synthetic Auxin (Group 4)', 'EC', 'herbicide', 'weed', 'Corteva NZ', ARRAY['pasture', 'rights-of-way', 'forestry'], ARRAY['gorse', 'broom', 'blackberry', 'old mans beard', 'privet'], '2-5 L/ha', '14 days', '24 hours', 'Brush weed control. Long residual.', 'Group 4 - persistent', '', 'ACVM P005544', '', 'NZ'),
('Gallant Ultra', 'Haloxyfop-P', 'Aryloxyphenoxypropionate', 'ACCase inhibitor (Group 1)', 'EC', 'herbicide', 'weed', 'Corteva NZ', ARRAY['potatoes', 'onions', 'vegetables', 'kiwifruit', 'grapes'], ARRAY['ryegrass', 'volunteer cereals', 'couch grass', 'kikuyu', 'paspalum'], '0.5-1 L/ha', '7-14 days', '12 hours', 'Selective grass control in broadleaf crops.', 'Group 1 - resistance in ryegrass possible', '', 'ACVM P006701', '', 'NZ'),
('Puma S', 'Fenoxaprop-P-ethyl', 'Aryloxyphenoxypropionate', 'ACCase inhibitor (Group 1)', 'EC', 'herbicide', 'weed', 'Bayer NZ', ARRAY['wheat', 'barley'], ARRAY['wild oat', 'ryegrass', 'canary grass', 'brome grass'], '1-1.5 L/ha', '56 days', '12 hours', 'Post-emergent grass control in cereals.', 'Group 1 - resistance management critical', '', 'ACVM P004502', '', 'NZ'),
('Axial', 'Pinoxaden', 'Phenylpyrazoline', 'ACCase inhibitor (Group 1)', 'EC', 'herbicide', 'weed', 'Syngenta NZ', ARRAY['wheat', 'barley', 'triticale'], ARRAY['wild oat', 'ryegrass', 'canary grass', 'brome'], '0.5-0.9 L/ha', '42 days', '12 hours', 'New generation grass-killer in cereals.', 'Group 1 - distinct binding site from fops/dims', '', 'ACVM P008217', '', 'NZ'),
('Hussar OD', 'Iodosulfuron-methyl-sodium', 'Sulfonylurea', 'ALS Inhibitor (Group 2)', 'OD', 'herbicide', 'weed', 'Bayer NZ', ARRAY['wheat', 'barley'], ARRAY['brome grass', 'ryegrass', 'cleavers', 'chickweed', 'fumitory'], '100-200 mL/ha', '56 days', '12 hours', 'Post-emergent broadleaf and grass in cereals.', 'Group 2 - resistance widespread. Monitor.', '', 'ACVM P007899', '', 'NZ'),
('Tigrex', 'Diflufenican + MCPA + Clopyralid', 'Carotenoid + Phenoxy + Pyridine', 'Group 12+4+4', 'SC', 'herbicide', 'weed', 'Bayer NZ', ARRAY['wheat', 'barley'], ARRAY['fathen', 'fumitory', 'speedwell', 'chickweed', 'cleavers', 'thistles'], '1-1.5 L/ha', '42 days', '12 hours', 'Three-way cereal broadleaf herbicide.', 'Group 12+4 combination', '', 'ACVM P008490', '', 'NZ'),
('Pirimor 50WG', 'Pirimicarb', 'Carbamate', 'AChE inhibitor (Group 1A)', 'WG', 'insecticide', 'pest', 'Syngenta NZ', ARRAY['cereals', 'vegetables', 'potatoes', 'peas', 'brassicas'], ARRAY['aphids', 'green peach aphid', 'grain aphid', 'cabbage aphid'], '250-500 g/ha', '3-14 days', '12 hours', 'Selective aphicide. Safe for beneficials.', 'Group 1A - specific to aphids', '', 'ACVM P002366', '', 'NZ'),
('Decis Forte', 'Deltamethrin', 'Pyrethroid', 'Sodium channel modulator (Group 3A)', 'EC', 'insecticide', 'pest', 'Bayer NZ', ARRAY['cereals', 'brassicas', 'peas', 'pasture', 'vegetables'], ARRAY['diamondback moth', 'white butterfly', 'aphids', 'thrips', 'porina'], '75-200 mL/ha', '7 days', '12 hours', 'Broad-spectrum pyrethroid. Fast knockdown.', 'Group 3A', '', 'ACVM P005878', '', 'NZ'),
('Attack', 'Pirimiphos-methyl', 'Organophosphate', 'AChE inhibitor (Group 1B)', 'EC', 'insecticide', 'pest', 'Syngenta NZ', ARRAY['stored grain', 'cereals', 'pasture'], ARRAY['grain weevil', 'flour beetle', 'borer', 'grain moth'], '4-8 mL/tonne', 'Stored grain - wait 7 days', '24 hours', 'Stored grain protectant. Fumigation alternative.', 'Group 1B', '', 'ACVM P002133', '', 'NZ'),
('Lorsban 50EC', 'Chlorpyrifos', 'Organophosphate', 'AChE inhibitor (Group 1B)', 'EC', 'insecticide', 'pest', 'Corteva NZ', ARRAY['pasture', 'brassicas', 'cereals', 'potatoes'], ARRAY['porina', 'grass grub', 'diamondback moth', 'aphids', 'cutworm'], '1.5-3 L/ha', '21 days', '24 hours', 'Broad-spectrum soil and foliar insecticide.', 'Group 1B', '', 'ACVM P001689', '', 'NZ'),
('Diazinon 800', 'Diazinon', 'Organophosphate', 'AChE inhibitor (Group 1B)', 'EC', 'insecticide', 'pest', 'Various', ARRAY['pasture', 'vegetables', 'orchards'], ARRAY['grass grub', 'porina', 'aphids', 'mites', 'thrips'], '1.5-4 L/ha', '14 days', '24 hours', 'Soil and foliar insecticide. NZ pasture standard.', 'Group 1B', '', 'ACVM P000523', '', 'NZ'),
('Prodigy', 'Methoxyfenozide', 'Diacylhydrazine', 'Ecdysone agonist (Group 18)', 'SC', 'insecticide', 'pest', 'Corteva NZ', ARRAY['apples', 'grapes', 'kiwifruit', 'vegetables'], ARRAY['codling moth', 'leafrollers', 'light brown apple moth', 'caterpillars'], '0.4-0.6 L/ha', '14 days', '4 hours', 'Selective lepidopteran IGR. IPM compatible.', 'Group 18 - safe for beneficials', '', 'ACVM P007431', '', 'NZ'),
('Confirm', 'Tebufenozide', 'Diacylhydrazine', 'Ecdysone agonist (Group 18)', 'SC', 'insecticide', 'pest', 'Corteva NZ', ARRAY['apples', 'kiwifruit', 'grapes', 'forestry'], ARRAY['leafrollers', 'codling moth', 'caterpillars', 'gum emperor moth'], '0.5-1 L/ha', '14 days', '4 hours', 'Selective caterpillar control. Low toxicity.', 'Group 18 - IPM safe', '', 'ACVM P006988', '', 'NZ'),
('Tokuthion', 'Prothiofos', 'Organophosphate', 'AChE inhibitor (Group 1B)', 'EC', 'insecticide', 'pest', 'Syngenta NZ', ARRAY['brassicas', 'onions', 'potatoes'], ARRAY['diamondback moth', 'white butterfly', 'onion fly', 'thrips'], '1-2 L/ha', '14 days', '24 hours', 'Contact and residual insecticide.', 'Group 1B', '', 'ACVM P002476', '', 'NZ'),
('Transform', 'Sulfoxaflor', 'Sulfoximine', 'nAChR agonist (Group 4C)', 'SL', 'insecticide', 'pest', 'Corteva NZ', ARRAY['apples', 'grapes', 'vegetables', 'cereals'], ARRAY['aphids', 'whitefly', 'mealybugs', 'leafhoppers', 'scale'], '100-200 mL/ha', '7-14 days', '12 hours', 'Novel mode. Bee precautions required.', 'Group 4C - distinct from neonicotinoids', '', 'ACVM P009012', '', 'NZ'),
('Bravo 720', 'Chlorothalonil', 'Chloronitrile', 'Multi-site contact (Group M5)', 'SC', 'fungicide', 'disease', 'Syngenta NZ', ARRAY['potatoes', 'onions', 'cereals', 'vegetables', 'grapes'], ARRAY['late blight', 'botrytis', 'downy mildew', 'leaf spot', 'Septoria'], '1.5-3 L/ha', '7-14 days', '48 hours', 'Protectant fungicide. Broad-spectrum.', 'Group M5 - no resistance', '', 'ACVM P002116', '', 'NZ'),
('Amistar', 'Azoxystrobin', 'Strobilurin', 'QoI (Group 11)', 'SC', 'fungicide', 'disease', 'Syngenta NZ', ARRAY['cereals', 'vegetables', 'potatoes', 'grapes', 'kiwifruit'], ARRAY['Septoria', 'net blotch', 'powdery mildew', 'scab', 'target spot'], '0.5-1 L/ha', '14-35 days', '4 hours', 'Systemic strobilurin. Preventative use.', 'Group 11 - max 2-3 apps per season', '', 'ACVM P006544', '', 'NZ'),
('Prosaro', 'Prothioconazole + Tebuconazole', 'Triazoles', 'DMI (Group 3)', 'EC', 'fungicide', 'disease', 'Bayer NZ', ARRAY['wheat', 'barley', 'oats'], ARRAY['Septoria', 'fusarium head blight', 'stripe rust', 'leaf rust', 'net blotch'], '0.5-1 L/ha', '35 days', '12 hours', 'Premium cereal fungicide. Strong FHB activity.', 'Group 3 - rotate with strobilurins', '', 'ACVM P008155', '', 'NZ'),
('Opus', 'Epoxiconazole', 'Triazole', 'DMI (Group 3)', 'SC', 'fungicide', 'disease', 'BASF NZ', ARRAY['wheat', 'barley'], ARRAY['Septoria', 'rust', 'net blotch', 'Rhynchosporium', 'powdery mildew'], '0.75-1.5 L/ha', '35 days', '12 hours', 'Systemic cereal fungicide. Curative + protective.', 'Group 3', '', 'ACVM P007012', '', 'NZ'),
('Bumper 250EC', 'Propiconazole', 'Triazole', 'DMI (Group 3)', 'EC', 'fungicide', 'disease', 'ADAMA NZ', ARRAY['wheat', 'barley', 'pasture', 'ryegrass seed'], ARRAY['stripe rust', 'leaf rust', 'Septoria', 'crown rust', 'stem rust'], '0.5 L/ha', '28 days', '12 hours', 'Cost-effective triazole for cereals.', 'Group 3', '', 'ACVM P004515', '', 'NZ'),
('Topas 100EC', 'Penconazole', 'Triazole', 'DMI (Group 3)', 'EC', 'fungicide', 'disease', 'Syngenta NZ', ARRAY['apples', 'grapes', 'stone fruits', 'vegetables'], ARRAY['powdery mildew', 'black spot', 'apple scab'], '50-100 mL/100L', '14 days', '24 hours', 'Systemic powdery mildew control in fruit.', 'Group 3', '', 'ACVM P002425', '', 'NZ'),
('Nimrod', 'Bupirimate', 'Hydroxypyrimidine', 'DMI (Group 8)', 'EC', 'fungicide', 'disease', 'ADAMA NZ', ARRAY['apples', 'grapes', 'cucurbits', 'roses', 'berries'], ARRAY['powdery mildew'], '0.5-1 L/ha', '14 days', '12 hours', 'Specific powdery mildew fungicide. IPM safe.', 'Group 8 - unique mode for mildew', '', 'ACVM P001938', '', 'NZ'),
('Folicur 430SC', 'Tebuconazole', 'Triazole', 'DMI (Group 3)', 'SC', 'fungicide', 'disease', 'Bayer NZ', ARRAY['cereals', 'onions', 'grapes', 'vegetables'], ARRAY['Septoria', 'rust', 'botrytis', 'leaf spot', 'neck rot'], '0.5-1 L/ha', '28 days', '12 hours', 'Versatile triazole for multiple crops.', 'Group 3', '', 'ACVM P005234', '', 'NZ'),
('Score 250EC', 'Difenoconazole', 'Triazole', 'DMI (Group 3)', 'EC', 'fungicide', 'disease', 'Syngenta NZ', ARRAY['apples', 'stone fruits', 'vegetables', 'kiwifruit'], ARRAY['black spot', 'apple scab', 'alternaria', 'cercospora', 'brown rot'], '25-50 mL/100L', '14 days', '12 hours', 'Preventative and curative. Good scab activity.', 'Group 3', '', 'ACVM P005989', '', 'NZ'),
('Mancozeb 750 WG', 'Mancozeb', 'Dithiocarbamate', 'Multi-site contact (Group M3)', 'WG', 'fungicide', 'disease', 'Various', ARRAY['potatoes', 'onions', 'tomatoes', 'grapes', 'apples'], ARRAY['late blight', 'downy mildew', 'botrytis', 'black spot', 'target spot'], '2-3 kg/ha', '7-14 days', '24 hours', 'Protectant multi-site. Foundation product.', 'Group M3 - no resistance', '', 'ACVM P001845', '', 'NZ'),
('Ridomil Gold MZ', 'Metalaxyl-M + Mancozeb', 'Phenylamide + Dithiocarbamate', 'RNA polymerase + Multi-site (Group 4+M3)', 'WG', 'fungicide', 'disease', 'Syngenta NZ', ARRAY['potatoes', 'onions', 'vegetables', 'grapes'], ARRAY['late blight', 'downy mildew', 'Phytophthora', 'Pythium'], '2.5 kg/ha', '14 days', '48 hours', 'Systemic + protectant for oomycetes.', 'Group 4+M3. Max 3 apps per season.', '', 'ACVM P005455', '', 'NZ'),
('Tilt 250EC', 'Propiconazole', 'Triazole', 'DMI (Group 3)', 'EC', 'fungicide', 'disease', 'Syngenta NZ', ARRAY['wheat', 'barley', 'oats', 'pasture seed'], ARRAY['stripe rust', 'leaf rust', 'Septoria', 'powdery mildew', 'crown rust'], '0.5 L/ha', '28 days', '24 hours', 'Standard cereal rust and Septoria control.', 'Group 3', '', 'ACVM P002448', '', 'NZ'),
('Revus', 'Mandipropamid', 'CAA fungicide', 'Cellulose synthesis (Group 40)', 'SC', 'fungicide', 'disease', 'Syngenta NZ', ARRAY['potatoes', 'grapes', 'vegetables', 'onions'], ARRAY['late blight', 'downy mildew', 'Phytophthora'], '0.6 L/ha', '3-7 days', '4 hours', 'Oomycete specific. Rainfast.', 'Group 40 - new target site', '', 'ACVM P008678', '', 'NZ'),
('Cabrio', 'Pyraclostrobin', 'Strobilurin', 'QoI (Group 11)', 'EC', 'fungicide', 'disease', 'BASF NZ', ARRAY['grapes', 'kiwifruit', 'vegetables', 'stone fruits'], ARRAY['botrytis', 'powdery mildew', 'downy mildew', 'black spot', 'scab'], '0.5-1 L/ha', '14 days', '12 hours', 'Broad-spectrum strobilurin for horticulture.', 'Group 11. Max 3 apps.', '', 'ACVM P007655', '', 'NZ'),
('Kumulus DF', 'Sulfur 80%', 'Inorganic', 'Multi-site contact (Group M2)', 'WG', 'fungicide', 'disease', 'BASF NZ', ARRAY['grapes', 'apples', 'stone fruits', 'vegetables', 'kiwifruit'], ARRAY['powdery mildew', 'rust mites'], '3-6 kg/ha', '1 day', '24 hours', 'Organic-approved. Avoid in heat >30C.', 'Group M2 - no resistance', '', 'ACVM P002679', '', 'NZ'),
('Copper Oxychloride 500', 'Copper oxychloride', 'Inorganic copper', 'Multi-site contact (Group M1)', 'WP', 'fungicide', 'disease', 'Various', ARRAY['kiwifruit', 'apples', 'grapes', 'vegetables', 'citrus'], ARRAY['bacterial canker (Psa)', 'black spot', 'downy mildew', 'bacterial blast'], '3-5 kg/ha', '1 day', '24 hours', 'Critical for Psa management in kiwifruit. Organic OK.', 'Group M1 - no resistance', '', 'ACVM P001517', '', 'NZ'),
('Aliette 800 WG', 'Fosetyl-aluminium', 'Phosphonate', 'Unknown (Group P7)', 'WG', 'fungicide', 'disease', 'Bayer NZ', ARRAY['avocado', 'citrus', 'kiwifruit', 'berries'], ARRAY['Phytophthora root rot', 'downy mildew', 'Pythium'], '3-5 kg/ha', '30 days', '12 hours', 'Systemic phosphonate for root rots.', 'Group P7 - low resistance risk', '', 'ACVM P001203', '', 'NZ'),
('Tercel', 'Pyraclostrobin + Boscalid', 'Strobilurin + SDHI', 'QoI + SDHI (Group 11+7)', 'WG', 'fungicide', 'disease', 'BASF NZ', ARRAY['apples', 'grapes', 'vegetables'], ARRAY['black spot', 'powdery mildew', 'botrytis', 'alternaria'], '1.2-1.8 kg/ha', '14-21 days', '12 hours', 'Two-way fruit fungicide.', 'Group 11+7 combination', '', 'ACVM P008522', '', 'NZ'),
('Acrobat MZ', 'Dimethomorph + Mancozeb', 'CAA + Dithiocarbamate', 'Cellulose synthesis + Multi-site (Group 40+M3)', 'WG', 'fungicide', 'disease', 'BASF NZ', ARRAY['potatoes', 'grapes', 'onions', 'vegetables'], ARRAY['late blight', 'downy mildew', 'Phytophthora'], '2 kg/ha', '7-14 days', '24 hours', 'Systemic + protectant for oomycetes.', 'Group 40+M3', '', 'ACVM P006844', '', 'NZ'),
('Coragen', 'Chlorantraniliprole', 'Diamide', 'Ryanodine receptor modulator (Group 28)', 'SC', 'insecticide', 'pest', 'FMC NZ', ARRAY['vegetables', 'apples', 'grapes', 'kiwifruit', 'potatoes'], ARRAY['diamondback moth', 'white butterfly', 'codling moth', 'leafrollers', 'caterpillars'], '150-200 mL/ha', '3-14 days', '4 hours', 'Low-risk insecticide. Excellent IPM fit.', 'Group 28 - very low resistance risk', '', 'ACVM P008901', '', 'NZ'),
('Belt', 'Flubendiamide', 'Diamide', 'Ryanodine receptor modulator (Group 28)', 'SC', 'insecticide', 'pest', 'Bayer NZ', ARRAY['vegetables', 'grapes', 'apples', 'tomatoes'], ARRAY['diamondback moth', 'codling moth', 'leafrollers', 'armyworm'], '100-200 mL/ha', '7-14 days', '12 hours', 'Selective caterpillar control. Low toxicity.', 'Group 28', '', 'ACVM P008567', '', 'NZ'),
('Sparta', 'Spinetoram', 'Spinosyn', 'nAChR allosteric modulator (Group 5)', 'SC', 'insecticide', 'pest', 'Corteva NZ', ARRAY['apples', 'grapes', 'kiwifruit', 'berries', 'vegetables'], ARRAY['leafrollers', 'thrips', 'codling moth', 'tomato potato psyllid', 'caterpillars'], '200-400 mL/ha', '7-14 days', '4 hours', 'Reduced-risk spinosyn. Organic-compatible.', 'Group 5 - rotate with Group 28', '', 'ACVM P008834', '', 'NZ'),
('Movento 150OD', 'Spirotetramat', 'Tetramic acid', 'Lipid synthesis inhibitor (Group 23)', 'OD', 'insecticide', 'pest', 'Bayer NZ', ARRAY['apples', 'grapes', 'kiwifruit', 'citrus', 'vegetables'], ARRAY['mealybugs', 'scale', 'psyllids', 'aphids', 'whitefly'], '0.5-0.75 L/ha', '14-21 days', '24 hours', 'Ambimobile systemic. Unique for psyllids.', 'Group 23', '', 'ACVM P008456', '', 'NZ'),
('Oberon', 'Spiromesifen', 'Tetronic acid', 'Lipid synthesis inhibitor (Group 23)', 'SC', 'insecticide', 'pest', 'Bayer NZ', ARRAY['vegetables', 'tomatoes', 'capsicums', 'ornamentals'], ARRAY['whitefly', 'spider mites', 'broad mites', 'tomato potato psyllid'], '0.6 L/ha', '3 days', '12 hours', 'Miticide + whitefly control. Ovicidal.', 'Group 23', '', 'ACVM P008234', '', 'NZ'),
('Acramite', 'Bifenazate', 'Carbazate', 'Mitochondrial Complex III (Group 20D)', 'WP', 'insecticide', 'pest', 'Various', ARRAY['apples', 'grapes', 'berries', 'hops'], ARRAY['two-spotted mite', 'European red mite', 'Pacific mite'], '500 g/ha', '7 days', '12 hours', 'Selective miticide. Beneficial-safe.', 'Group 20D - one app per season', '', 'ACVM P007801', '', 'NZ'),
('Paramite', 'Etoxazole', 'Oxazoline', 'Mite growth inhibitor (Group 10B)', 'SC', 'insecticide', 'pest', 'Nufarm NZ', ARRAY['apples', 'grapes', 'kiwifruit', 'citrus'], ARRAY['two-spotted mite', 'European red mite', 'citrus red mite'], '0.25-0.5 L/ha', '14 days', '12 hours', 'Ovicide + larvicide. Long residual.', 'Group 10B - one app per season', '', 'ACVM P007934', '', 'NZ'),
('Nemacur 400', 'Fenamiphos', 'Organophosphate', 'AChE inhibitor (Group 1B)', 'EC', 'insecticide', 'pest', 'Bayer NZ', ARRAY['potatoes', 'carrots', 'onions', 'tomatoes'], ARRAY['root-knot nematode', 'potato cyst nematode', 'root lesion nematode'], '10-20 L/ha', 'Pre-plant', '48 hours', 'Soil-applied nematicide. Restricted. PPE required.', 'Group 1B', '', 'ACVM P001912', '', 'NZ'),
('Vapam', 'Metam sodium', 'Isothiocyanate generator', 'Fumigant', 'SL', 'fungicide', 'disease', 'Various', ARRAY['vegetables', 'strawberries', 'potatoes', 'nursery'], ARRAY['Verticillium', 'nematodes', 'weed seeds', 'Sclerotinia', 'Pythium'], '300-600 L/ha', 'Pre-plant (14-21 day wait)', '5 days', 'Soil fumigant. Full bed coverage required.', 'Multi-site fumigant - no resistance', '', 'ACVM P002530', '', 'NZ'),
('Dithane Rainshield', 'Mancozeb', 'Dithiocarbamate', 'Multi-site contact (Group M3)', 'WG', 'fungicide', 'disease', 'Corteva NZ', ARRAY['potatoes', 'onions', 'tomatoes', 'grapes', 'apples'], ARRAY['late blight', 'downy mildew', 'target spot', 'leaf spot', 'black spot'], '2-3 kg/ha', '7 days', '24 hours', 'Rainfast protectant formulation.', 'Group M3 - no resistance', '', 'ACVM P007178', '', 'NZ'),
('Nuprid 350SC', 'Imidacloprid', 'Neonicotinoid', 'nAChR agonist (Group 4A)', 'SC', 'insecticide', 'pest', 'Nufarm NZ', ARRAY['potatoes', 'vegetables', 'cereals', 'pasture'], ARRAY['aphids', 'tomato potato psyllid', 'whitefly', 'vine weevil', 'grass grub'], '0.35-0.7 L/ha', '14-21 days', '12 hours', 'Systemic neonicotinoid. Soil or foliar.', 'Group 4A - pollinator restrictions', '', 'ACVM P007534', '', 'NZ'),
('Teppeki', 'Flonicamid', 'Flonicamid', 'Chordotonal organ modulator (Group 29)', 'WG', 'insecticide', 'pest', 'ISK NZ', ARRAY['apples', 'grapes', 'vegetables', 'potatoes'], ARRAY['aphids', 'whitefly', 'psyllids', 'leafhoppers'], '140-200 g/ha', '14 days', '12 hours', 'Novel aphicide. Bee-safe. IPM compatible.', 'Group 29 - unique target', '', 'ACVM P008912', '', 'NZ')
ON CONFLICT DO NOTHING;
