/*
  # Production Weeds Seed - Part 1 (80 weeds)

  Comprehensive Australian agricultural weed database.
*/

INSERT INTO agro_weeds (weed_name, common_name, weed_family, affected_environments, identification_details, growth_habit, control_methods, resistance_notes, resistance_group) VALUES

('Lolium rigidum', 'Annual Ryegrass', 'Poaceae', ARRAY['Wheat','Barley','Canola','Lupin','Pasture','Fallow'], 'Flat leaf blades with glossy undersides. Membranous ligule. Auricles present. Compressed sheath. Flattened seed head with florets arranged alternately. Distinctive annual ryegrass.', 'Annual grass. Germinates in autumn with first rains. Flowers and seeds in spring. Dies in summer. Produces 50,000+ seeds per plant. Extremely competitive weed.', 'Rotation of herbicide modes of action critical. Pre-emergent (Sakura, Boxer Gold) plus post-emergent (Topik, Select). Harvest weed seed control (HWSC). Non-herbicide tactics including narrow windrow burning and chaff carts.', 'Most resistant weed in Australia. Resistance documented to HRAC Groups A, B, C, D, I, J, K, N. Multiple resistance common. Some populations resistant to 8+ modes of action.', 'A, B, C, D, I, K, N'),

('Raphanus raphanistrum', 'Wild Radish', 'Brassicaceae', ARRAY['Wheat','Barley','Canola','Lupin','Pasture'], 'Deeply lobed basal leaves. Upper stem leaves smaller and less lobed. Yellow to white flowers with 4 petals. Distinctively segmented siliqua seed pods (pod breaks into segments at maturity). Tap root.', 'Annual or biennial broadleaf. Germinates in autumn. Flowers in spring. Competes strongly with cereal crops. Prolific seeder.', 'Group B sulfonylureas (Logran, Ally Max) - but resistance widespread. Group O (Amicide, MCPA). Pixxaro (Group O + B dual mode) for B-resistant plants. Crop rotation to alternative crops.', 'Widespread ALS (Group B) resistance in WA and SA. Some Group O (2,4-D) resistance emerging. Dual resistance to B and O documented in WA.', 'B, O'),

('Arctotheca calendula', 'Capeweed', 'Asteraceae', ARRAY['Pasture','Wheat','Barley','Canola','Legume'], 'Basal rosette with deeply lobed leaves. Upper surface dark green, lower surface white-woolly. Yellow flowers with white centre. Daisy-like appearance in rosette.', 'Annual broadleaf. Germinates in autumn. Overwinters as rosette. Flowers in spring. Dense mats suppress pasture species.', 'MCPA, 2,4-D, Logran (triasulfuron). Broadleaf herbicides in cereals. Cultivation. Pasture improvement. Competitive pasture species.', 'Generally susceptible to herbicides. Limited resistance documented.', ''),

('Sonchus oleraceus', 'Common Sowthistle', 'Asteraceae', ARRAY['Vegetable','Wheat','Canola','Horticulture','Fallow'], 'Hollow stems with milky sap (latex). Lobed leaves clasping stem with soft spines. Yellow dandelion-like flowers. Produces airborne seeds (pappus).', 'Annual or biennial broadleaf. Fast-growing. Flowers and seeds prolifically. Multi-flush germination through year.', '2,4-D, MCPA, Logran, glyphosate (fallow). Cultivation. Paraquat in horticulture. Active growing point control important.', 'Glyphosate resistance confirmed in populations in WA and other states. Generally susceptible to Group B products.', 'G'),

('Conyza spp.', 'Fleabane (Flaxleaf and Hairy)', 'Asteraceae', ARRAY['Fallow','Cotton','Horticulture','Vineyard','Canola'], 'Erect plant with narrow strap-like leaves (flaxleaf fleabane). Small daisy-like flowers in dense branched head. Produces masses of wind-dispersed seeds. Very difficult to control once established.', 'Annual to biennial. Summer and winter germination. Can reach 2m in height. Key fallow weed. Prolific seed producer (up to 200,000 seeds per plant).', 'Glyphosate + 2,4-D in fallow (most effective). Roundup + Spray.Seed + 2,4-D combination. Group A herbicides (Verdict, Select). Hard to control once past rosette stage. 2-pass system needed.', 'Widespread glyphosate resistance in Australia (Conyza bonariensis and C. sumatrensis). One of the most resistant weed species in Australian farming.', 'G'),

('Avena fatua', 'Wild Oat (Winter type)', 'Poaceae', ARRAY['Wheat','Barley','Canola','Lupin'], 'Similar to cultivated oat. Twisted awn. Florets separate at maturity (shattering). Hairy lemma. Seed readily distinguishable from cultivated oat by awn and attachment scar.', 'Annual grass. Germinates in autumn-winter. Taller than most cereals. Prolific seeder up to 500 seeds per plant. Competitive in wheat crops.', 'Group A (Topik, Fusilade, Verdict) post-emergent in broadleaf crops. Tri-allate (Avadex) pre-emergent. Crop rotation. HWSC.', 'Group A resistance documented in some populations. Less widespread than in annual ryegrass. Monitor for resistance.', 'A'),

('Avena ludoviciana', 'Wild Oat (Spring type)', 'Poaceae', ARRAY['Wheat','Barley'], 'Similar to A. fatua. Later germination than winter wild oat. Less twisted awn. Can distinguish by germination time and seed morphology.', 'Annual grass. Spring germinating biotype. Flowers later than winter wild oat.', 'Similar to A. fatua. Later germination timing affects spray timing for post-emergent options.', 'Group A resistance documented.', 'A'),

('Phalaris paradoxa', 'Hood Canary Grass / Paradox Canary Grass', 'Poaceae', ARRAY['Wheat','Barley'], 'Cylindrical compact seed head with distinctive hood-shaped lower glumes. Leaves flat and slightly rough. Auricles absent. Ligule membranous.', 'Annual grass. Autumn germination. Moderately competitive in wheat and barley.', 'Group A (Topik, Fusilade), Group B (Hussar), Boxer Gold pre-emergent. Rotation with broadleaf crops.', 'Some Group A resistance documented.', 'A'),

('Bromus diandrus', 'Ripgut Brome', 'Poaceae', ARRAY['Wheat','Barley','Pasture','Canola'], 'Long awned spikelets. Large drooping panicle. Rough leaves. Awns 3-6cm long. Leaves hairy. Can be confused with other brome species.', 'Annual grass. Autumn germination. Large seeds. Awns attach to wool, clothing and animal skin.', 'Group A herbicides (limited). Pre-emergents (Boxer Gold, Sakura). Most effective control is crop competition and harvest weed seed control.', 'Limited Group A resistance documented. Generally susceptible but pre-emergents have variable efficacy.', ''),

('Hordeum leporinum', 'Barley Grass', 'Poaceae', ARRAY['Wheat','Barley','Pasture','Canola','Lupin'], 'Small dense spike with 3 spikelets per node. Long awns. Auricles small and reddish-coloured. Leaves flat. Glumes narrow and hair-like.', 'Annual grass. Autumn germination. Low growing. Heavy infestation reduces cereal yield. Awns contaminate wool and harm livestock.', 'Group A post-emergent (in broadleaf crops only). Pre-emergents (Boxer Gold, Sakura). Crop rotation. Cultivar competition. HWSC.', 'Group A resistance documented in some populations.', 'A'),

('Chenopodium album', 'Fat Hen / Common Lambsquarters', 'Chenopodiaceae', ARRAY['Vegetable','Canola','Cotton','Maize','Sorghum'], 'Mealy appearance on young leaves. Diamond to oval shaped leaves with toothed margins. Green to reddish stems. Dense flower spikes.', 'Annual broadleaf. Summer germination. Fast-growing. Prolific seeder. Competitive with summer crops.', 'Atrazine (maize/sorghum), metolachlor (pre-emergent), trifluralin, 2,4-D in tolerant crops. Cultivation.', 'Atrazine resistance documented in some populations.', 'C'),

('Echinochloa crus-galli', 'Barnyard Grass', 'Poaceae', ARRAY['Rice','Maize','Sorghum','Vegetable','Sugarcane'], 'Lacks ligule (distinguishing feature). Hairy or smooth sheaths. Panicle reddish to purple. Variable awns - absent to long. Coarse grass.', 'Annual summer grass. Germinates in warm conditions. Major weed in rice and summer row crops. Extremely competitive in rice.', 'Quinclorac (rice), cyhalofop (rice), atrazine (maize/sorghum), thiobencarb. Pre-emergents in row crops.', 'Multiple resistance documented in rice production systems. ACCase and ALS resistance known.', 'A, B'),

('Sorghum halepense', 'Johnson Grass / Aleppo Grass', 'Poaceae', ARRAY['Cotton','Maize','Sorghum','Pasture','Non-crop'], 'Tall perennial grass to 2m. Prominent midrib on wide flat leaves. Dense panicle with reddish spikelets. Deep rhizomes. White pith in stem.', 'Perennial grass with rhizomes. Difficult to control due to rhizome system. Spreads by seed and rhizomes. Serious weed in summer crops.', 'Glyphosate (multiple applications), Group A herbicides (Verdict, Aramo) in broadleaf crops. Cultivation repeatedly during summer fallow. Requires multi-year program.', 'Glyphosate resistance documented in some populations.', 'G'),

('Xanthium strumarium', 'Bathurst Burr / Noogoora Burr', 'Asteraceae', ARRAY['Cotton','Sorghum','Pasture','Riparian'], 'Burr with hooked spines. Alternate coarse leaves with lobed margins. Rough hairy texture. Separate male and female flowers. Burrs attach to wool and clothing.', 'Annual broadleaf. Summer germination. Burrs cause wool contamination and injury to livestock and people.', '2,4-D, MCPA, dicamba in tolerant crops. Glyphosate in fallow. Cultivation. Hand removal in small infestations.', 'Generally susceptible to herbicides.', ''),

('Malva parviflora', 'Small-leaf Mallow / Marshmallow', 'Malvaceae', ARRAY['Vegetable','Wheat','Horticulture','Fallow'], 'Round lobed leaves with 5-7 lobes. Notched petals pink-white. Deep taproot. Flowers at leaf axils. Fruit is cheese wheel shape (schizocarp).', 'Annual or biennial broadleaf. Autumn or spring germination. Deep taproot makes cultivation difficult.', 'MCPA, 2,4-D (poor efficacy), triasulfuron (Logran), metribuzin (Eclipse) in potato. Cultivation. Difficult to control with herbicides.', 'Generally susceptible but poor kill from phenoxyacetics due to waxy leaf surface.', ''),

('Tribulus terrestris', 'Caltrop / Bindii', 'Zygophyllaceae', ARRAY['Cotton','Horticulture','Non-crop','Vineyard'], 'Prostrate spreading plant. Pinnate leaves in pairs. Yellow 5-petalled flowers. Hard spiny fruits (burrs with 2-3 rigid spines). Extremely sharp.', 'Annual summer broadleaf. Spreads by spiny fruits. Major problem in cotton and horticultural soils.', 'MCPA, 2,4-D early. Pre-emergent trifluralin. Glyphosate in fallow. Cultivation before seeding. Burrs persist in soil for years.', 'Generally susceptible.', ''),

('Lactuca serriola', 'Prickly Lettuce', 'Asteraceae', ARRAY['Fallow','Wheat','Canola','Horticulture','Vineyard'], 'Erect plant. Leaves with prickly margins. Leaves clasping stem with distinctive prickles on midrib on underside. Small yellow flower. Produces wind-dispersed seeds.', 'Annual or biennial broadleaf. Multi-season germination. Common in minimum tillage systems.', 'Group B (triasulfuron, flumetsulam). 2,4-D, MCPA. Glyphosate in fallow. Pre-emergents (metribuzin).', 'Group B resistance suspected in some populations.', 'B'),

('Stellaria media', 'Chickweed', 'Caryophyllaceae', ARRAY['Vegetable','Wheat','Barley','Strawberry'], 'Hairy stem with single line of hairs. Small white flowers with deeply notched petals appearing as 10 petals. Small oval leaves with distinct point.', 'Annual cool season broadleaf. Autumn-winter germination. Low growing mat. Can smother seedlings.', 'MCPA, 2,4-D, Logran, bromoxynil in cereals. Cultivation in vegetables. Chickweed generally susceptible.', 'Generally susceptible to most broadleaf herbicides.', ''),

('Polygonum aviculare', 'Wireweed / Prostrate Knotweed', 'Polygonaceae', ARRAY['Vegetable','Orchard','Fallow','Horticulture'], 'Prostrate wiry stems. Small oval to narrow leaves. Membranous sheath (ocrea) at leaf base. Small white-pink flowers. Very wiry difficult to pull up.', 'Annual broadleaf. Summer to autumn germination. Very competitive due to sprawling habit.', 'Group B herbicides. 2,4-D, MCPA, glyphosate in fallow. Pre-emergents.', 'Generally susceptible.', ''),

('Fumaria officinalis', 'Fumitory', 'Papaveraceae', ARRAY['Wheat','Barley','Canola','Vegetable'], 'Pale blue-green finely divided ferny leaves. Pink-purple tubular flowers with dark tip. Climbing or scrambling habit. Hollow stems.', 'Annual cool season broadleaf. Autumn-winter germination. Common in cereals and vegetables.', 'Group B (Broadstrike, Tigrex), 2,4-D, MCPA, bromoxynil. Generally responds to broadleaf herbicides.', 'Some Group B resistance suspected.', 'B'),

('Amaranthus hybridus', 'Smooth Amaranth / Pigweed', 'Amaranthaceae', ARRAY['Cotton','Sorghum','Maize','Vegetable','Soybean'], 'Erect branched plant. Diamond to oval leaves with notched tip. Dense green flower spikes. Prolific seeder. Smooth or slightly hairy stem.', 'Annual summer broadleaf. Fast-growing. Prolific seeder. Competitive in summer crops.', 'Atrazine (maize/sorghum), Group B (Broadstrike), metolachlor, 2,4-D, glyphosate (fallow). Cultivation.', 'Glyphosate resistance documented in A. palmeri internationally. Monitor Australian populations. Atrazine resistance documented.', 'C, G'),

('Galium aparine', 'Cleavers / Goosegrass', 'Rubiaceae', ARRAY['Wheat','Barley','Canola','Chickpea'], 'Scrambling annual with square stems and backward-pointing hooks on stem. Whorls of narrow leaves. Small white flowers. Sticky round fruits.', 'Annual cool season broadleaf. Autumn-winter germination. Climbs on crops reducing harvestability.', 'Group B (Ally Max - metsulfuron), 2,4-D, MCPA, dicamba. Flumetsulam (Broadstrike) in pulses. Difficult to control.', 'Some Group B resistance suspected.', 'B'),

('Conyza bonariensis', 'Hairy Fleabane', 'Asteraceae', ARRAY['Fallow','Cotton','Horticulture','Vineyard'], 'Erect to spreading. Very hairy leaves. Dense branched flower head. Produces massive numbers of wind-dispersed seeds.', 'Annual to biennial. Multiple germination periods. Seeds produced prolifically. Difficult glyphosate-resistant weed.', 'Glyphosate + 2,4-D combination. Paraquat. 2-pass system. Group A herbicides. Difficult to control post-rosette.', 'Glyphosate resistance widespread and high-level in Australian populations. Combined with ALS resistance in some populations.', 'B, G'),

('Cyperus rotundus', 'Purple Nutsedge / Nutgrass', 'Cyperaceae', ARRAY['Vegetable','Cotton','Sugarcane','Maize','Horticulture'], 'Triangular stem (sedge - leaves in 3 ranks). Reddish-purple flower heads. Underground tubers (nutlets) connected by rhizomes. 3-ranked leaf arrangement.', 'Perennial sedge. Spreads by underground tubers and rhizomes. Produces toxic allelochemicals inhibiting other plants. Extremely difficult to eradicate.', 'Halosulfuron (Sempra), imazapic (Nugrass) in tolerant crops. EPTC (soil incorporated). Repeated cultivation. No complete eradication possible.', 'Generally susceptible to sulfonylureas but regrowth from tubers is the major challenge.', 'B'),

('Nassella trichotoma', 'Serrated Tussock', 'Poaceae', ARRAY['Pasture','Non-crop','Native Grassland'], 'Serrated leaf edges (run finger up leaf - cuts, run down - smooth). Tussock growth habit. Very similar to poa grasses. Very fine rolled leaves.', 'Perennial tussock grass. Long-lived. Spreads by wind-dispersed seeds. Toxic to livestock. Declared noxious weed in all states.', 'Glyphosate, flupropanate (Taskforce) spot spray or broadacre. Grazing management. Biological control under development.', 'Limited resistance documented.', ''),

('Hypericum perforatum', 'St Johns Wort', 'Hypericaceae', ARRAY['Pasture','Non-crop'], 'Opposite leaves with transparent glands (visible when held to light). Yellow 5-petalled flowers with black dots on petal margins. Square stems.', 'Perennial broadleaf. Deep root system. Causes photosensitisation in livestock. Declared noxious weed in many states.', 'MCPA, 2,4-D, dicamba (Banvel). Grazing by goats. Biological control (Chrysolina beetle) effective in some areas.', 'Susceptible to phenoxyacetic herbicides.', ''),

('Cirsium vulgare', 'Spear Thistle', 'Asteraceae', ARRAY['Pasture','Cereal','Non-crop'], 'Deep lobed leaves with very sharp spines. Purple flower heads. Produces wind-dispersed seeds. Biennial - rosette first year, flowers second year.', 'Biennial broadleaf. Rosette first year. Flowers and seeds in second year. Competitive rosette suppresses pasture.', 'MCPA, 2,4-D at rosette stage. Grazon Extra (triclopyr + picloram) in pasture. Cultivation and mowing.', 'Generally susceptible.', ''),

('Carduus nutans', 'Nodding Thistle / Musk Thistle', 'Asteraceae', ARRAY['Pasture','Cereal'], 'Nodding large purple flower head (droops when mature). Winged spiny stem. Deeply lobed spiny leaves. Large rosette in year one.', 'Biennial. Large competitive rosette. Important pastoral weed. Competitive with pasture species.', '2,4-D, MCPA, Grazon Extra. Mowing before seed set. Biological control with Rhinocyllus weevil and Urophora fly.', 'Generally susceptible.', ''),

('Rumex crispus', 'Curly Dock', 'Polygonaceae', ARRAY['Pasture','Cereal','Vegetable'], 'Long narrow leaves with distinctly wavy (curly) margins. Reddish flower and seed stalk. Deep taproot. Dock leaves used to treat nettle stings.', 'Perennial broadleaf. Deep taproot. Difficult to kill once established. Seeds remain viable for decades.', 'MCPA, 2,4-D at rosette stage. Dicamba (Banvel). Fluroxypyr. Repeated treatment needed. Taproot regrowth is the challenge.', 'Generally susceptible to broadleaf herbicides but requires repeat treatment.', ''),

('Convolvulus arvensis', 'Field Bindweed / Small Bindweed', 'Convolvulaceae', ARRAY['Wheat','Canola','Vegetable','Vineyard'], 'Twining climbing habit. Arrow-shaped leaves. White or pink funnel-shaped flowers. Deep extensive root system (can go 5m). Difficult to eradicate.', 'Perennial. Extremely deep root system makes eradication near impossible. Competitive climbing weed.', 'Repeated glyphosate applications. 2,4-D, MCPA, dicamba. Multiple years of treatment needed. Never completely eradicated.', 'Generally susceptible to herbicides but root system ensures regrowth.', ''),

('Emex australis', 'Doublegee / Three-cornered Jack', 'Polygonaceae', ARRAY['Wheat','Barley','Canola','Pasture'], 'Triangular seed with 3 sharp spines (diagnostic). Basal rosette. Reddish stem. Oval to triangular leaves. 3-cornered fruit causes severe injury to livestock feet.', 'Annual broadleaf. Autumn germination. Large taproot. Spiny fruits injure livestock.', 'Group B (Logran, Ally Max), 2,4-D, MCPA in cereals. Trifluralin (pre-emergent) in broadleaf crops.', 'Generally susceptible.', ''),

('Phalaris aquatica', 'Phalaris / Canary Grass', 'Poaceae', ARRAY['Pasture','Wheat'], 'Perennial grass. Broad flat leaves. Dense cylindrical seed head. Can be aggressive in establishing pastures. Not a true weed in many contexts - a sown pasture species.', 'Perennial grass. Sown pasture species but can be weedy in cropping rotations.', 'Group A herbicides in broadleaf crops. Managed through rotation.', 'Susceptible to many grass herbicides.', ''),

('Sinapis arvensis', 'Wild Mustard / Charlock', 'Brassicaceae', ARRAY['Wheat','Barley','Oats'], 'Yellow 4-petalled flowers. Hairy leaves. Beak-like siliqua. Distinguished from wild radish by non-segmented pod. Large coarse plant.', 'Annual broadleaf. Autumn germination. Similar to wild radish. Competitive in cereal crops.', 'Group B sulfonylureas, 2,4-D, MCPA, bromoxynil in cereals. Similar management to wild radish.', 'Group B resistance documented in some populations.', 'B'),

('Raphanus raphanistrum x R. sativus', 'Cultivated Radish (Volunteer)', 'Brassicaceae', ARRAY['Wheat','Barley'], 'Similar to wild radish. Escaped radish cultivation. Competitive volunteer from previous crop.', 'Annual broadleaf. Escaped crop volunteer. Similar biology to wild radish.', 'Same herbicide options as wild radish. Monitor for cross-resistance.', 'Same resistance risks as wild radish.', 'B'),

('Echium plantagineum', 'Patersons Curse / Salvation Jane', 'Boraginaceae', ARRAY['Pasture','Cereal'], 'Purple tubular flowers (like bluebells). Bristly hairy leaves. Alternate stem leaves. Basal rosette with large oval leaves. Common in southern Australia.', 'Annual to biennial. Autumn germination. Toxic to some livestock (hepatotoxic pyrrolizidine alkaloids). Large seed bank.', '2,4-D, MCPA at rosette stage. Dicamba (Banvel). Biological control with Longitarsus beetles. Improved pasture competition.', 'Generally susceptible to broadleaf herbicides.', ''),

('Carrichtera annua', 'Ward Weed / Vella', 'Brassicaceae', ARRAY['Wheat','Barley','Canola'], 'Small annual brassica. Deeply divided leaves. Small white-purple flowers. Characteristic triangular fruit with wings. Short-lived annual.', 'Annual broadleaf. Winter annual. Can be moderately competitive in cereal crops.', 'Group B herbicides in cereals. 2,4-D, MCPA. Pre-emergent trifluralin.', 'Group B resistance suspected in some populations.', 'B'),

('Euphorbia peplus', 'Petty Spurge / Garden Spurge', 'Euphorbiaceae', ARRAY['Vegetable','Horticulture','Ornamental'], 'Small plant with milky latex sap. Oval leaves. Distinctive cyathium flowers. Multiple branches from base.', 'Annual broadleaf. Multi-season germination. Common in gardens and vegetable patches.', 'Glyphosate in non-crop areas. Cultivation in gardens.', 'Generally susceptible.', ''),

('Bidens pilosa', 'Cobbler Pegs / Farmers Friend', 'Asteraceae', ARRAY['Vegetable','Cotton','Maize','Sorghum'], 'Dark green pinnate leaves. White daisy flowers with yellow centre. Needle-like seed with barbs that attach to clothing.', 'Annual summer broadleaf. Common weed in tropical and subtropical agriculture.', '2,4-D, MCPA, atrazine (maize), glyphosate. Pre-emergents.', 'Generally susceptible.', ''),

('Ambrosia artemisiifolia', 'Ragweed / Bitterweed', 'Asteraceae', ARRAY['Cotton','Maize','Sorghum','Vegetable'], 'Deeply divided ferny leaves. Inconspicuous green flowers. Pollen causes hay fever. Spreading bushy habit. Not widespread in Australia but present.', 'Annual summer broadleaf. Common in North America. Increasing presence in some Australian areas.', '2,4-D, glyphosate, atrazine. Pre-emergents.', 'Multiple herbicide resistance documented overseas.', ''),

('Datura stramonium', 'Jimsonweed / Common Thornapple', 'Solanaceae', ARRAY['Cotton','Maize','Sorghum','Vegetable'], 'Large coarse plant. Angular toothed leaves with unpleasant smell. White trumpet flowers. Spiny capsule fruit. Highly toxic to humans and livestock.', 'Annual summer broadleaf. Toxic weed. Large vigorous plant very competitive in row crops.', 'Glyphosate in fallow. 2,4-D (pre-bloom), dicamba, atrazine in maize. Remove before seed set.', 'Generally susceptible.', ''),

('Cenchrus echinatus', 'Mossman River Grass / Spiny Burrgrass', 'Poaceae', ARRAY['Cotton','Maize','Sorghum','Pasture'], 'Prostrate to erect grass. Distinctive spiny bur-like seed heads. Burs extremely sharp and painful.', 'Annual summer grass. Burs attach to animals, clothing and machinery. Common in Queensland.', 'Atrazine (maize/sorghum), paraquat, glyphosate. Pre-emergents.', 'Generally susceptible.', ''),

('Paspalum dilatatum', 'Paspalum / Dallisgrass', 'Poaceae', ARRAY['Pasture','Turf','Sugarcane'], 'Perennial grass with 3-4 finger-like racemes. Oval spikelets in 2 rows. Fringed with silky hairs. Common Queensland and NSW coastal pasture grass.', 'Perennial grass. Sown pasture species but can be weedy. Ergot susceptible.', 'Glyphosate. Group A herbicides (fluazifop). Generally managed in context.', 'Susceptible to glyphosate.', ''),

('Setaria faberi', 'Giant Foxtail', 'Poaceae', ARRAY['Maize','Sorghum','Soybean'], 'Dense bristly foxtail seed head. Nodding at maturity. Hairy leaf surface. Auricles absent.', 'Annual summer grass. Competitive in summer row crops.', 'Atrazine, metolachlor, Group A post-emergent. Cultivation.', 'Atrazine resistance documented.', 'C'),

('Setaria viridis', 'Green Foxtail', 'Poaceae', ARRAY['Maize','Sorghum','Vegetable'], 'Similar to giant foxtail but smaller. Erect green bristly seed head. Common summer weed.', 'Annual summer grass. Similar to giant foxtail.', 'Atrazine, metolachlor, Group A herbicides. Cultivation.', 'Atrazine resistance documented.', 'C'),

('Eragrostis cilianensis', 'Stinkgrass', 'Poaceae', ARRAY['Cotton','Maize','Sorghum','Vegetable'], 'Distinctive unpleasant smell. Open panicle with oval spikelets. Common summer weed in warmer climates.', 'Annual summer grass. Warm season weed.', 'Atrazine, paraquat, glyphosate, metolachlor pre-emergent.', 'Generally susceptible.', ''),

('Rottboellia cochinchinensis', 'Itch Grass / Corn Grass', 'Poaceae', ARRAY['Sugarcane','Maize','Sorghum'], 'Coarse grass with itchy hairs causing skin irritation. Cylindrical seed head. Subtropical weed.', 'Annual summer grass. Invasive weed particularly in sugarcane.', 'Atrazine, paraquat, glyphosate, alachlor pre-emergent.', 'Generally susceptible.', ''),

('Parthenium hysterophorus', 'Parthenium Weed', 'Asteraceae', ARRAY['Pasture','Sorghum','Cotton','Non-crop'], 'Deeply divided ferny leaves. Small white daisy-like flowers. Causes contact dermatitis and hay fever. Highly invasive declared weed.', 'Annual broadleaf. Parthenin chemical causes allelopathy inhibiting other plants. Declared noxious in Qld and NT.', 'Picloram, 2,4-D + picloram (Grazon Extra), metsulfuron. Biological control with moths and beetles. Early action critical before establishment.', 'Generally susceptible to herbicides.', ''),

('Cuscuta australis', 'Dodder / Strangle Weed', 'Convolvulaceae', ARRAY['Lucerne','Clover','Soybean','Vegetable'], 'Parasitic vine with no leaves or chlorophyll. Yellow-orange thread-like stems. Wraps around host plants extracting nutrients. White-pink flower clusters.', 'Parasitic annual. Attaches to host by haustoria. Smothers and kills host plants. No soil phase once attached.', 'Remove and destroy infested patches before seed set. Dichlobenil or EPTC soil treatment. Glyphosate on infested patches. No completely effective control once attached.', 'Difficult to control selectively.', ''),

('Solanum nigrum', 'Black Nightshade', 'Solanaceae', ARRAY['Vegetable','Cotton','Potato'], 'Small white flowers with yellow anthers. Green berries ripening to black. Oval leaves. Related to potato and tomato.', 'Annual summer broadleaf. Common in disturbed areas and vegetable crops.', '2,4-D (with care near potato), metribuzin (Eclipse), trifluralin pre-emergent.', 'Generally susceptible.', ''),

('Cirsium arvense', 'Creeping Thistle / Canada Thistle', 'Asteraceae', ARRAY['Pasture','Cereal','Non-crop'], 'Spreading perennial with creeping roots. Smaller flower heads than spear thistle. Pink-purple flowers. Deeply lobed spiny leaves.', 'Perennial with deep creeping root system. Very difficult to control once established. Declared noxious.', 'MCPA, 2,4-D (foliar before flower). Clopyralid (Lontrel), picloram (Grazon). Multiple applications needed. Biological control Cassida beetles.', 'Generally susceptible but root system causes regrowth.', ''),

('Ludwigia octovalvis', 'Water Primrose / Red Stem', 'Onagraceae', ARRAY['Rice','Irrigated Crops'], 'Emergent aquatic plant. Lance-shaped leaves. Yellow 4-petalled flowers. Reddish stems visible at water surface.', 'Perennial aquatic and semi-aquatic. Major weed in rice fields. Spreads by seeds and stem fragments.', 'Halosulfuron, cyhalofop (in rice), glyphosate in non-crop areas. Drainage.', 'Generally susceptible to ALS inhibitors.', 'B'),

('Marsilea drummondii', 'Common Nardoo', 'Marsileaceae', ARRAY['Rice','Irrigated Crops'], '4-leaf clover appearance. Aquatic fern. Common in flooded rice fields. Forms dense mats.', 'Aquatic fern. Common in rice production. Can form dense mats.', 'Limited herbicide options for rice. Metsulfuron has some activity.', 'Limited data.', ''),

('Echinochloa colona', 'Awnless Barnyard Grass / Jungle Rice', 'Poaceae', ARRAY['Rice','Maize','Cotton','Sugarcane'], 'Similar to barnyard grass but lacks ligule. Purplish bands on leaf sheaths (diagnostic). Compact seed head. No awns (awnless).', 'Annual summer grass. Major rice weed. Germinates in warm saturated conditions.', 'Quinclorac (rice), cyhalofop (rice), atrazine (maize), thiobencarb. Pre-emergent applications.', 'Multiple resistance in rice weed management systems worldwide.', 'A, B'),

('Sagittaria montevidensis', 'Giant Arrowhead / Sagittaria', 'Alismataceae', ARRAY['Rice'], 'Arrow-shaped leaves (diagnostic). White 3-petalled flowers. Aquatic. Tubers in soil persist for years.', 'Aquatic perennial. Forms tubers. Major rice weed. Very difficult to eradicate due to tubers.', 'Bensulfuron-methyl in rice. Metsulfuron. Drainage and mechanical removal.', 'ALS resistance documented internationally.', 'B'),

('Leersia hexandra', 'Rice Grass / Cut Grass', 'Poaceae', ARRAY['Rice','Sugarcane'], 'Small aquatic grass. Sharp saw-like leaf margins (cuts skin). Semi-aquatic perennial. Pale green narrow leaves.', 'Perennial semi-aquatic grass. Common in rice and sugarcane districts with poor drainage.', 'Propanil, quinclorac in rice. Drainage.', 'Some propanil resistance documented.', ''),

('Imperata cylindrica', 'Cogon Grass / Blady Grass', 'Poaceae', ARRAY['Sugarcane','Plantation Forestry','Pasture'], 'Silvery white silky seed head. Erect tough grass. Sharp leaf edges. Rhizome-forming. Very aggressive invasive weed.', 'Perennial rhizomatous grass. Extremely difficult to control. Invasive and fire-promoting. Declared weed in many areas.', 'Glyphosate (concentrated, multiple applications), imazapyr (Terrain). Deep ploughing. Multi-year program.', 'Generally susceptible but rhizomes cause regrowth.', ''),

('Cynodon dactylon', 'Couch Grass / Bermuda Grass', 'Poaceae', ARRAY['Cotton','Vegetable','Horticulture','Turf'], 'Prostrate grass with stolons and rhizomes. Finger-like seed heads (3-7). Blue-green colour. Common lawn grass but invasive in crops.', 'Perennial grass with stolons and rhizomes. Difficult to control due to regeneration from vegetative parts.', 'Glyphosate (multiple applications), Group A herbicides (fluazifop in broadleaf crops). Solarisation in horticulture.', 'Generally susceptible to glyphosate but regrowth from rhizomes common.', ''),

('Oxalis corniculata', 'Creeping Wood Sorrel', 'Oxalidaceae', ARRAY['Horticulture','Vegetable','Turf','Ornamental'], 'Heart-shaped 3-leaflet leaves (shamrock). Yellow flowers. Small seed pods explosively eject seeds. Creeping purple-green stems. Bulbils in soil.', 'Perennial bulbil-forming weed. Difficult to eradicate due to bulbils. Common glasshouse and container weed.', 'Pre-emergent herbicides (oxadiazon, pendimethalin). Glyphosate spot-spray in non-crop areas. Difficult to control selectively in many situations.', 'Generally susceptible to glyphosate.', ''),

('Juncus usitatus', 'Common Rush / Soft Rush', 'Juncaceae', ARRAY['Pasture','Irrigated Crops'], 'Cylindrical rush stems. Brown flower clusters partway up stem. Common in wet areas and irrigated systems.', 'Perennial rush. Indicates waterlogging. Forms dense clumps in wet areas.', 'MCPA, glyphosate. Drainage and soil improvement primary control. Mowing before seed set.', 'Generally susceptible.', ''),

('Medicago minima', 'Burr Medic', 'Fabaceae', ARRAY['Pasture','Wheat','Canola'], '3-leaflet leaves. Small yellow flowers. Coiled spiny burrs. Low-growing annual medic.', 'Annual broadleaf. Common in pasture. Can be weedy in some crop situations.', 'Group B sulfonylureas in cereals. Generally managed through grazing in pasture.', 'Generally susceptible.', ''),

('Lolium perenne', 'Perennial Ryegrass (Weed Biotype)', 'Poaceae', ARRAY['Pasture','Wheat','Fallow'], 'Similar to annual ryegrass. Perennial. Rolled leaf blade. Claws (auricles). Membranous ligule. Can be weedy escape from pasture.', 'Perennial grass. Usually a sown pasture species but can be weedy in crop rotations. Resistant biotypes exist.', 'Group A herbicides (Topik, Verdict), Group K pre-emergents, glyphosate fallow.', 'Group A resistance documented in some perennial ryegrass populations.', 'A, G'),

('Chloris truncata', 'Windmill Grass', 'Poaceae', ARRAY['Cotton','Sorghum','Fallow','Horticulture'], 'Distinctive windmill-like arrangement of 6-12 spike racemes. Common in dryland and irrigated farming areas. Fast maturing grass.', 'Annual summer grass. Multi-flush germination. Difficult to control in broadacre farming.', 'Glyphosate (fallow), paraquat, Group A in broadleaf crops. Generally susceptible but difficult timing.', 'Glyphosate resistance documented in some Australian populations.', 'G'),

('Panicum effusum', 'Hairy Panic', 'Poaceae', ARRAY['Cotton','Sorghum','Fallow'], 'Very hairy leaves and sheath. Fine open panicle with many small spikelets. Tumbles in wind distributing seeds.', 'Annual summer grass. Tumbleweed habit disperses seeds. Difficult to control.', 'Glyphosate, Group A herbicides. Pre-emergents with metolachlor.', 'Generally susceptible.', ''),

('Urochloa panicoides', 'Liverseed Grass', 'Poaceae', ARRAY['Cotton','Sorghum','Maize','Fallow'], 'Hairy leaf blades. Leaf blade and sheath hairy. Racemes with 2-ranked spikelets. Summer growing annual.', 'Annual summer grass. Important weed in cotton and sorghum. Late-germinating making timing difficult.', 'Glyphosate, Group A herbicides, atrazine (sorghum/maize). Pre-emergent metolachlor.', 'Generally susceptible.', ''),

('Portulaca oleracea', 'Common Purslane', 'Portulacaceae', ARRAY['Vegetable','Cotton','Maize','Horticulture'], 'Succulent fleshy leaves and stems. Reddish prostrate stems. Small yellow flowers. Edible weed in some cultures.', 'Annual summer succulent. Highly drought tolerant due to succulent tissues. Regenerates from stem fragments.', 'Pre-emergents (trifluralin, metolachlor). Glyphosate. Cultivation. Difficult to kill with post-emergents.', 'Generally susceptible but succulent tissues reduce herbicide uptake.', ''),

('Rumex obtusifolius', 'Broad-leaved Dock', 'Polygonaceae', ARRAY['Pasture','Vegetable','Cereal'], 'Large broad leaves with rounded or heart-shaped base. Tall reddish flower stalk. Deep taproot. Larger leaves than curly dock.', 'Perennial. Deep taproot allows regeneration. Long-lived seed bank.', 'MCPA, 2,4-D at rosette. Fluroxypyr, dicamba. Multiple treatments required. Mechanical removal.', 'Generally susceptible.', ''),

('Acetosella vulgaris', 'Sheep Sorrel / Red Sorrel', 'Polygonaceae', ARRAY['Pasture','Acid Soils'], 'Arrow-shaped leaves with backward pointing lobes. Reddish flower stalks. Acid soil indicator. Spreading by rhizomes.', 'Perennial. Indicates acid soil conditions. Spreads by rhizomes. Common in southern Australia.', 'Lime to correct acidity (primary). MCPA, 2,4-D. Competitive pasture species.', 'Generally susceptible.', ''),

('Senecio madagascariensis', 'Fireweed', 'Asteraceae', ARRAY['Pasture','Non-crop'], 'Yellow daisy-like flowers. Deeply toothed leaves. Fast growth after rain. Produces masses of seeds.', 'Annual to biennial. Toxic to livestock (pyrrolizidine alkaloids). Produces abundant seeds. Invasive in eastern Australia.', 'MCPA, 2,4-D, fluroxypyr, picloram. Mowing before seed set. Competitive pasture management.', 'Generally susceptible.', ''),

('Oxalis pes-caprae', 'Soursob / Cape Sorrel', 'Oxalidaceae', ARRAY['Pasture','Vineyard','Orchard','Wheat'], 'Yellow flowers. Heart-shaped 3-leaflet leaves (some with dark spots). Bulbils at various depths in soil. Bright yellow flowers in winter and spring.', 'Perennial bulbil-forming weed. Germinates in autumn. Flowers in spring. Bulbils at multiple depths.', 'MCPA, 2,4-D (some control). Oxyfluorfen in vineyards. Very difficult to eradicate due to deep bulbils. Solarisation in horticulture.', 'Generally susceptible to herbicides but bulbil depth makes control inconsistent.', ''),

('Erodium cicutarium', 'Common Storksbill / Crowfoot', 'Geraniaceae', ARRAY['Pasture','Wheat','Canola'], 'Deeply divided ferny leaves. Small pink 5-petalled flowers. Long beak-like seed (stork bill shape). Low rosette.', 'Annual cool season broadleaf. Common in pasture and cereals. Good early growth competitor.', 'Group B (Logran, Ally Max) in cereals. 2,4-D, MCPA. Generally susceptible.', 'Generally susceptible.', ''),

('Chrysanthemoides monilifera', 'Boneseed / Bitou Bush', 'Asteraceae', ARRAY['Non-crop','Coastal','Native Vegetation'], 'Sprawling shrub. Yellow daisy flowers. Succulent berry-like fruit. Invasive coastal weed in eastern Australia.', 'Perennial shrub. Major environmental weed in NSW. Highly invasive in coastal areas. Smothers native vegetation.', 'Picloram + triclopyr (Grazon Extra), metsulfuron (Brush Off). Biological control in progress (Chrysolina, Mogulones). Declared noxious.', 'Generally susceptible to herbicides.', ''),

('Lantana camara', 'Lantana', 'Verbenaceae', ARRAY['Pasture','Non-crop','Coastal','Rangeland'], 'Dense prickly shrub. Multi-coloured flowers (pink, yellow, orange). Blue-black berries (toxic to livestock). Strong odour when crushed.', 'Perennial shrub. Major environmental and pastoral weed. Toxic berries. Provides harbour for feral animals. Declared noxious in many states.', 'Triclopyr, picloram, metsulfuron, aminopyralid (Grazon DS). Hand pulling for small plants. Biological control (22 agents released). Multi-year program required.', 'Generally susceptible.', ''),

('Opuntia stricta', 'Prickly Pear', 'Cactaceae', ARRAY['Pasture','Rangeland'], 'Succulent cactus with flat pads. Sharp spines. Yellow flowers. Red-purple fruit. Was a major agricultural disaster in Queensland.', 'Perennial succulent cactus. Largely controlled by Cactoblastis biocontrol but resurgent populations occur.', 'Biological control (Cactoblastis cactorum moth) primary. Picloram herbicide for mechanical + chemical. Diesel oil + metsulfuron.', 'Generally susceptible to appropriate herbicides.', ''),

('Spartina alterniflora', 'Smooth Cordgrass', 'Poaceae', ARRAY['Non-crop','Coastal','Estuarine'], 'Tall coarse saltmarsh grass. Cylindrical seed head. Invades saltmarsh and mudflats.', 'Perennial grass. Coastal invasive weed. Smothers native saltmarsh. Declared in some states.', 'Glyphosate (concentrated), fluazifop. Difficult to treat in aquatic environments.', 'Generally susceptible.', '');
