/*
  # Add comprehensive US EPA-registered chemicals - Part 2

  1. Modified Table
    - `agro_chemicals` - Additional US products (specialty crops, miticides, nematicides)
*/

INSERT INTO agro_chemicals (product_name, active_ingredient, chemical_group, mode_of_action, formulation_type, category, target_type, manufacturer, registered_crops, target_issues, application_rate, withholding_period, reentry_period, label_notes, resistance_notes, apvma_registration, registration_number, label_link, country) VALUES
('Oberon 2SC', 'Spiromesifen', 'Tetronic acid', 'Lipid synthesis inhibitor (Group 23)', 'SC', 'insecticide', 'pest', 'Bayer', ARRAY['vegetables', 'cotton', 'citrus', 'ornamentals'], ARRAY['whitefly', 'spider mites', 'broad mites', 'tarsonemid mites'], '8.5 fl oz/acre', '7 days PHI', '12 hours', 'Miticide + whitefly control. Ovicidal.', 'Group 23 - unique lipid target', '', 'EPA 264-778', '', 'US'),
('Portal', 'Fenpyroximate', 'METI', 'Mitochondrial Complex I (Group 21A)', 'SC', 'insecticide', 'pest', 'Nichino America', ARRAY['tree fruits', 'grapes', 'citrus', 'vegetables', 'hops'], ARRAY['spider mites', 'rust mites', 'European red mite', 'broad mite'], '2 pt/acre', '14 days PHI', '12 hours', 'Contact miticide. Fast knockdown.', 'Group 21A - rotate with other miticide classes', '', 'EPA 71711-28', '', 'US'),
('Acramite 50WS', 'Bifenazate', 'Carbazate', 'Mitochondrial Complex III (Group 20D)', 'WS', 'insecticide', 'pest', 'Chemtura', ARRAY['tree fruits', 'grapes', 'berries', 'hops', 'ornamentals'], ARRAY['two-spotted spider mite', 'European red mite', 'Pacific mite'], '0.75-1 lb/acre', '7 days PHI', '12 hours', 'Selective miticide. Safe for beneficials.', 'Group 20D - one app per season', '', 'EPA 400-498', '', 'US'),
('Velum Prime', 'Fluopyram', 'SDHI', 'Succinate dehydrogenase inhibitor (Group 7)', 'SC', 'fungicide', 'disease', 'Bayer', ARRAY['potatoes', 'vegetables', 'peanuts', 'cotton', 'soybeans'], ARRAY['nematodes', 'white mold', 'early blight', 'Rhizoctonia', 'southern blight'], '6.5 fl oz/acre', '7 days PHI', '12 hours', 'Dual-use: nematicide + fungicide in-furrow or foliar.', 'Group 7 - count toward SDHI total', '', 'EPA 264-1168', '', 'US'),
('Nimitz Pro G', 'Fluensulfone', 'Fluoroalkenyl thioether', 'Unknown nematode target (Group unknown)', 'GR', 'insecticide', 'pest', 'ADAMA', ARRAY['vegetables', 'potatoes', 'cucurbits', 'peppers', 'tomatoes'], ARRAY['root-knot nematodes', 'sting nematodes', 'stubby-root nematodes'], '3.5-7 lb/acre', 'Pre-plant', '12 hours', 'Non-fumigant nematicide. Apply and incorporate.', 'Novel mode - no known cross-resistance', '', 'EPA 66222-243', '', 'US'),
('Vydate L', 'Oxamyl', 'Carbamate', 'AChE inhibitor (Group 1A)', 'SL', 'insecticide', 'pest', 'Corteva', ARRAY['potatoes', 'vegetables', 'citrus', 'cotton'], ARRAY['nematodes', 'aphids', 'leafminers', 'whitefly', 'psyllids'], '2-4 pt/acre', '7-14 days PHI', '48 hours', 'Systemic nematicide and insecticide. Restricted Use.', 'Group 1A', '', 'EPA 62719-108', '', 'US'),
('Rescue', 'Fenpropathrin', 'Pyrethroid', 'Sodium channel modulator (Group 3A)', 'EC', 'insecticide', 'pest', 'Various', ARRAY['cotton', 'vegetables', 'tree fruits', 'soybeans'], ARRAY['lygus', 'stink bugs', 'mites', 'bollworm', 'thrips'], '5.1 fl oz/acre', '14 days PHI', '24 hours', 'Pyrethroid with miticide activity. Broad spectrum.', 'Group 3A', '', 'EPA 279-3222', '', 'US'),
('Senstar', 'Isofetamid + Tebuconazole', 'SDHI + Triazole', 'SDHI + DMI (Group 7+3)', 'SC', 'fungicide', 'disease', 'ISK Biosciences', ARRAY['grapes', 'berries', 'stone fruits', 'vegetables'], ARRAY['botrytis', 'powdery mildew', 'brown rot', 'sclerotinia'], '10 fl oz/acre', '0-14 days PHI', '12 hours', 'Premium vineyard and berry fungicide.', 'Group 7+3', '', 'EPA 89442-16', '', 'US'),
('Copper Sulfate Pentahydrate', 'Copper sulfate', 'Inorganic copper', 'Multi-site contact (Group M1)', 'WP', 'fungicide', 'disease', 'Various', ARRAY['vegetables', 'tree fruits', 'grapes', 'citrus', 'potatoes'], ARRAY['bacterial spot', 'fire blight', 'downy mildew', 'late blight', 'citrus canker'], '2-8 lb/acre', '0 days PHI', '24 hours', 'Organic-approved. Apply protectively.', 'Group M1 - no known resistance', '', 'EPA various', '', 'US'),
('Sulfur 90W', 'Sulfur', 'Inorganic', 'Multi-site contact (Group M2)', 'WG', 'fungicide', 'disease', 'Various', ARRAY['grapes', 'tree fruits', 'vegetables', 'berries', 'hops'], ARRAY['powdery mildew', 'rust mites', 'brown rot'], '5-10 lb/acre', '0 days PHI', '24 hours', 'Organic-approved. Avoid in high temps (>90F).', 'Group M2 - no resistance', '', 'EPA various', '', 'US'),
('Aliette WDG', 'Fosetyl-Al', 'Phosphonate', 'Unknown (Group P7)', 'WDG', 'fungicide', 'disease', 'Bayer', ARRAY['citrus', 'avocado', 'berries', 'vegetables', 'turf'], ARRAY['Phytophthora', 'Pythium', 'downy mildew', 'root rot'], '5 lb/acre', '0-60 days PHI', '12 hours', 'Systemic phosphonate for oomycetes.', 'Group P7 - low resistance risk', '', 'EPA 264-516', '', 'US'),
('Avaunt', 'Indoxacarb', 'Oxadiazine', 'Sodium channel blocker (Group 22A)', 'EC', 'insecticide', 'pest', 'FMC', ARRAY['vegetables', 'grapes', 'tree fruits', 'cotton'], ARRAY['armyworm', 'diamondback moth', 'codling moth', 'grape berry moth', 'leafrollers'], '6 fl oz/acre', '14 days PHI', '12 hours', 'Selective Lepidoptera control.', 'Group 22A', '', 'EPA 279-3383', '', 'US'),
('Imidan 70W', 'Phosmet', 'Organophosphate', 'AChE inhibitor (Group 1B)', 'WP', 'insecticide', 'pest', 'Gowan', ARRAY['tree fruits', 'blueberries', 'potatoes'], ARRAY['codling moth', 'plum curculio', 'apple maggot', 'Japanese beetle', 'tufted apple bud moth'], '4.25 lb/acre', '7-14 days PHI', '24 hours', 'OP for fruit orchards. Good CM activity.', 'Group 1B', '', 'EPA 10163-29', '', 'US'),
('Rimon 0.83EC', 'Novaluron', 'Benzoylphenyl urea', 'Chitin synthesis inhibitor (Group 15)', 'EC', 'insecticide', 'pest', 'ADAMA', ARRAY['tree fruits', 'vegetables', 'cotton', 'soybeans'], ARRAY['codling moth', 'leafrollers', 'beet armyworm', 'whitefly larvae', 'Colorado potato beetle'], '12 fl oz/acre', '14 days PHI', '12 hours', 'IGR - targets immature stages. Good residual.', 'Group 15 - IGR class', '', 'EPA 66222-49', '', 'US'),
('Centric 40WG', 'Thiamethoxam', 'Neonicotinoid', 'nAChR agonist (Group 4A)', 'WG', 'insecticide', 'pest', 'Syngenta', ARRAY['vegetables', 'tree fruits', 'potatoes', 'grapes'], ARRAY['aphids', 'whitefly', 'flea beetles', 'Colorado potato beetle', 'leafhoppers'], '2 oz/acre', '7-14 days PHI', '12 hours', 'Foliar neonicotinoid. Pollinator restrictions.', 'Group 4A', '', 'EPA 100-1230', '', 'US'),
('Movento', 'Spirotetramat', 'Tetramic acid', 'Lipid synthesis inhibitor (Group 23)', 'SC', 'insecticide', 'pest', 'Bayer', ARRAY['tree fruits', 'citrus', 'grapes', 'vegetables', 'nuts'], ARRAY['psyllids', 'aphids', 'whitefly', 'mealybugs', 'scale'], '9 fl oz/acre', '7 days PHI', '24 hours', 'Two-way systemic (ambimobile). Unique for psyllids.', 'Group 23', '', 'EPA 264-826', '', 'US'),
('Voliam Flexi', 'Thiamethoxam + Chlorantraniliprole', 'Neonicotinoid + Diamide', 'nAChR + Ryanodine (Group 4A+28)', 'SC', 'insecticide', 'pest', 'Syngenta', ARRAY['vegetables', 'tree fruits', 'cotton', 'soybeans'], ARRAY['lepidoptera', 'aphids', 'whitefly', 'beetles', 'thrips'], '7 fl oz/acre', '7-28 days PHI', '12 hours', 'Broad-spectrum: caterpillars + sucking pests.', 'Group 4A+28', '', 'EPA 100-1320', '', 'US'),
('Torac', 'Tolfenpyrad', 'Pyrazole', 'Mitochondrial Complex I (Group 21A)', 'EC', 'insecticide', 'pest', 'Nichino America', ARRAY['vegetables', 'tree fruits', 'grapes', 'hops'], ARRAY['mites', 'leafhoppers', 'thrips', 'psyllids', 'whitefly'], '21 fl oz/acre', '1-14 days PHI', '12 hours', 'Broad-spectrum miticide/insecticide.', 'Group 21A', '', 'EPA 71711-35', '', 'US'),
('Pounce 25WP', 'Permethrin', 'Pyrethroid', 'Sodium channel modulator (Group 3A)', 'WP', 'insecticide', 'pest', 'FMC', ARRAY['corn', 'soybeans', 'alfalfa', 'vegetables', 'cotton'], ARRAY['corn earworm', 'armyworm', 'cutworm', 'flea beetles', 'grasshoppers'], '6.4 oz/acre', '3-14 days PHI', '12 hours', 'Standard pyrethroid for row crops.', 'Group 3A', '', 'EPA 279-3051', '', 'US'),
('Sevin XLR Plus', 'Carbaryl', 'Carbamate', 'AChE inhibitor (Group 1A)', 'SC', 'insecticide', 'pest', 'Bayer', ARRAY['tree fruits', 'vegetables', 'turf', 'ornamentals', 'corn'], ARRAY['Japanese beetle', 'apple maggot', 'earwigs', 'armyworm', 'fruit thinning'], '2 qt/acre', '3-14 days PHI', '12 hours', 'Broad-spectrum carbamate. Also fruit thinner.', 'Group 1A', '', 'EPA 264-334', '', 'US'),
('Requiem Prime', 'Terpenoid blend (QRD 460)', 'Botanical extract', 'TRPV channel modulator (Group UNE)', 'EC', 'insecticide', 'pest', 'Bayer', ARRAY['vegetables', 'grapes', 'berries', 'tree fruits'], ARRAY['whitefly', 'thrips', 'psyllids', 'aphids', 'mites'], '3 qt/acre', '0 days PHI', '4 hours', 'Biopesticide. Organic compatible. Contact activity.', 'Botanical - no resistance expected', '', 'EPA 264-1176', '', 'US'),
('Kopa Insecticidal Soap', 'Potassium salts of fatty acids', 'Soap', 'Contact desiccant (Group UNR)', 'SL', 'insecticide', 'pest', 'Various', ARRAY['vegetables', 'tree fruits', 'ornamentals', 'herbs'], ARRAY['aphids', 'whitefly', 'mealybugs', 'spider mites', 'thrips'], '1-2% v/v', '0 days PHI', '12 hours', 'OMRI organic. Contact only - good coverage essential.', 'No resistance. Physical mode of action.', '', 'EPA various', '', 'US'),
('Bifenture EC', 'Bifenthrin', 'Pyrethroid', 'Sodium channel modulator (Group 3A)', 'EC', 'insecticide', 'pest', 'UPL', ARRAY['corn', 'soybeans', 'cotton', 'vegetables', 'turf'], ARRAY['corn rootworm', 'stink bugs', 'chinch bugs', 'fire ants', 'armyworm'], '6.4 fl oz/acre', '14 days PHI', '12 hours', 'Broad-spectrum pyrethroid. Soil and foliar uses.', 'Group 3A', '', 'EPA 70506-181', '', 'US')
ON CONFLICT DO NOTHING;
