/*
  # Add comprehensive US EPA-registered chemicals - Part 1 (Herbicides + Fungicides)

  1. Modified Table
    - `agro_chemicals` - Adding 40 additional US EPA-registered products

  2. Products Added
    - Major row crop herbicides (corn, soybean, cotton, wheat)
    - Premium fungicides for specialty and row crops
    - All with proper EPA registration context
*/

INSERT INTO agro_chemicals (product_name, active_ingredient, chemical_group, mode_of_action, formulation_type, category, target_type, manufacturer, registered_crops, target_issues, application_rate, withholding_period, reentry_period, label_notes, resistance_notes, apvma_registration, registration_number, label_link, country) VALUES
('Enlist One', 'Enlist (2,4-D choline)', 'Phenoxy', 'Synthetic Auxin (Group 4)', 'SL', 'herbicide', 'weed', 'Corteva', ARRAY['corn', 'soybeans', 'cotton'], ARRAY['waterhemp', 'Palmer amaranth', 'kochia', 'ragweed', 'lambsquarters'], '2 pt/acre', '14 days PHI', '48 hours', 'Enlist trait required. Buffer zones apply.', 'Group 4 - rotate with non-auxin modes of action', '', 'EPA 62719-695', '', 'US'),
('Warrant', 'Acetochlor', 'Chloroacetamide', 'VLCFA Inhibitor (Group 15)', 'CS', 'herbicide', 'weed', 'Bayer', ARRAY['corn', 'soybeans', 'cotton', 'peanuts'], ARRAY['waterhemp', 'Palmer amaranth', 'foxtail', 'pigweed', 'nightshade'], '3 qt/acre', 'None listed', '12 hours', 'Apply pre-emergence or early post. Encapsulated formulation.', 'Group 15 - use in rotation with Groups 2, 4, 9, 14, 27', '', 'EPA 524-591', '', 'US'),
('Acuron', 'Bicyclopyrone + Mesotrione + S-metolachlor + Atrazine', 'HPPD + Triazine + Chloroacetamide', 'HPPD + PSII + VLCFA (Group 27+5+15)', 'SC', 'herbicide', 'weed', 'Syngenta', ARRAY['corn'], ARRAY['waterhemp', 'Palmer amaranth', 'velvetleaf', 'morningglory', 'giant ragweed', 'foxtail', 'crabgrass'], '2.5 qt/acre', 'None listed', '24 hours', 'Broad-spectrum residual + contact corn herbicide.', 'Multiple modes of action reduce resistance risk', '', 'EPA 100-1466', '', 'US'),
('Tavium Plus VaporGrip', 'Dicamba + S-metolachlor', 'Benzoic acid + Chloroacetamide', 'Synthetic Auxin + VLCFA (Group 4+15)', 'SC', 'herbicide', 'weed', 'Syngenta', ARRAY['soybeans', 'cotton'], ARRAY['Palmer amaranth', 'waterhemp', 'morningglory', 'velvetleaf', 'lambsquarters'], '56.5 fl oz/acre', '14 days PHI soybeans', '24 hours', 'Dicamba-tolerant traits required. Low-volatility formulation.', 'Group 4+15 combination', '', 'EPA 100-1623', '', 'US'),
('XtendiMax with VaporGrip', 'Dicamba (diglycolamine salt)', 'Benzoic acid', 'Synthetic Auxin (Group 4)', 'SL', 'herbicide', 'weed', 'Bayer', ARRAY['soybeans', 'cotton'], ARRAY['Palmer amaranth', 'waterhemp', 'morningglory', 'ragweed', 'kochia'], '22 fl oz/acre', '14 days PHI', '24 hours', 'XtendFlex trait required. Spray buffer zones mandatory.', 'Group 4 - rotate modes of action', '', 'EPA 524-617', '', 'US'),
('Verdict', 'Saflufenacil + Dimethenamid-P', 'PPO + Chloroacetamide', 'PPO + VLCFA (Group 14+15)', 'EC', 'herbicide', 'weed', 'BASF', ARRAY['corn', 'soybeans', 'wheat', 'sorghum'], ARRAY['marestail', 'waterhemp', 'kochia', 'lambsquarters', 'ragweed'], '5 fl oz/acre', 'Pre-plant only', '12 hours', 'Burndown + residual. Apply before crop emergence.', 'Group 14+15 combination', '', 'EPA 7969-345', '', 'US'),
('Anthem Maxx', 'Pyroxasulfone + Fluthiacet-methyl', 'Isoxazoline + PPO', 'VLCFA + PPO (Group 15+14)', 'SC', 'herbicide', 'weed', 'FMC', ARRAY['corn', 'soybeans'], ARRAY['waterhemp', 'Palmer amaranth', 'morningglory', 'pigweed', 'foxtail', 'barnyardgrass'], '4 fl oz/acre', 'Pre-emergence only', '12 hours', 'Pre-emerge residual herbicide.', 'Group 15+14 combination', '', 'EPA 279-3468', '', 'US'),
('Callisto', 'Mesotrione', 'Triketone', 'HPPD Inhibitor (Group 27)', 'SC', 'herbicide', 'weed', 'Syngenta', ARRAY['corn', 'turf', 'sorghum'], ARRAY['velvetleaf', 'nightshade', 'pigweed', 'lambsquarters', 'waterhemp', 'ragweed'], '6 fl oz/acre', '45 days PHI sweet corn', '12 hours', 'Post-emergent broadleaf control in corn. Bleaching symptomology.', 'Group 27 - rotate with Groups 2, 4, 15', '', 'EPA 100-1131', '', 'US'),
('Laudis', 'Tembotrione', 'Triketone', 'HPPD Inhibitor (Group 27)', 'OD', 'herbicide', 'weed', 'Bayer', ARRAY['corn'], ARRAY['velvetleaf', 'lambsquarters', 'pigweed', 'morningglory', 'foxtail', 'shattercane'], '3 fl oz/acre', '45 days PHI', '12 hours', 'Post-emergent corn herbicide. Add MSO adjuvant.', 'Group 27 - rotate modes of action annually', '', 'EPA 264-1065', '', 'US'),
('Resicore', 'Acetochlor + Mesotrione + Clopyralid', 'Chloroacetamide + Triketone + Pyridine', 'VLCFA + HPPD + Auxin (Group 15+27+4)', 'SC', 'herbicide', 'weed', 'Corteva', ARRAY['corn'], ARRAY['waterhemp', 'Palmer amaranth', 'ragweed', 'lambsquarters', 'foxtail', 'morningglory'], '2.25 qt/acre', 'None listed', '24 hours', 'Three modes of action for extended residual.', 'Triple-stacked modes reduce resistance', '', 'EPA 62719-688', '', 'US'),
('Trivapro', 'Benzovindiflupyr + Propiconazole + Azoxystrobin', 'SDHI + DMI + QoI', 'SDHI + DMI + QoI (Group 7+3+11)', 'SE', 'fungicide', 'disease', 'Syngenta', ARRAY['corn', 'wheat', 'soybeans', 'barley', 'peanuts'], ARRAY['gray leaf spot', 'northern corn leaf blight', 'frogeye leaf spot', 'rust', 'Septoria'], '13.7 fl oz/acre', '30 days PHI wheat', '12 hours', 'Three-way fungicide for broad-spectrum disease control.', 'Multiple modes of action', '', 'EPA 100-1581', '', 'US'),
('Veltyma', 'Mefentrifluconazole + Pyraclostrobin', 'Triazole + Strobilurin', 'DMI + QoI (Group 3+11)', 'SE', 'fungicide', 'disease', 'BASF', ARRAY['corn', 'soybeans', 'wheat'], ARRAY['gray leaf spot', 'tar spot', 'frogeye leaf spot', 'cercospora', 'rust'], '7 fl oz/acre', '21 days PHI', '12 hours', 'Strong tar spot activity in corn.', 'Group 3+11. Limit strobilurin apps per season.', '', 'EPA 7969-400', '', 'US'),
('Delaro Complete', 'Prothioconazole + Trifloxystrobin + Fluopyram', 'Triazole + Strobilurin + SDHI', 'DMI + QoI + SDHI (Group 3+11+7)', 'SC', 'fungicide', 'disease', 'Bayer', ARRAY['wheat', 'barley', 'corn', 'soybeans'], ARRAY['fusarium head blight', 'Septoria', 'rust', 'gray leaf spot', 'white mold'], '8 fl oz/acre', '30 days PHI', '12 hours', 'Premium three-way fungicide. Strong FHB activity.', 'Triple mode - strong resistance management', '', 'EPA 264-1198', '', 'US'),
('Lucento', 'Bixafen + Flutriafol', 'SDHI + Triazole', 'SDHI + DMI (Group 7+3)', 'SC', 'fungicide', 'disease', 'FMC', ARRAY['wheat', 'barley', 'soybeans', 'corn'], ARRAY['Septoria', 'tan spot', 'net blotch', 'rust', 'cercospora'], '5 fl oz/acre', '30 days PHI', '12 hours', 'Two-way systemic fungicide for cereals.', 'Group 7+3 combination', '', 'EPA 279-3510', '', 'US'),
('Propulse', 'Fluopyram + Prothioconazole', 'SDHI + Triazole', 'SDHI + DMI (Group 7+3)', 'SC', 'fungicide', 'disease', 'Bayer', ARRAY['soybeans', 'peanuts', 'canola', 'sunflower'], ARRAY['white mold', 'sclerotinia', 'cercospora', 'frogeye leaf spot', 'rust'], '13.6 fl oz/acre', '21 days PHI', '12 hours', 'Strong white mold and sclerotinia control.', 'Group 7+3. Rotate modes of action.', '', 'EPA 264-1080', '', 'US'),
('Miravis Neo', 'Pydiflumetofen + Propiconazole + Azoxystrobin', 'SDHI + DMI + QoI', 'SDHI + DMI + QoI (Group 7+3+11)', 'SE', 'fungicide', 'disease', 'Syngenta', ARRAY['corn', 'soybeans', 'wheat', 'peanuts', 'vegetables'], ARRAY['tar spot', 'cercospora', 'frogeye leaf spot', 'powdery mildew', 'rust'], '13.7 fl oz/acre', '14-30 days PHI', '12 hours', 'Premium broad-spectrum with novel SDHI.', 'Three modes for resistance management', '', 'EPA 100-1640', '', 'US'),
('Elevest', 'Bifenthrin + Chlorantraniliprole', 'Pyrethroid + Diamide', 'Sodium channel + Ryanodine (Group 3A+28)', 'SC', 'insecticide', 'pest', 'FMC', ARRAY['corn', 'soybeans', 'cotton', 'wheat', 'sorghum'], ARRAY['armyworm', 'corn earworm', 'stink bugs', 'aphids', 'cutworm'], '8.5 fl oz/acre', '21 days PHI', '24 hours', 'Dual-mode insecticide for broad-spectrum control.', 'Group 3A+28 combination', '', 'EPA 279-3579', '', 'US'),
('Besiege', 'Lambda-cyhalothrin + Chlorantraniliprole', 'Pyrethroid + Diamide', 'Sodium channel + Ryanodine (Group 3A+28)', 'ZC', 'insecticide', 'pest', 'Syngenta', ARRAY['corn', 'soybeans', 'cotton', 'vegetables', 'sorghum'], ARRAY['bollworm', 'armyworm', 'stink bugs', 'aphids', 'earworm'], '10 fl oz/acre', '21 days PHI', '24 hours', 'Broad-spectrum. Fast knockdown + residual.', 'Group 3A+28', '', 'EPA 100-1376', '', 'US'),
('Vantacor', 'Chlorantraniliprole', 'Diamide', 'Ryanodine receptor modulator (Group 28)', 'SC', 'insecticide', 'pest', 'FMC', ARRAY['vegetables', 'tree fruits', 'grapes', 'potatoes', 'berries'], ARRAY['codling moth', 'oriental fruit moth', 'Colorado potato beetle', 'diamondback moth', 'caterpillars'], '7 fl oz/acre', '3-14 days PHI', '4 hours', 'Low-risk insecticide. IPM compatible.', 'Group 28 - low resistance risk', '', 'EPA 279-3614', '', 'US'),
('Intrepid Edge', 'Methoxyfenozide + Spinetoram', 'Diacylhydrazine + Spinosyn', 'Ecdysone agonist + nAChR (Group 18+5)', 'SC', 'insecticide', 'pest', 'Corteva', ARRAY['tree fruits', 'grapes', 'vegetables', 'nuts'], ARRAY['codling moth', 'leafrollers', 'armyworm', 'loopers', 'fruitworm'], '12 fl oz/acre', '14 days PHI', '4 hours', 'Selective caterpillar control. Safe for beneficials.', 'Group 18+5', '', 'EPA 62719-721', '', 'US'),
('Assail 30SG', 'Acetamiprid', 'Neonicotinoid', 'nAChR agonist (Group 4A)', 'SG', 'insecticide', 'pest', 'UPL', ARRAY['tree fruits', 'grapes', 'vegetables', 'cotton', 'berries'], ARRAY['aphids', 'whitefly', 'leafhopper', 'apple maggot', 'plum curculio'], '4 oz/acre', '7 days PHI', '12 hours', 'Foliar neonicotinoid. Pollinator restrictions apply.', 'Group 4A', '', 'EPA 8033-36', '', 'US'),
('Switch 62.5WG', 'Cyprodinil + Fludioxonil', 'Anilinopyrimidine + Phenylpyrrole', 'Group 9+12', 'WG', 'fungicide', 'disease', 'Syngenta', ARRAY['grapes', 'berries', 'vegetables', 'stone fruits'], ARRAY['botrytis', 'alternaria', 'brown rot', 'anthracnose', 'sclerotinia'], '14 oz/acre', '7 days PHI', '12 hours', 'Industry standard for botrytis in grapes/berries.', 'Group 9+12. Limit applications per season.', '', 'EPA 100-1206', '', 'US'),
('Luna Experience', 'Fluopyram + Tebuconazole', 'SDHI + Triazole', 'SDHI + DMI (Group 7+3)', 'SC', 'fungicide', 'disease', 'Bayer', ARRAY['stone fruits', 'grapes', 'berries', 'vegetables', 'tree nuts'], ARRAY['brown rot', 'powdery mildew', 'botrytis', 'scab', 'rust'], '6.84 fl oz/acre', '7-14 days PHI', '12 hours', 'Premium fruit and vegetable fungicide.', 'Group 7+3', '', 'EPA 264-1092', '', 'US'),
('Presidio', 'Fluopicolide', 'Benzamide', 'Spectrin delocalization (Group 43)', 'SC', 'fungicide', 'disease', 'Corteva', ARRAY['vegetables', 'grapes', 'potatoes', 'cucurbits'], ARRAY['downy mildew', 'late blight', 'Phytophthora'], '4 fl oz/acre', '2 days PHI', '12 hours', 'Must tank-mix with another mode of action.', 'Group 43. Always tank-mix.', '', 'EPA 59639-145', '', 'US'),
('Orondis Ultra', 'Oxathiapiprolin + Mandipropamid', 'Piperidinyl thiazole + CAA', 'Group 49+40', 'SC', 'fungicide', 'disease', 'Syngenta', ARRAY['vegetables', 'potatoes', 'grapes', 'tobacco'], ARRAY['late blight', 'downy mildew', 'Phytophthora', 'Pythium'], '5.5 fl oz/acre', '1-7 days PHI', '4 hours', 'Premium oomycete control. Very low use rates.', 'Group 49+40. Novel mode of action.', '', 'EPA 100-1607', '', 'US'),
('Captan 50WP', 'Captan', 'Phthalimide', 'Multi-site contact (Group M4)', 'WP', 'fungicide', 'disease', 'Drexel', ARRAY['apples', 'cherries', 'peaches', 'grapes', 'berries'], ARRAY['apple scab', 'black rot', 'downy mildew', 'botrytis', 'brown rot'], '3 lb/acre', '0 days PHI', '24 hours', 'Multi-site protectant. Foundation for fruit programs.', 'Group M4 - very low resistance risk', '', 'EPA 19713-36', '', 'US'),
('Rally 40WSP', 'Myclobutanil', 'Triazole', 'DMI (Group 3)', 'WSP', 'fungicide', 'disease', 'Corteva', ARRAY['apples', 'grapes', 'stone fruits', 'berries', 'pecans'], ARRAY['powdery mildew', 'apple scab', 'cedar apple rust', 'brown rot'], '5 oz/acre', '14 days PHI', '24 hours', 'Standard triazole for tree fruit powdery mildew/scab.', 'Group 3. Rotate with strobilurins.', '', 'EPA 62719-410', '', 'US'),
('Mustang Maxx', 'Zeta-cypermethrin', 'Pyrethroid', 'Sodium channel modulator (Group 3A)', 'EC', 'insecticide', 'pest', 'FMC', ARRAY['corn', 'soybeans', 'wheat', 'cotton', 'sorghum', 'alfalfa'], ARRAY['armyworm', 'aphids', 'cereal leaf beetle', 'stink bugs', 'grasshoppers'], '4 fl oz/acre', '21 days PHI', '12 hours', 'Fast-acting pyrethroid for row crops.', 'Group 3A', '', 'EPA 279-3426', '', 'US'),
('Tombstone', 'Cyfluthrin', 'Pyrethroid', 'Sodium channel modulator (Group 3A)', 'EC', 'insecticide', 'pest', 'Bayer', ARRAY['corn', 'soybeans', 'wheat', 'alfalfa', 'vegetables'], ARRAY['corn rootworm adults', 'aphids', 'armyworm', 'bean leaf beetle', 'grasshoppers'], '2.4 fl oz/acre', '21 days PHI', '12 hours', 'Standard pyrethroid for beetle and aphid control.', 'Group 3A', '', 'EPA 264-1050', '', 'US'),
('Steward EC', 'Indoxacarb', 'Oxadiazine', 'Sodium channel blocker (Group 22A)', 'EC', 'insecticide', 'pest', 'FMC', ARRAY['vegetables', 'tree fruits', 'cotton', 'soybeans'], ARRAY['diamondback moth', 'armyworm', 'corn earworm', 'codling moth', 'beet armyworm'], '11.3 fl oz/acre', '3-7 days PHI', '12 hours', 'Selective lepidopteran control. Low impact on beneficials.', 'Group 22A', '', 'EPA 279-3206', '', 'US'),
('Radiant SC', 'Spinetoram', 'Spinosyn', 'nAChR allosteric modulator (Group 5)', 'SC', 'insecticide', 'pest', 'Corteva', ARRAY['vegetables', 'tree fruits', 'grapes', 'berries', 'citrus'], ARRAY['thrips', 'leafminers', 'armyworm', 'loopers', 'spotted wing drosophila'], '6 fl oz/acre', '1-3 days PHI', '4 hours', 'Reduced-risk insecticide. Good IPM fit.', 'Group 5', '', 'EPA 62719-545', '', 'US'),
('Entrust SC', 'Spinosad', 'Spinosyn', 'nAChR allosteric modulator (Group 5)', 'SC', 'insecticide', 'pest', 'Corteva', ARRAY['vegetables', 'tree fruits', 'berries', 'grapes', 'citrus'], ARRAY['thrips', 'diamondback moth', 'armyworm', 'Colorado potato beetle', 'leafminers'], '6 fl oz/acre', '1-3 days PHI', '4 hours', 'OMRI-listed (organic). Fermentation-derived.', 'Group 5 - organic approved', '', 'EPA 62719-621', '', 'US'),
('Sefina', 'Afidopyropen', 'Pyropene', 'Chordotonal organ modulator (Group 9D)', 'EC', 'insecticide', 'pest', 'BASF', ARRAY['vegetables', 'tree fruits', 'cotton', 'potatoes'], ARRAY['aphids', 'whitefly', 'psyllids', 'leafhoppers'], '3.5 fl oz/acre', '0-1 days PHI', '4 hours', 'Novel mode of action. Bee-safe.', 'Group 9D - low resistance risk', '', 'EPA 7969-385', '', 'US'),
('Agri-Mek SC', 'Abamectin', 'Avermectin', 'GluCl channel activator (Group 6)', 'SC', 'insecticide', 'pest', 'Syngenta', ARRAY['tree fruits', 'grapes', 'vegetables', 'citrus', 'cotton'], ARRAY['spider mites', 'rust mites', 'leafminers', 'psyllids', 'pear psylla'], '3.5 fl oz/acre', '28 days PHI', '12 hours', 'Translaminar miticide/insecticide.', 'Group 6', '', 'EPA 100-1424', '', 'US'),
('Atrazine 4L', 'Atrazine', 'Triazine', 'PSII Inhibitor (Group 5)', 'SC', 'herbicide', 'weed', 'Various', ARRAY['corn', 'sorghum', 'sugarcane'], ARRAY['broadleaf weeds', 'foxtail', 'lambsquarters', 'pigweed', 'velvetleaf', 'morningglory'], '2 qt/acre', 'None listed', '12 hours', 'Restricted Use Pesticide in most states.', 'Group 5 - combine with other modes of action', '', 'EPA various', '', 'US'),
('Outlook', 'Dimethenamid-P', 'Chloroacetamide', 'VLCFA Inhibitor (Group 15)', 'EC', 'herbicide', 'weed', 'BASF', ARRAY['corn', 'soybeans', 'potatoes', 'dry beans', 'vegetables'], ARRAY['annual grasses', 'pigweed', 'nightshade', 'foxtail', 'waterhemp'], '21 fl oz/acre', 'Pre-emergence', '12 hours', 'Residual grass control. Safer on potatoes than metolachlor.', 'Group 15', '', 'EPA 7969-156', '', 'US'),
('Quelex', 'Halauxifen-methyl + Florasulam', 'Arylpicolinate + Triazolopyrimidine', 'Auxin + ALS (Group 4+2)', 'WG', 'herbicide', 'weed', 'Corteva', ARRAY['wheat', 'barley', 'triticale'], ARRAY['cleavers', 'kochia', 'wild buckwheat', 'chickweed', 'mustard'], '0.75 oz/acre', '60 days PHI', '12 hours', 'Cereal broadleaf herbicide. Very low use rates.', 'Group 4+2 combination', '', 'EPA 62719-680', '', 'US'),
('Huskie Complete', 'Pyrasulfotole + Bromoxynil + Thiencarbazone-methyl', 'HPPD + Nitrile + ALS', 'HPPD + PSII + ALS (Group 27+6+2)', 'OD', 'herbicide', 'weed', 'Bayer', ARRAY['wheat', 'barley'], ARRAY['kochia', 'wild buckwheat', 'wild mustard', 'cleavers', 'thistle'], '13.5 fl oz/acre', '60 days PHI', '12 hours', 'Three-way cereal herbicide. Broad-spectrum broadleaf.', 'Three modes of action', '', 'EPA 264-1144', '', 'US'),
('Osprey Xtra', 'Mesosulfuron-methyl + Thiencarbazone-methyl', 'Sulfonylurea + Sulfonamide', 'ALS Inhibitor (Group 2)', 'WG', 'herbicide', 'weed', 'Bayer', ARRAY['wheat'], ARRAY['Italian ryegrass', 'wild oat', 'cheat', 'downy brome', 'foxtail'], '4.75 oz/acre', '60 days PHI', '12 hours', 'Post-emergent grass control in winter wheat.', 'Group 2 - resistance common in ryegrass', '', 'EPA 264-1099', '', 'US')
ON CONFLICT DO NOTHING;
