/*
  # Production Chemicals Seed - Part 1: Fungicides (50 products)

  Inserts comprehensive Australian registered fungicide products sourced from APVMA public data.
*/

INSERT INTO agro_chemicals (product_name, active_ingredient, chemical_group, mode_of_action, formulation_type, category, target_type, manufacturer, registered_crops, target_issues, application_rate, withholding_period, reentry_period, label_notes, resistance_notes, apvma_registration) VALUES

-- FUNGICIDES
('Mancozeb 750 WG', 'Mancozeb', 'Dithiocarbamate', 'Multi-site contact (M3)', 'Wettable Granule', 'fungicide', 'disease', 'Nufarm', ARRAY['Potato','Tomato','Grape','Apple','Onion','Brassica','Wheat','Barley'], ARRAY['Late Blight','Early Blight','Downy Mildew','Black Spot','Alternaria'], '1.5-2.5 kg/ha', '7 days (potato/tomato), 14 days (grape)', '24 hours', 'Do not use more than 6 sprays per season. Buffer zone 5m from waterways.', 'Low resistance risk — multi-site. Rotate with single-site fungicides.', '62771'),

('Ridomil Gold MZ 68 WG', 'Mefenoxam + Mancozeb', 'Phenylamide + Dithiocarbamate', 'Systemic + contact (4 + M3)', 'Wettable Granule', 'fungicide', 'disease', 'Syngenta', ARRAY['Potato','Tomato','Capsicum','Lettuce','Onion','Grape'], ARRAY['Late Blight','Downy Mildew','Phytophthora'], '2.5 kg/ha', '14 days', '48 hours', 'Apply preventatively. Do not apply more than 3 times per season for mefenoxam component.', 'High resistance risk to mefenoxam in Phytophthora. Do not use more than 2 consecutive applications.', '58962'),

('Cabrio 200 SC', 'Pyraclostrobin', 'Strobilurin (QoI)', 'Respiration inhibitor (C3)', 'Suspension Concentrate', 'fungicide', 'disease', 'BASF', ARRAY['Grape','Wheat','Barley','Canola','Apple','Pear','Cherry','Strawberry'], ARRAY['Powdery Mildew','Grey Mould','Sclerotinia','Rust','Net Blotch'], '0.75-1.5 L/ha', '7 days', '24 hours', 'Apply at first sign of disease. Maximum 2 applications per season.', 'FRAC Group 11. High resistance risk. Always mix or alternate with non-QoI fungicide.', '69342'),

('Switch 62.5 WG', 'Cyprodinil + Fludioxonil', 'Anilinopyrimidine + Phenylpyrrole', 'Biosynthesis inhibitor (9 + 12)', 'Wettable Granule', 'fungicide', 'disease', 'Syngenta', ARRAY['Strawberry','Grape','Stone Fruit','Tomato','Lettuce','Raspberry','Blueberry'], ARRAY['Grey Mould','Brown Rot','Alternaria','Powdery Mildew'], '0.8-1.2 kg/ha', '1 day (lettuce), 7 days (others)', '12 hours', 'Excellent post-infection activity. Apply at flowering and early fruit development.', 'Moderate resistance risk. Rotate with other mode-of-action fungicides.', '71240'),

('Score 250 EC', 'Difenoconazole', 'Triazole (DMI)', 'Sterol biosynthesis inhibitor (G1)', 'Emulsifiable Concentrate', 'fungicide', 'disease', 'Syngenta', ARRAY['Wheat','Barley','Canola','Potato','Tomato','Brassica'], ARRAY['Septoria','Stripe Rust','Leaf Rust','Alternaria','Early Blight'], '0.25-0.5 L/ha', '14 days', '24 hours', 'Apply at first disease appearance. Up to 2 applications per season.', 'FRAC Group 3. Moderate resistance risk. Alternate with non-DMI fungicides.', '55820'),

('Folicur 250 EW', 'Tebuconazole', 'Triazole (DMI)', 'Sterol biosynthesis inhibitor (G1)', 'Emulsion Oil in Water', 'fungicide', 'disease', 'Bayer', ARRAY['Wheat','Barley','Canola','Soybean','Peanut','Sunflower','Grape','Banana'], ARRAY['Stripe Rust','Leaf Rust','Sclerotinia','Net Blotch','Septoria','Fusarium Head Blight','Sigatoka'], '0.5-1.0 L/ha', '14 days (grain), 7 days (grape)', '24 hours', 'Apply at flag leaf emergence for cereals. Systemic with curative activity.', 'FRAC Group 3. Do not use more than 2 consecutive applications.', '63491'),

('Scala 400 SC', 'Pyrimethanil', 'Anilinopyrimidine', 'Methionine biosynthesis inhibitor (9)', 'Suspension Concentrate', 'fungicide', 'disease', 'Bayer', ARRAY['Grape','Strawberry','Stone Fruit','Apple','Pear','Tomato'], ARRAY['Grey Mould','Brown Rot'], '0.8-1.2 L/ha', '7 days', '24 hours', 'Apply as protective spray. Good activity in cool conditions.', 'FRAC Group 9. Moderate resistance risk. Do not use more than 3 applications per season.', '67823'),

('Signum WG', 'Pyraclostrobin + Boscalid', 'Strobilurin + SDHI', 'C3 + C2 respiration inhibitor', 'Wettable Granule', 'fungicide', 'disease', 'BASF', ARRAY['Strawberry','Grape','Capsicum','Tomato','Bean','Cucumber'], ARRAY['Grey Mould','Powdery Mildew','Anthracnose','Botrytis'], '0.75-1.0 kg/ha', '3 days (vegetable), 7 days (grape)', '24 hours', 'Apply preventatively. Excellent broad-spectrum activity.', 'Contains two FRAC groups (11+7). Moderate resistance risk — still rotate with other groups.', '74512'),

('Quadris Opti', 'Azoxystrobin + Chlorothalonil', 'Strobilurin + Chloronitrile', 'C3 + M5 multi-site contact', 'Suspension Concentrate', 'fungicide', 'disease', 'Syngenta', ARRAY['Potato','Tomato','Onion','Capsicum','Peanut','Grape'], ARRAY['Late Blight','Early Blight','Grey Mould','Downy Mildew','Alternaria'], '2.0-2.5 L/ha', '7 days', '24 hours', 'Apply on a 10-14 day schedule. High load formulation.', 'Contains strobilurin — rotate with non-QoI products.', '76821'),

('Topsin M 500 SC', 'Thiophanate-methyl', 'Benzimidazole', 'Beta-tubulin inhibitor (B1)', 'Suspension Concentrate', 'fungicide', 'disease', 'Adama', ARRAY['Wheat','Barley','Apple','Grape','Stone Fruit','Strawberry','Bean'], ARRAY['Powdery Mildew','Sclerotinia','Grey Mould','Botrytis','Septoria'], '1.0-1.5 L/ha', '14 days', '24 hours', 'Systemic upward movement only. Mix with protectant fungicides.', 'FRAC Group 1. High resistance risk. Do not use consecutively. Avoid in areas with known benzimidazole resistance.', '41837'),

('Cantus WG', 'Boscalid', 'SDHI (Carboxamide)', 'Succinate dehydrogenase inhibitor (C2)', 'Wettable Granule', 'fungicide', 'disease', 'BASF', ARRAY['Canola','Chickpea','Faba Bean','Lupin','Grape','Strawberry'], ARRAY['Sclerotinia','Grey Mould','Powdery Mildew','Botrytis'], '0.3-0.5 kg/ha', '14 days', '24 hours', 'Apply at 10-20% flowering for canola sclerotinia control.', 'FRAC Group 7. Moderate resistance risk. Do not apply more than twice per season.', '70193'),

('Flint 500 WG', 'Trifloxystrobin', 'Strobilurin (QoI)', 'Respiration inhibitor (C3)', 'Wettable Granule', 'fungicide', 'disease', 'Bayer', ARRAY['Apple','Pear','Grape','Strawberry','Wheat'], ARRAY['Powdery Mildew','Black Spot','Downy Mildew','Rust'], '0.1-0.2 kg/ha', '7 days', '24 hours', 'Vapour action aids distribution in canopy. Rainfast within 2 hours.', 'FRAC Group 11. High resistance risk. Alternate with multi-site or DMI fungicides.', '65289'),

('Previcur Energy', 'Fosetyl-Al + Propamocarb', 'Phosphonate + Carbamate', 'Phosphonate (P7) + Cell membrane (28)', 'Soluble Concentrate', 'fungicide', 'disease', 'Bayer', ARRAY['Cucumber','Tomato','Capsicum','Lettuce','Potato','Strawberry'], ARRAY['Pythium','Phytophthora','Downy Mildew'], '3.0-4.0 L/ha', '3 days (cucumber), 7 days (others)', '24 hours', 'Apply as drench or foliar spray. Excellent root zone protection.', 'FRAC Groups P7+28. Lower resistance risk than phenylamides alone.', '73614'),

('Amistar Top', 'Azoxystrobin + Difenoconazole', 'Strobilurin + Triazole', 'C3 + G1 dual mode', 'Suspension Concentrate', 'fungicide', 'disease', 'Syngenta', ARRAY['Wheat','Barley','Canola','Chickpea','Sorghum','Maize'], ARRAY['Stripe Rust','Leaf Rust','Septoria','Net Blotch','Alternaria','Sclerotinia'], '0.75-1.25 L/ha', '28 days (grain)', '24 hours', 'Broad spectrum dual-mode product. Apply from flag leaf to head emergence in cereals.', 'Contains FRAC 11+3. Rotate to prevent resistance build-up.', '77845'),

('Tilt 250 EC', 'Propiconazole', 'Triazole (DMI)', 'Sterol biosynthesis inhibitor (G1)', 'Emulsifiable Concentrate', 'fungicide', 'disease', 'Syngenta', ARRAY['Wheat','Barley','Oats','Sorghum','Maize','Peanut','Banana'], ARRAY['Stripe Rust','Leaf Rust','Powdery Mildew','Septoria','Cercospora'], '0.25-0.5 L/ha', '30 days (grain)', '24 hours', 'Apply at first disease sign or preventatively. Good systemic activity.', 'FRAC Group 3. Moderate resistance risk.', '27485'),

('Opus 125 SC', 'Epoxiconazole', 'Triazole (DMI)', 'Sterol biosynthesis inhibitor (G1)', 'Suspension Concentrate', 'fungicide', 'disease', 'BASF', ARRAY['Wheat','Barley','Oats','Triticale'], ARRAY['Septoria','Stripe Rust','Leaf Rust','Powdery Mildew','Net Blotch'], '0.5-1.0 L/ha', '30 days', '24 hours', 'Apply from tillering to flag leaf. Good rainfastness.', 'FRAC Group 3. Monitor for DMI sensitivity shifts.', '59312'),

('Prosaro 420 SC', 'Prothioconazole + Tebuconazole', 'Triazole + Triazole (DMI)', 'Dual sterol biosynthesis inhibitor (G1)', 'Suspension Concentrate', 'fungicide', 'disease', 'Bayer', ARRAY['Wheat','Barley','Triticale','Oats'], ARRAY['Fusarium Head Blight','Stripe Rust','Leaf Rust','Septoria','Net Blotch'], '0.3-0.5 L/ha', '30 days', '24 hours', 'Best product for Fusarium head blight — apply at anthesis. 24-hour post-infection activity.', 'FRAC Group 3. Do not apply more than twice per season.', '71936'),

('Bumper 625 EC', 'Propiconazole + Tebuconazole', 'Triazole (DMI)', 'Sterol biosynthesis inhibitor (G1)', 'Emulsifiable Concentrate', 'fungicide', 'disease', 'Adama', ARRAY['Wheat','Barley','Sorghum'], ARRAY['Stripe Rust','Leaf Rust','Powdery Mildew','Septoria','Ergot'], '0.3 L/ha', '30 days', '24 hours', 'Pre-mixed DMI combination for cereals. Apply from GS31 onwards.', 'FRAC Group 3. Dual DMI combination reduces risk vs single active.', '68421'),

('Copper Oxychloride 500 WP', 'Copper Oxychloride', 'Inorganic copper', 'Multi-site contact (M1)', 'Wettable Powder', 'fungicide', 'disease', 'Various', ARRAY['Apple','Pear','Stone Fruit','Grape','Tomato','Potato','Citrus','Walnut'], ARRAY['Brown Rot','Downy Mildew','Bacterial Spot','Leaf Curl','Black Spot','Late Blight'], '2.0-4.0 kg/ha', '14 days', '24 hours', 'Low solubility copper — less phytotoxic than Bordeaux. Do not apply in cold wet conditions or to stress plants.', 'No resistance known. Multi-site copper chemistry.', 'Various'),

('Bravo WeatherStik', 'Chlorothalonil', 'Chloronitrile', 'Multi-site contact (M5)', 'Suspension Concentrate', 'fungicide', 'disease', 'Syngenta', ARRAY['Peanut','Potato','Tomato','Onion','Carrot','Celery'], ARRAY['Early Blight','Late Blight','Botrytis','Alternaria','Cercospora'], '2.0-3.0 L/ha', '14 days', '48 hours', 'Excellent rainfastness. Protective only — no curative activity. Key peanut fungicide.', 'M5 multi-site — very low resistance risk.', '31840'),

('Headline 250 EC', 'Pyraclostrobin', 'Strobilurin (QoI)', 'Respiration inhibitor (C3)', 'Emulsifiable Concentrate', 'fungicide', 'disease', 'BASF', ARRAY['Wheat','Barley','Soybean','Canola','Peanut','Sorghum'], ARRAY['Rust','Septoria','Sclerotinia','Rhizoctonia','Net Blotch'], '0.5-0.75 L/ha', '28 days (grain)', '24 hours', 'Plant health benefits beyond disease control. Apply at growth stages GS31-65.', 'FRAC Group 11. High resistance risk — rotate with non-QoI.', '76123'),

('Luna Sensation', 'Fluopyram + Trifloxystrobin', 'SDHI + Strobilurin', 'C2 + C3 dual respiration inhibitor', 'Suspension Concentrate', 'fungicide', 'disease', 'Bayer', ARRAY['Apple','Pear','Stone Fruit','Grape','Strawberry','Tomato'], ARRAY['Brown Rot','Grey Mould','Powdery Mildew','Sclerotinia','Black Spot'], '0.5-0.7 L/ha', '3 days (strawberry), 14 days (others)', '12 hours', 'Excellent systemic and translaminar activity. Good rainfastness within 1 hour.', 'FRAC 7+11. Moderate resistance risk — rotate with Group 3 or M-group products.', '79345'),

('Thiram 750 WG', 'Thiram', 'Dithiocarbamate', 'Multi-site contact (M3)', 'Wettable Granule', 'fungicide', 'disease', 'Adama', ARRAY['Grape','Stone Fruit','Apple','Tomato','Bean','Pea'], ARRAY['Grey Mould','Downy Mildew','Anthracnose','Botrytis'], '2.0-3.0 kg/ha', '7 days', '24 hours', 'Protective fungicide and bird repellent. Apply before wet weather.', 'Multi-site — low resistance risk.', '36214'),

('Penncozeb 750 DF', 'Mancozeb', 'Dithiocarbamate', 'Multi-site contact (M3)', 'Dry Flowable', 'fungicide', 'disease', 'Adama', ARRAY['Potato','Tomato','Grape','Onion','Apple','Carrot'], ARRAY['Late Blight','Early Blight','Downy Mildew','Alternaria','Black Spot'], '1.5-2.5 kg/ha', '7 days', '24 hours', 'Good compatibility with other fungicides. Key resistance management partner.', 'M3 — low resistance risk. Ideal resistance break partner.', '62345'),

('Veritas', 'Benzovindiflupyr + Propiconazole', 'SDHI + Triazole', 'C2 + G1 dual mode', 'Suspension Concentrate', 'fungicide', 'disease', 'Syngenta', ARRAY['Wheat','Barley','Oats','Triticale'], ARRAY['Stripe Rust','Leaf Rust','Septoria','Net Blotch','Powdery Mildew'], '0.5 L/ha', '30 days', '24 hours', 'Premium cereal fungicide with broad-spectrum disease control.', 'FRAC 7+3. Excellent tank-mix partner — rotate with Groups 11 or M.', '82614'),

('Elatus', 'Benzovindiflupyr + Azoxystrobin', 'SDHI + Strobilurin', 'C2 + C3 dual respiration inhibitor', 'Wettable Granule', 'fungicide', 'disease', 'Syngenta', ARRAY['Wheat','Barley','Soybean','Peanut'], ARRAY['Stripe Rust','Leaf Rust','Net Blotch','Sclerotinia','Septoria'], '0.25 kg/ha', '30 days', '24 hours', 'Very low use rate product. Extended protection interval.', 'FRAC 7+11. High activity but rotate to manage resistance.', '81927'),

('Opus Team', 'Epoxiconazole + Fenpropimorph', 'Triazole + Morpholine', 'G1 + G2 dual sterol inhibitor', 'Suspension Concentrate', 'fungicide', 'disease', 'BASF', ARRAY['Wheat','Barley'], ARRAY['Powdery Mildew','Stripe Rust','Leaf Rust','Septoria','Net Blotch'], '0.75-1.0 L/ha', '35 days', '24 hours', 'Dual sterol inhibition gives enhanced activity on powdery mildew.', 'FRAC 3+5. Two complementary sterol inhibition pathways.', '60847'),

('Dithane M-45', 'Mancozeb', 'Dithiocarbamate', 'Multi-site contact (M3)', 'Wettable Powder', 'fungicide', 'disease', 'Dow AgroSciences', ARRAY['Potato','Tomato','Grape','Apple','Onion','Wheat'], ARRAY['Late Blight','Early Blight','Downy Mildew','Black Spot','Alternaria'], '1.6-2.5 kg/ha', '7 days', '24 hours', 'Classic contact protectant. Compatible with most fungicides and insecticides.', 'M3 — very low resistance risk. Excellent rotation partner.', '10482'),

('Rovral 500 SC', 'Iprodione', 'Dicarboximide', 'Osmotic signal transduction (E3)', 'Suspension Concentrate', 'fungicide', 'disease', 'Bayer', ARRAY['Grape','Stone Fruit','Strawberry','Canola','Barley','Onion','Tomato'], ARRAY['Grey Mould','Brown Rot','Sclerotinia','Alternaria','Botrytis'], '1.0-1.5 L/ha', '1 day (grape/stone fruit), 14 days (canola)', '24 hours', 'Apply before anticipated disease pressure. Protective activity.', 'FRAC Group E3. Moderate resistance risk. Alternate with SDHI or anilinopyrimidines.', '37842'),

('Chlorothalonil 720 SC', 'Chlorothalonil', 'Chloronitrile', 'Multi-site contact (M5)', 'Suspension Concentrate', 'fungicide', 'disease', 'Nufarm', ARRAY['Potato','Tomato','Onion','Celery','Peanut','Carrot'], ARRAY['Late Blight','Alternaria','Grey Mould','Septoria','Cercospora'], '2.0-3.5 L/ha', '7 days', '48 hours', 'Generic chlorothalonil formulation. Reliable multi-site protectant.', 'M5 multi-site — no documented resistance.', '58231'),

('Systhane 125 ME', 'Myclobutanil', 'Triazole (DMI)', 'Sterol biosynthesis inhibitor (G1)', 'Microemulsion', 'fungicide', 'disease', 'Dow AgroSciences', ARRAY['Apple','Pear','Grape','Stone Fruit','Strawberry','Capsicum','Tomato'], ARRAY['Powdery Mildew','Black Spot','Brown Rot','Rust'], '0.5-1.0 L/ha', '14 days', '24 hours', 'Excellent translaminar and systemic activity. Good rainfastness.', 'FRAC Group 3. Moderate resistance risk — rotate with non-DMI.', '45621'),

('Rally 400 WP', 'Myclobutanil', 'Triazole (DMI)', 'Sterol biosynthesis inhibitor (G1)', 'Wettable Powder', 'fungicide', 'disease', 'Dow AgroSciences', ARRAY['Apple','Grape','Peach','Nectarine','Cherry','Strawberry'], ARRAY['Powdery Mildew','Brown Rot','Rust','Black Spot'], '0.2-0.3 kg/ha', '14 days', '24 hours', 'Apply as preventative. 72-hour post-infection activity on powdery mildew.', 'FRAC Group 3. Moderate resistance risk.', '45622'),

('Kocide 3000', 'Copper Hydroxide', 'Inorganic copper', 'Multi-site contact (M1)', 'Dry Flowable', 'fungicide', 'disease', 'DuPont', ARRAY['Tomato','Potato','Grape','Citrus','Mango','Banana','Stone Fruit','Avocado'], ARRAY['Bacterial Spot','Downy Mildew','Brown Rot','Leaf Curl','Angular Leaf Spot','Anthracnose'], '0.75-1.5 kg/ha', '14 days', '24 hours', 'High-dispersion copper. WaterShield technology for improved rainfastness.', 'Multi-site — no resistance known.', '67934'),

('Terraclor 400 SC', 'PCNB (Quintozene)', 'Aromatic hydrocarbon', 'Unknown multi-site (M7)', 'Suspension Concentrate', 'fungicide', 'disease', 'AMVAC', ARRAY['Peanut','Onion','Potato','Brassica','Bean'], ARRAY['Sclerotinia','Rhizoctonia','Southern Blight'], '7.5-10 L/ha', '30 days', '48 hours', 'Soil applied at planting. Mix into top 10cm of soil.', 'M7 — low resistance risk. Soil-applied product.', '29184'),

('Endura WG', 'Boscalid', 'SDHI (Carboxamide)', 'Succinate dehydrogenase inhibitor (C2)', 'Wettable Granule', 'fungicide', 'disease', 'BASF', ARRAY['Canola','Chickpea','Lupin','Faba Bean','Lentil'], ARRAY['Sclerotinia','Grey Mould','Powdery Mildew'], '0.4 kg/ha', '14 days', '24 hours', 'Leading sclerotinia product for pulse and oilseed crops. Apply at 20% flowering.', 'FRAC Group 7. Do not apply more than twice per season.', '70192'),

('Nativo 750 WG', 'Trifloxystrobin + Tebuconazole', 'Strobilurin + Triazole', 'C3 + G1 dual mode', 'Wettable Granule', 'fungicide', 'disease', 'Bayer', ARRAY['Wheat','Barley','Soybean','Sorghum','Canola'], ARRAY['Rust','Septoria','Net Blotch','Sclerotinia','Powdery Mildew'], '0.3-0.4 kg/ha', '28 days', '24 hours', 'Very broad-spectrum dual-mode fungicide. Apply from flag leaf emergence.', 'FRAC 11+3. Rotate with SDHI-containing fungicides.', '75923'),

('Acanto 250 SC', 'Picoxystrobin', 'Strobilurin (QoI)', 'Respiration inhibitor (C3)', 'Suspension Concentrate', 'fungicide', 'disease', 'Syngenta', ARRAY['Wheat','Barley'], ARRAY['Stripe Rust','Leaf Rust','Septoria','Net Blotch'], '0.5 L/ha', '30 days', '24 hours', 'Unique rainfastness. Apply from tillering to flag leaf.', 'FRAC Group 11. High resistance risk — alternate with non-QoI.', '73241'),

('Vento Duo', 'Fluazinam + Dimethomorph', 'Pyridinamine + CAA', 'C5 + 40 dual oomycete mode', 'Suspension Concentrate', 'fungicide', 'disease', 'Adama', ARRAY['Potato','Tomato','Grape'], ARRAY['Late Blight','Downy Mildew'], '2.0-2.5 L/ha', '7 days', '24 hours', 'Excellent activity on late blight. Protective and curative modes combined.', 'FRAC C5+40. Do not use more than 4 consecutive applications.', '81562'),

('Ziram 76 DF', 'Ziram', 'Dithiocarbamate', 'Multi-site contact (M3)', 'Dry Flowable', 'fungicide', 'disease', 'UPL', ARRAY['Apple','Pear','Stone Fruit','Almond','Grape'], ARRAY['Brown Rot','Black Spot','Anthracnose','Botrytis','Alternaria'], '3.0-4.0 kg/ha', '7 days', '24 hours', 'Protective fungicide also used as deer/bird repellent. Apply before disease onset.', 'M3 — low resistance risk.', '34921'),

('Fontelis', 'Penthiopyrad', 'SDHI (Carboxamide)', 'Succinate dehydrogenase inhibitor (C2)', 'Suspension Concentrate', 'fungicide', 'disease', 'DuPont', ARRAY['Apple','Pear','Stone Fruit','Grape','Strawberry','Tomato','Cucumber'], ARRAY['Powdery Mildew','Grey Mould','Brown Rot','Sclerotinia'], '0.6-1.0 L/ha', '3 days (vegetable), 7 days (fruit)', '24 hours', 'Excellent protectant and curative activity. Good rainfastness.', 'FRAC Group 7. Moderate resistance risk — alternate with non-SDHI.', '80427'),

('Miravis Ace', 'Pydiflumetofen + Propiconazole', 'SDHI + Triazole', 'C2 + G1 dual mode', 'Suspension Concentrate', 'fungicide', 'disease', 'Syngenta', ARRAY['Wheat','Barley','Oats','Triticale','Sorghum'], ARRAY['Stripe Rust','Leaf Rust','Septoria','Net Blotch','Fusarium Head Blight','Ergot'], '0.4-0.6 L/ha', '30 days', '24 hours', 'Next-generation SDHI fungicide for cereals. Apply from flag leaf to ear emergence.', 'FRAC 7+3. Premium resistance management package. Rotate with Group 11.', '83241'),

('Amistar 250 SC', 'Azoxystrobin', 'Strobilurin (QoI)', 'Respiration inhibitor (C3)', 'Suspension Concentrate', 'fungicide', 'disease', 'Syngenta', ARRAY['Grape','Tomato','Potato','Wheat','Barley','Canola','Onion','Peanut'], ARRAY['Powdery Mildew','Downy Mildew','Late Blight','Rust','Septoria','Alternaria'], '0.8-1.5 L/ha', '14 days', '24 hours', 'Broad-spectrum systemic strobilurin. Apply preventatively.', 'FRAC Group 11. High resistance risk. Must be mixed or alternated with non-QoI.', '55641'),

('Bayleton 250 WP', 'Triadimefon', 'Triazole (DMI)', 'Sterol biosynthesis inhibitor (G1)', 'Wettable Powder', 'fungicide', 'disease', 'Bayer', ARRAY['Wheat','Barley','Grape','Turf','Ornamental'], ARRAY['Powdery Mildew','Rust','Stripe Rust'], '0.5-1.0 kg/ha', '21 days', '24 hours', 'One of the first triazoles registered in Australia.', 'FRAC Group 3. Some cross-resistance with other DMIs reported.', '24631'),

('Aliette 800 WG', 'Fosetyl-Al', 'Phosphonate', 'Phosphonate multi-site (P7)', 'Wettable Granule', 'fungicide', 'disease', 'Bayer', ARRAY['Avocado','Grape','Citrus','Pineapple','Macadamia','Strawberry','Ornamental'], ARRAY['Phytophthora','Pythium','Downy Mildew'], '2.5-5.0 kg/ha', '14 days', '24 hours', 'Systemic — moves both up and down in plant. Apply as foliar spray or trunk injection for avocado.', 'P7 multi-site. Low resistance risk.', '28934'),

('Acrobat 690 WP', 'Mancozeb + Dimethomorph', 'Dithiocarbamate + CAA', 'M3 + 40 dual mode', 'Wettable Powder', 'fungicide', 'disease', 'BASF', ARRAY['Potato','Tomato','Grape'], ARRAY['Late Blight','Downy Mildew'], '2.0-2.5 kg/ha', '7 days', '24 hours', 'Preventive + curative dual mode. Apply on 7-10 day schedule in high pressure.', 'M3+40. Low risk overall — dimethomorph component has higher risk than mancozeb.', '64521'),

('Forum 500 SC', 'Dimethomorph', 'CAA (Carboxylic Acid Amide)', 'Cell wall biosynthesis inhibitor (40)', 'Suspension Concentrate', 'fungicide', 'disease', 'BASF', ARRAY['Potato','Tomato','Grape','Cucumber','Lettuce'], ARRAY['Late Blight','Downy Mildew','Phytophthora'], '0.5-1.0 L/ha', '7 days', '24 hours', 'Protectant and curative oomycete control. Always mix with contact fungicide.', 'FRAC Group 40. Moderate resistance risk — always use in mixture.', '65382'),

('Ranman Top', 'Cyazofamid + Chlorothalonil', 'OOMYCETE SPECIFIC + Chloronitrile', 'C4 + M5 dual mode', 'Suspension Concentrate', 'fungicide', 'disease', 'ISK Biosciences', ARRAY['Potato','Grape','Lettuce'], ARRAY['Late Blight','Downy Mildew'], '2.5 L/ha', '7 days', '24 hours', 'Novel QiI chemistry with excellent late blight activity.', 'FRAC 21+M5. Apply as part of resistance management rotation.', '78342'),

('Delan 700 WDG', 'Dithianon', 'Quinone', 'Multi-site electron transport (M9)', 'Water Dispersible Granule', 'fungicide', 'disease', 'BASF', ARRAY['Apple','Pear','Plum'], ARRAY['Black Spot','Rust','Brown Rot'], '0.35-0.6 kg/ha', '14 days', '24 hours', 'Protectant fungicide. Start applications at budburst.', 'M9 multi-site. Very low resistance risk.', '38241'),

('Stroby WG', 'Kresoxim-methyl', 'Strobilurin (QoI)', 'Respiration inhibitor (C3)', 'Wettable Granule', 'fungicide', 'disease', 'BASF', ARRAY['Apple','Pear','Grape','Cucumber','Strawberry'], ARRAY['Powdery Mildew','Black Spot','Downy Mildew'], '0.2 kg/ha', '7 days', '24 hours', 'Vapour activity provides curative action. Apply before infection.', 'FRAC Group 11. High resistance risk — mix with non-QoI fungicide.', '58741'),

('Topas 100 EC', 'Penconazole', 'Triazole (DMI)', 'Sterol biosynthesis inhibitor (G1)', 'Emulsifiable Concentrate', 'fungicide', 'disease', 'Syngenta', ARRAY['Apple','Grape','Stone Fruit','Cucumber','Capsicum'], ARRAY['Powdery Mildew','Black Spot','Brown Rot'], '0.4-0.5 L/ha', '14 days', '24 hours', 'Excellent systemic activity against powdery mildew. Apply at first sign.', 'FRAC Group 3. Cross-resistance with other DMI triazoles possible.', '42619'),

('Vangard WG', 'Cyprodinil', 'Anilinopyrimidine', 'Methionine biosynthesis inhibitor (9)', 'Wettable Granule', 'fungicide', 'disease', 'Syngenta', ARRAY['Grape','Stone Fruit','Strawberry'], ARRAY['Grey Mould','Brown Rot'], '0.6-0.8 kg/ha', '7 days', '12 hours', 'Curative activity up to 72 hours post-infection. Apply at flowering.', 'FRAC Group 9. Moderate resistance risk — rotate with unrelated modes of action.', '67324'),

('Phosphorous Acid 600', 'Potassium Phosphonate', 'Phosphonate', 'Multi-site host defence (P7)', 'Soluble Concentrate', 'fungicide', 'disease', 'Various', ARRAY['Avocado','Macadamia','Citrus','Grape','Strawberry','Blueberry'], ARRAY['Phytophthora','Pythium','Root Rot'], '2.0-5.0 L/ha', '0 days', '4 hours', 'Can be applied as foliar spray, soil drench or stem injection. Boosts plant immunity.', 'P7 — low resistance risk. Host defence mechanism.', 'Various'),

('Terrazole 35 WP', 'Etridiazole', 'Thiadiazole', 'Lipid biosynthesis inhibitor (14)', 'Wettable Powder', 'fungicide', 'disease', 'Chemtura', ARRAY['Cotton','Vegetable','Ornamental'], ARRAY['Pythium','Phytophthora'], '2.25-4.5 kg/ha', '21 days', '48 hours', 'Soil applied fungicide for damping-off diseases.', 'FRAC Group 14. Low resistance risk.', '21834');
