/*
  # Add comprehensive Canada PMRA-registered chemicals

  1. Modified Table
    - `agro_chemicals` - Adding 60+ Canadian PMRA-registered products

  2. Products Added
    - Major prairie crop herbicides (canola, wheat, barley, pulses)
    - Fungicides for cereal and pulse diseases
    - Insecticides for prairie and horticultural pests
    - Canadian brand names and PMRA registration context
*/

INSERT INTO agro_chemicals (product_name, active_ingredient, chemical_group, mode_of_action, formulation_type, category, target_type, manufacturer, registered_crops, target_issues, application_rate, withholding_period, reentry_period, label_notes, resistance_notes, apvma_registration, registration_number, label_link, country) VALUES
('Simplicity GoDRI', 'Pyroxasulfone + Sulfentrazone + Carfentrazone-ethyl', 'Isoxazoline + PPO', 'VLCFA + PPO (Group 15+14)', 'WG', 'herbicide', 'weed', 'FMC Canada', ARRAY['wheat', 'barley'], ARRAY['wild oat', 'green foxtail', 'cleavers', 'kochia', 'wild buckwheat'], '111 g/acre', 'Pre-emergence', '12 hours', 'Prairie cereal pre-emergent. Broad-spectrum.', 'Group 15+14 combination', '', 'PMRA 32766', '', 'CA'),
('Goldwing', 'Pyroxasulfone + Sulfentrazone', 'Isoxazoline + PPO', 'VLCFA + PPO (Group 15+14)', 'SC', 'herbicide', 'weed', 'FMC Canada', ARRAY['field peas', 'chickpeas', 'lentils', 'soybeans'], ARRAY['green foxtail', 'wild oat', 'pigweed', 'nightshade', 'kochia'], '222 mL/acre', 'Pre-emergence', '12 hours', 'Pre-emergent for pulse crops. Extended residual.', 'Group 15+14', '', 'PMRA 33145', '', 'CA'),
('Varro', 'Pyroxasulfone + Flumioxazin', 'Isoxazoline + PPO', 'VLCFA + PPO (Group 15+14)', 'SC', 'herbicide', 'weed', 'Valent Canada', ARRAY['soybeans', 'dry beans'], ARRAY['waterhemp', 'Palmer amaranth', 'pigweed', 'nightshade', 'foxtail'], '90 mL/acre', 'Pre-emergence', '12 hours', 'Soybean and dry bean residual herbicide.', 'Group 15+14', '', 'PMRA 33278', '', 'CA'),
('Ares', 'Imazamox + Imazethapyr', 'Imidazolinone', 'ALS Inhibitor (Group 2)', 'SL', 'herbicide', 'weed', 'BASF Canada', ARRAY['Clearfield canola', 'Clearfield wheat', 'Clearfield lentils'], ARRAY['volunteer canola', 'wild mustard', 'stinkweed', 'cleavers', 'chickweed'], '0.4 L/acre', '60 days', '12 hours', 'Clearfield system only. Do not use on non-CL varieties.', 'Group 2 - resistance widespread in wild mustard', '', 'PMRA 27517', '', 'CA'),
('Solo', 'Imazamox', 'Imidazolinone', 'ALS Inhibitor (Group 2)', 'SL', 'herbicide', 'weed', 'BASF Canada', ARRAY['Clearfield canola', 'Clearfield wheat'], ARRAY['volunteer canola', 'wild mustard', 'chickweed', 'cleavers', 'stinkweed'], '0.2 L/acre', '70 days', '12 hours', 'Post-emergent in CL crops. Tank-mix partner.', 'Group 2', '', 'PMRA 28956', '', 'CA'),
('Express SG', 'Tribenuron-methyl', 'Sulfonylurea', 'ALS Inhibitor (Group 2)', 'SG', 'herbicide', 'weed', 'FMC Canada', ARRAY['wheat', 'barley', 'oats'], ARRAY['wild buckwheat', 'stinkweed', 'wild mustard', 'chickweed', 'kochia'], '8 g/acre', '60 days', '12 hours', 'Post-emergent broadleaf in cereals.', 'Group 2 - resistance common', '', 'PMRA 25218', '', 'CA'),
('Muster', 'Ethametsulfuron-methyl', 'Sulfonylurea', 'ALS Inhibitor (Group 2)', 'SC', 'herbicide', 'weed', 'FMC Canada', ARRAY['canola'], ARRAY['stinkweed', 'wild mustard', 'shepherds purse', 'flixweed'], '20 g/acre', '60 days', '12 hours', 'Canola-specific broadleaf herbicide.', 'Group 2', '', 'PMRA 24516', '', 'CA'),
('Curtail M', 'Clopyralid + MCPA', 'Pyridine + Phenoxy', 'Synthetic Auxin (Group 4)', 'SL', 'herbicide', 'weed', 'Corteva Canada', ARRAY['wheat', 'barley', 'oats', 'pasture'], ARRAY['Canada thistle', 'sow thistle', 'cleavers', 'wild buckwheat'], '0.67 L/acre', '60 days', '12 hours', 'Thistle specialist in cereals and pasture.', 'Group 4', '', 'PMRA 22029', '', 'CA'),
('Lontrel 360', 'Clopyralid', 'Pyridine', 'Synthetic Auxin (Group 4)', 'SL', 'herbicide', 'weed', 'Corteva Canada', ARRAY['canola', 'flax', 'sugar beets', 'onions'], ARRAY['Canada thistle', 'volunteer clover', 'dandelion', 'sow thistle'], '0.17 L/acre', '60 days', '12 hours', 'Selective thistle control. Persistent.', 'Group 4', '', 'PMRA 23545', '', 'CA'),
('Prestige XL', 'Flumetsulam + Clopyralid', 'Triazolopyrimidine + Pyridine', 'ALS + Auxin (Group 2+4)', 'SL', 'herbicide', 'weed', 'Corteva Canada', ARRAY['canola'], ARRAY['wild buckwheat', 'cleavers', 'thistles', 'chickweed', 'stinkweed'], '0.4 L/acre', '60 days', '12 hours', 'Two-mode canola broadleaf herbicide.', 'Group 2+4 combination', '', 'PMRA 28734', '', 'CA'),
('Centurion', 'Clethodim', 'Cyclohexanedione', 'ACCase Inhibitor (Group 1)', 'EC', 'herbicide', 'weed', 'ADAMA Canada', ARRAY['canola', 'flax', 'pulses', 'sunflower', 'vegetables'], ARRAY['wild oat', 'green foxtail', 'volunteer cereals', 'quack grass', 'foxtail barley'], '0.1-0.2 L/acre', '60-75 days', '12 hours', 'Grass-specific herbicide in broadleaf crops.', 'Group 1 - rotate with other modes', '', 'PMRA 21740', '', 'CA'),
('Assure II', 'Quizalofop-P-ethyl', 'Aryloxyphenoxypropionate', 'ACCase Inhibitor (Group 1)', 'EC', 'herbicide', 'weed', 'ADAMA Canada', ARRAY['canola', 'flax', 'soybeans', 'dry beans', 'sunflower'], ARRAY['wild oat', 'volunteer wheat', 'green foxtail', 'quack grass', 'foxtail barley'], '0.2 L/acre', '60-80 days', '12 hours', 'Fop grass herbicide for broadleaf crops.', 'Group 1', '', 'PMRA 23624', '', 'CA'),
('Puma Advance', 'Fenoxaprop-P-ethyl', 'Aryloxyphenoxypropionate', 'ACCase Inhibitor (Group 1)', 'EC', 'herbicide', 'weed', 'Bayer Canada', ARRAY['wheat', 'barley'], ARRAY['wild oat', 'green foxtail', 'Persian darnel', 'volunteer canola'], '0.4 L/acre', '60 days', '12 hours', 'Post-emergent grass control in cereals.', 'Group 1 - rotate with other modes', '', 'PMRA 24821', '', 'CA'),
('Everest 3.0', 'Flucarbazone-sodium', 'Sulfonylaminocarbonyl-triazolinone', 'ALS Inhibitor (Group 2)', 'WG', 'herbicide', 'weed', 'FMC Canada', ARRAY['wheat'], ARRAY['wild oat', 'foxtail barley', 'Japanese brome', 'downy brome', 'Persian darnel'], '16 g/acre', '60 days', '12 hours', 'Unique ALS for wild oat + brome in wheat.', 'Group 2 - monitor for resistance', '', 'PMRA 27096', '', 'CA'),
('Tundra', 'Lambda-cyhalothrin + Chlorantraniliprole', 'Pyrethroid + Diamide', 'Sodium channel + Ryanodine (Group 3A+28)', 'CS', 'insecticide', 'pest', 'Syngenta Canada', ARRAY['canola', 'wheat', 'barley', 'pulses', 'corn'], ARRAY['flea beetles', 'bertha armyworm', 'diamondback moth', 'cutworm', 'grasshoppers'], '53-107 mL/acre', '21 days', '24 hours', 'Dual-mode insecticide for prairie crops.', 'Group 3A+28', '', 'PMRA 31523', '', 'CA'),
('Matador 120EC', 'Lambda-cyhalothrin', 'Pyrethroid', 'Sodium channel modulator (Group 3A)', 'EC', 'insecticide', 'pest', 'Syngenta Canada', ARRAY['canola', 'cereals', 'pulses', 'corn', 'potatoes'], ARRAY['flea beetles', 'grasshoppers', 'bertha armyworm', 'aphids', 'cutworm'], '41-83 mL/acre', '7-21 days', '24 hours', 'Standard prairie pyrethroid. Fast knockdown.', 'Group 3A', '', 'PMRA 24984', '', 'CA'),
('Decis 100EC', 'Deltamethrin', 'Pyrethroid', 'Sodium channel modulator (Group 3A)', 'EC', 'insecticide', 'pest', 'Bayer Canada', ARRAY['canola', 'cereals', 'pulses', 'vegetables', 'potatoes'], ARRAY['flea beetles', 'grasshoppers', 'aphids', 'bertha armyworm', 'Colorado potato beetle'], '40-83 mL/acre', '7-21 days', '12 hours', 'Pyrethroid for field and vegetable crops.', 'Group 3A', '', 'PMRA 22478', '', 'CA'),
('Coragen', 'Chlorantraniliprole', 'Diamide', 'Ryanodine receptor modulator (Group 28)', 'SC', 'insecticide', 'pest', 'FMC Canada', ARRAY['canola', 'vegetables', 'fruits', 'potatoes', 'corn'], ARRAY['bertha armyworm', 'diamondback moth', 'Colorado potato beetle', 'codling moth', 'corn borer'], '75-250 mL/acre', '3-14 days', '4 hours', 'Low-risk diamide. Excellent IPM fit.', 'Group 28', '', 'PMRA 29056', '', 'CA'),
('Delegate', 'Spinetoram', 'Spinosyn', 'nAChR allosteric modulator (Group 5)', 'WG', 'insecticide', 'pest', 'Corteva Canada', ARRAY['tree fruits', 'vegetables', 'grapes', 'berries'], ARRAY['codling moth', 'oriental fruit moth', 'spotted wing drosophila', 'thrips', 'leafrollers'], '100-200 g/acre', '7 days', '4 hours', 'Spinosyn for horticulture. Good residual.', 'Group 5', '', 'PMRA 28772', '', 'CA'),
('Lagon 480EC', 'Dimethoate', 'Organophosphate', 'AChE inhibitor (Group 1B)', 'EC', 'insecticide', 'pest', 'Various', ARRAY['canola', 'wheat', 'barley', 'flax', 'mustard'], ARRAY['flea beetles', 'aphids', 'lygus bugs', 'grasshoppers', 'bertha armyworm'], '0.2 L/acre', '14-21 days', '48 hours', 'Systemic OP for prairie pests. REI restrictions.', 'Group 1B', '', 'PMRA 12598', '', 'CA'),
('Concept', 'Imidacloprid', 'Neonicotinoid', 'nAChR agonist (Group 4A)', 'SC', 'insecticide', 'pest', 'Bayer Canada', ARRAY['canola', 'soybeans', 'corn', 'potatoes'], ARRAY['flea beetles', 'wireworms', 'aphids', 'Colorado potato beetle', 'corn rootworm'], 'Seed treatment', 'Seed applied', '12 hours', 'Seed treatment insecticide. Pollinator label.', 'Group 4A - seed treatment restrictions', '', 'PMRA 27367', '', 'CA'),
('Prosaro XTR', 'Prothioconazole + Tebuconazole', 'Triazoles', 'DMI (Group 3)', 'EC', 'fungicide', 'disease', 'Bayer Canada', ARRAY['wheat', 'barley', 'oats', 'rye'], ARRAY['fusarium head blight', 'Septoria', 'leaf rust', 'net blotch', 'tan spot'], '0.32 L/acre', '36 days', '12 hours', 'Premium cereal fungicide. FHB standard.', 'Group 3 - rotate with strobilurins', '', 'PMRA 28013', '', 'CA'),
('Caramba', 'Metconazole', 'Triazole', 'DMI (Group 3)', 'SL', 'fungicide', 'disease', 'BASF Canada', ARRAY['wheat', 'barley', 'canola'], ARRAY['fusarium head blight', 'Septoria', 'sclerotinia', 'leaf rust', 'net blotch'], '0.2-0.4 L/acre', '30-36 days', '12 hours', 'Strong FHB and sclerotinia activity.', 'Group 3', '', 'PMRA 27343', '', 'CA'),
('Proline 480SC', 'Prothioconazole', 'Triazole', 'DMI (Group 3)', 'SC', 'fungicide', 'disease', 'Bayer Canada', ARRAY['wheat', 'barley', 'canola', 'pulses'], ARRAY['fusarium head blight', 'Septoria', 'sclerotinia', 'ascochyta', 'net blotch'], '0.16 L/acre', '36 days', '12 hours', 'Versatile triazole. Broad label.', 'Group 3', '', 'PMRA 27834', '', 'CA'),
('Folicur 432F', 'Tebuconazole', 'Triazole', 'DMI (Group 3)', 'SC', 'fungicide', 'disease', 'Bayer Canada', ARRAY['wheat', 'barley', 'canola', 'corn'], ARRAY['leaf rust', 'stripe rust', 'Septoria', 'sclerotinia', 'net blotch'], '0.25 L/acre', '30 days', '12 hours', 'Cost-effective triazole. Prairie standard.', 'Group 3', '', 'PMRA 24756', '', 'CA'),
('Stratego PRO', 'Prothioconazole + Trifloxystrobin', 'Triazole + Strobilurin', 'DMI + QoI (Group 3+11)', 'SC', 'fungicide', 'disease', 'Bayer Canada', ARRAY['wheat', 'barley', 'corn', 'canola'], ARRAY['leaf rust', 'Septoria', 'tan spot', 'net blotch', 'gray leaf spot'], '0.2 L/acre', '36 days', '12 hours', 'Two-way cereal and corn fungicide.', 'Group 3+11', '', 'PMRA 29456', '', 'CA'),
('Headline EC', 'Pyraclostrobin', 'Strobilurin', 'QoI (Group 11)', 'EC', 'fungicide', 'disease', 'BASF Canada', ARRAY['wheat', 'barley', 'canola', 'pulses', 'corn', 'soybeans'], ARRAY['Septoria', 'tan spot', 'sclerotinia', 'anthracnose', 'ascochyta'], '0.2-0.4 L/acre', '36-42 days', '12 hours', 'Broad-spectrum strobilurin. Plant health benefits.', 'Group 11 - max 1-2 apps per season', '', 'PMRA 26844', '', 'CA'),
('Priaxor', 'Fluxapyroxad + Pyraclostrobin', 'SDHI + Strobilurin', 'SDHI + QoI (Group 7+11)', 'EC', 'fungicide', 'disease', 'BASF Canada', ARRAY['wheat', 'barley', 'canola', 'pulses', 'soybeans'], ARRAY['sclerotinia', 'ascochyta', 'Septoria', 'net blotch', 'anthracnose'], '0.2 L/acre', '36 days', '12 hours', 'Premium two-way for cereals and pulses.', 'Group 7+11 combination', '', 'PMRA 30234', '', 'CA'),
('Lance WDG', 'Boscalid', 'SDHI', 'Succinate dehydrogenase inhibitor (Group 7)', 'WDG', 'fungicide', 'disease', 'BASF Canada', ARRAY['canola', 'lentils', 'dry beans', 'chickpeas', 'soybeans'], ARRAY['sclerotinia', 'white mold', 'botrytis', 'ascochyta'], '97-141 g/acre', '36 days', '12 hours', 'Sclerotinia and white mold specialist.', 'Group 7. Max 2 apps per season.', '', 'PMRA 27125', '', 'CA'),
('Contans WG', 'Coniothyrium minitans', 'Biological', 'Mycoparasite of Sclerotinia', 'WG', 'fungicide', 'disease', 'Bayer Canada', ARRAY['canola', 'soybeans', 'dry beans', 'sunflower', 'vegetables'], ARRAY['sclerotinia', 'white mold'], '1-2 kg/acre', 'None - biological', '4 hours', 'Biological sclerotinia control. Apply to soil.', 'Biological - no resistance concerns', '', 'PMRA 29134', '', 'CA'),
('Cotegra', 'Boscalid + Metconazole', 'SDHI + Triazole', 'SDHI + DMI (Group 7+3)', 'SC', 'fungicide', 'disease', 'BASF Canada', ARRAY['canola', 'pulses', 'soybeans', 'sunflower'], ARRAY['sclerotinia', 'white mold', 'ascochyta', 'anthracnose'], '0.2 L/acre', '36 days', '12 hours', 'Two-mode sclerotinia and disease control.', 'Group 7+3', '', 'PMRA 31456', '', 'CA'),
('Acapela', 'Picoxystrobin', 'Strobilurin', 'QoI (Group 11)', 'SC', 'fungicide', 'disease', 'Corteva Canada', ARRAY['wheat', 'barley', 'corn', 'soybeans', 'potatoes'], ARRAY['Septoria', 'tan spot', 'leaf rust', 'cercospora', 'early blight'], '0.2-0.35 L/acre', '30-42 days', '12 hours', 'Broad-spectrum strobilurin.', 'Group 11', '', 'PMRA 29567', '', 'CA'),
('Quadris Top', 'Azoxystrobin + Difenoconazole', 'Strobilurin + Triazole', 'QoI + DMI (Group 11+3)', 'SC', 'fungicide', 'disease', 'Syngenta Canada', ARRAY['potatoes', 'vegetables', 'soybeans', 'corn'], ARRAY['early blight', 'late blight', 'cercospora', 'anthracnose', 'scab'], '0.3-0.5 L/acre', '14-30 days', '12 hours', 'Two-way for potato and vegetable diseases.', 'Group 11+3', '', 'PMRA 29878', '', 'CA'),
('Allegro 500F', 'Fluazinam', 'Phenylpyridinamine', 'Oxidative phosphorylation uncoupler (Group 29)', 'SC', 'fungicide', 'disease', 'ISK Canada', ARRAY['potatoes', 'vegetables', 'canola'], ARRAY['late blight', 'white mold', 'sclerotinia', 'Alternaria'], '0.2 L/acre', '14 days', '12 hours', 'Contact fungicide. No cross-resistance to other classes.', 'Group 29 - low resistance risk', '', 'PMRA 26789', '', 'CA'),
('Sivanto Prime', 'Flupyradifurone', 'Butenolide', 'nAChR agonist (Group 4D)', 'SL', 'insecticide', 'pest', 'Bayer Canada', ARRAY['potatoes', 'vegetables', 'tree fruits', 'berries'], ARRAY['aphids', 'psyllids', 'whitefly', 'leafhoppers', 'Colorado potato beetle'], '200-300 mL/acre', '7 days', '4 hours', 'Novel butenolide. Safer for bees than neonics.', 'Group 4D - distinct from 4A neonics', '', 'PMRA 30567', '', 'CA'),
('Closer', 'Sulfoxaflor', 'Sulfoximine', 'nAChR agonist (Group 4C)', 'SC', 'insecticide', 'pest', 'Corteva Canada', ARRAY['canola', 'cereals', 'potatoes', 'vegetables', 'fruits'], ARRAY['aphids', 'lygus bugs', 'thrips', 'whitefly', 'mealybugs'], '50-100 mL/acre', '7-14 days', '12 hours', 'Novel sulfoximine. Distinct from neonicotinoids.', 'Group 4C', '', 'PMRA 30789', '', 'CA'),
('Cygon 480EC', 'Dimethoate', 'Organophosphate', 'AChE inhibitor (Group 1B)', 'EC', 'insecticide', 'pest', 'Various', ARRAY['canola', 'wheat', 'flax', 'mustard', 'vegetables'], ARRAY['flea beetles', 'lygus bugs', 'aphids', 'thrips', 'sawflies'], '0.2-0.4 L/acre', '14-21 days', '48 hours', 'Systemic OP. Low-cost aphid/flea beetle option.', 'Group 1B', '', 'PMRA 12788', '', 'CA'),
('Malathion 500EC', 'Malathion', 'Organophosphate', 'AChE inhibitor (Group 1B)', 'EC', 'insecticide', 'pest', 'Various', ARRAY['canola', 'cereals', 'vegetables', 'fruits', 'stored grain'], ARRAY['grasshoppers', 'bertha armyworm', 'lygus', 'aphids', 'stored grain pests'], '0.5-1 L/acre', '7-14 days', '12 hours', 'Low-cost broad-spectrum OP.', 'Group 1B', '', 'PMRA 8372', '', 'CA'),
('Silencer 120EC', 'Lambda-cyhalothrin', 'Pyrethroid', 'Sodium channel modulator (Group 3A)', 'EC', 'insecticide', 'pest', 'ADAMA Canada', ARRAY['canola', 'cereals', 'pulses', 'corn', 'soybeans'], ARRAY['flea beetles', 'bertha armyworm', 'grasshoppers', 'cutworms', 'lygus'], '41-83 mL/acre', '7-21 days', '24 hours', 'Generic lambda-cyhalothrin for prairies.', 'Group 3A', '', 'PMRA 30112', '', 'CA'),
('Admire 240FS', 'Imidacloprid', 'Neonicotinoid', 'nAChR agonist (Group 4A)', 'FS', 'insecticide', 'pest', 'Bayer Canada', ARRAY['canola', 'corn', 'soybeans', 'potatoes'], ARRAY['flea beetles', 'wireworms', 'corn rootworm', 'aphids'], 'Seed treatment', 'Seed applied', '12 hours', 'Seed treatment neonicotinoid. Check bee restrictions.', 'Group 4A', '', 'PMRA 27022', '', 'CA'),
('Solvigo', 'Abamectin + Cyantraniliprole', 'Avermectin + Diamide', 'GluCl + Ryanodine (Group 6+28)', 'SC', 'insecticide', 'pest', 'Syngenta Canada', ARRAY['potatoes', 'vegetables'], ARRAY['Colorado potato beetle', 'wireworms', 'aphids', 'nematodes'], 'In-furrow 250 mL/acre', 'In-furrow at planting', '12 hours', 'Soil-applied dual-mode. At-plant control.', 'Group 6+28', '', 'PMRA 32456', '', 'CA'),
('Beleaf 50SG', 'Flonicamid', 'Flonicamid', 'Chordotonal organ modulator (Group 29)', 'SG', 'insecticide', 'pest', 'ISK Canada', ARRAY['canola', 'wheat', 'potatoes', 'tree fruits', 'vegetables'], ARRAY['aphids', 'lygus bugs', 'plant bugs', 'psyllids'], '48-60 g/acre', '7-14 days', '12 hours', 'Selective aphicide/plantbugicide. Bee-safe.', 'Group 29 - unique target', '', 'PMRA 29345', '', 'CA'),
('Pounce 384EC', 'Permethrin', 'Pyrethroid', 'Sodium channel modulator (Group 3A)', 'EC', 'insecticide', 'pest', 'FMC Canada', ARRAY['canola', 'cereals', 'corn', 'vegetables', 'alfalfa'], ARRAY['flea beetles', 'bertha armyworm', 'cutworms', 'grasshoppers', 'corn borer'], '62-107 mL/acre', '21 days', '12 hours', 'Cost-effective pyrethroid for prairies.', 'Group 3A', '', 'PMRA 17319', '', 'CA'),
('Bravo ZN', 'Chlorothalonil', 'Chloronitrile', 'Multi-site contact (Group M5)', 'SC', 'fungicide', 'disease', 'Syngenta Canada', ARRAY['potatoes', 'vegetables', 'pulses', 'peanuts'], ARRAY['late blight', 'early blight', 'cercospora', 'Septoria', 'botrytis'], '1-1.5 L/acre', '7-14 days', '48 hours', 'Multi-site protectant. Foundation product.', 'Group M5 - no resistance', '', 'PMRA 22388', '', 'CA'),
('Dithane DG Rainshield', 'Mancozeb', 'Dithiocarbamate', 'Multi-site contact (Group M3)', 'WG', 'fungicide', 'disease', 'Corteva Canada', ARRAY['potatoes', 'vegetables', 'pulses', 'corn'], ARRAY['late blight', 'early blight', 'anthracnose', 'downy mildew', 'Septoria'], '0.75-1 kg/acre', '7-14 days', '24 hours', 'Protectant multi-site. Rainfast formulation.', 'Group M3 - no resistance', '', 'PMRA 23978', '', 'CA'),
('Copper 53W', 'Copper oxychloride', 'Inorganic copper', 'Multi-site contact (Group M1)', 'WP', 'fungicide', 'disease', 'Various', ARRAY['potatoes', 'vegetables', 'tree fruits', 'grapes'], ARRAY['bacterial diseases', 'late blight', 'downy mildew', 'fire blight'], '1-3 kg/acre', '1 day', '24 hours', 'Organic-approved copper. Protectant only.', 'Group M1 - no resistance', '', 'PMRA various', '', 'CA'),
('Serenade Opti', 'Bacillus subtilis strain QST 713', 'Biological', 'Biocontrol organism', 'WP', 'fungicide', 'disease', 'Bayer Canada', ARRAY['vegetables', 'fruits', 'grapes', 'berries'], ARRAY['botrytis', 'powdery mildew', 'sclerotinia', 'bacterial spot'], '1-3 kg/acre', '0 days', '4 hours', 'Biological fungicide. Organic-approved.', 'Biological - no resistance', '', 'PMRA 28549', '', 'CA'),
('Vertisan', 'Penthiopyrad', 'SDHI', 'Succinate dehydrogenase inhibitor (Group 7)', 'SC', 'fungicide', 'disease', 'Corteva Canada', ARRAY['canola', 'soybeans', 'dry beans', 'chickpeas'], ARRAY['sclerotinia', 'white mold', 'cercospora', 'anthracnose'], '0.4-0.5 L/acre', '21 days', '12 hours', 'SDHI for sclerotinia in pulse and oilseed crops.', 'Group 7', '', 'PMRA 30123', '', 'CA'),
('Propulse', 'Fluopyram + Prothioconazole', 'SDHI + Triazole', 'SDHI + DMI (Group 7+3)', 'SC', 'fungicide', 'disease', 'Bayer Canada', ARRAY['canola', 'soybeans', 'pulses', 'sunflower'], ARRAY['sclerotinia', 'white mold', 'cercospora', 'ascochyta', 'rust'], '0.2 L/acre', '30 days', '12 hours', 'Premium sclerotinia control in canola/pulses.', 'Group 7+3', '', 'PMRA 30456', '', 'CA'),
('Delaro 325SC', 'Prothioconazole + Trifloxystrobin', 'Triazole + Strobilurin', 'DMI + QoI (Group 3+11)', 'SC', 'fungicide', 'disease', 'Bayer Canada', ARRAY['wheat', 'barley', 'oats', 'corn'], ARRAY['fusarium head blight', 'leaf rust', 'Septoria', 'tan spot', 'net blotch'], '0.2-0.32 L/acre', '36 days', '12 hours', 'Two-way cereal fungicide. Good FHB suppression.', 'Group 3+11', '', 'PMRA 29234', '', 'CA')
ON CONFLICT DO NOTHING;
