/*
  # Production Diseases Seed - Part 1 (50 diseases)

  Comprehensive Australian agricultural disease database.
  pathogen_type must be one of: 'fungal', 'bacterial', 'viral', 'oomycete', 'nematode', 'physiological', ''
*/

INSERT INTO agro_diseases (disease_name, common_name, pathogen_type, affected_crops, symptoms, conditions_favouring, weather_favourable_conditions, management_options, prevention_notes) VALUES

('Phytophthora infestans', 'Late Blight of Potato and Tomato', 'oomycete', ARRAY['Potato','Tomato'], 'Water-soaked lesions on leaves that rapidly turn dark brown-black with pale green halo. White sporulation on leaf undersides in wet conditions. Tuber rot with brown granular internal decay spreading from skin.', 'Cool temperatures 10-25C with extended leaf wetness over 10 hours. Dense canopy. High humidity.', 'Cool nights followed by warm humid days. Rain, fog, dew, overhead irrigation. Humidity above 90% RH.', 'Protectant fungicides on 5-7 day schedule. Systemics (Ridomil Gold, Forum) for curative action. Destroy infected plant material immediately. Remove volunteer potatoes.', 'Plant certified disease-free seed. Choose resistant varieties. Ensure good air circulation. Monitor using blight forecast models. Avoid overhead irrigation.'),

('Alternaria solani', 'Early Blight of Potato and Tomato', 'fungal', ARRAY['Potato','Tomato','Capsicum'], 'Concentric ring target-spot lesions on older leaves. Dark brown to black. Yellow halo around lesion. Affects older leaves first and progresses upward through canopy.', 'Warm temperatures 24-29C, moisture stress, heavy fruit load, nutrient deficiency. Favours stressed plants.', 'Alternating wet and dry conditions. Dew periods. Warm days above 24C.', 'Apply protectant fungicide (Mancozeb, Bravo) on 7-10 day schedule. Maintain crop nutrition especially nitrogen and potassium. Strobilurin or triazole fungicides curative.', 'Maintain potassium and nitrogen nutrition. Avoid water stress. Remove infected lower leaves. Implement longer crop rotations.'),

('Botrytis cinerea', 'Grey Mould', 'fungal', ARRAY['Strawberry','Grape','Tomato','Lettuce','Bean','Stone Fruit','Capsicum','Raspberry','Blueberry'], 'Soft grey-brown lesions. Characteristic grey fuzzy sporulation on infected tissue. Rapid collapse. Berry and fruit rot at harvest. Blossom blighting. Canker formation under bark.', 'Cool to mild temperatures 15-25C, high humidity, senescent tissue, flowers, wounds, poor air circulation.', 'Prolonged leaf wetness, high humidity, cool overcast conditions, rain during flowering.', 'Anilinopyrimidines (Switch, Vangard, Scala), SDHI (Cantus, Fontelis), dicarboximides (Rovral). Remove infected material promptly. Improve air circulation through canopy.', 'Reduce nitrogen. Improve canopy management. Avoid wounding. Time irrigation to allow foliage to dry. Remove senescing tissue before flowering.'),

('Puccinia striiformis f.sp. tritici', 'Stripe Rust of Wheat', 'fungal', ARRAY['Wheat','Triticale','Barley','Rye'], 'Pale yellow stripes of pustules along leaf veins. Severe epidemics cause head blight. Leaves die prematurely causing significant yield loss.', 'Cool temperatures 8-15C, extended dew or leaf moisture. Susceptible varieties.', 'Cool moist conditions in winter and spring. Dew, fog, light rain. Temperature 2-15C optimal for infection.', 'Apply triazole (Score, Tilt, Folicur) or strobilurin fungicides at first detection. Use resistant varieties. Apply preventatively before flag leaf emergence.', 'Plant resistant or tolerant varieties. Monitor via sentinel sites. Apply foliar fungicide at tillering to flag leaf stage in conducive conditions.'),

('Puccinia triticina', 'Leaf Rust of Wheat', 'fungal', ARRAY['Wheat','Triticale','Barley'], 'Orange-brown pustules on upper leaf surface. Circular to oval shaped. No distinctive striping pattern. Pustules turn dark as spores age through season.', 'Warmer temperatures 15-25C. Leaf wetness. Susceptible varieties. More aggressive in spring.', 'Warm humid conditions. Night dew or light rain. Temperature 15-25C optimal.', 'Foliar fungicides (triazoles, strobilurins). SDHI products for extended protection interval. Apply at GS31-45.', 'Resistant varieties are first line of defence. Monitor crop regularly from tillering. Apply fungicide at first pustule detection.'),

('Sclerotinia sclerotiorum', 'Sclerotinia Stem Rot', 'fungal', ARRAY['Canola','Chickpea','Faba Bean','Lupin','Sunflower','Soybean','Carrot','Lettuce','Tomato'], 'White cottony mycelium on stems, roots and pods. Water-soaked lesions. Hard black sclerotia inside hollow stem. Stem collapse. Pod shatter in canola and severe yield loss.', 'Canopy closure, cool 15-20C temperatures, extended wet periods during flowering. High sclerotia load from previous susceptible crops.', 'Cool moist conditions during flowering. Rain, overhead irrigation, high humidity. Dense canopy with restricted airflow.', 'Apply Cantus, Endura or Rovral at 20-30% flowering in canola. Timing is critical with 10-14 day residual needed.', 'Rotate away from susceptible crops. Avoid dense canopies. Wider row spacing. Cultivar selection with improved tolerance. Monitor crop closely at flowering.'),

('Fusarium oxysporum', 'Fusarium Wilt', 'fungal', ARRAY['Tomato','Capsicum','Strawberry','Banana','Cotton','Chickpea','Watermelon'], 'One-sided wilting of leaves and shoots. Yellow vascular streaking in cross-section (diagnostic). Plant death in severe cases. Internal brown-red discolouration in stem.', 'Warm soil temperatures 25-30C, soil pH below 6.5, root damage from nematodes or insects, continuous cropping.', 'Warm dry conditions. Warm soil above 22C. Low soil moisture stress increases susceptibility significantly.', 'No effective chemical control once established. Soil fumigation pre-plant. Grafting onto resistant rootstocks for tomato. Metalaxyl seed treatment reduces seedling loss.', 'Plant resistant varieties. Avoid root-damaging pests including nematodes. Maintain optimal soil pH. Implement long rotations of 5+ years. Use certified disease-free propagation material.'),

('Erysiphe necator', 'Powdery Mildew of Grape', 'fungal', ARRAY['Grape'], 'White powdery patches on green tissue. Affected berries turn brown and crack. Disfigured shoots. Dark mycelia visible on older infected tissue.', 'Mild temperatures 20-27C, moderate humidity, poor air circulation, shaded tissue inside canopy.', 'Moderate temperatures 20-27C. Can occur without rain. Dry periods with mild nights favour spread.', 'Sulfur-based fungicides early season. Triazoles, QoI strobilurins, SDHI fungicides. Apply every 7-14 days from budburst to veraison.', 'Manage canopy for light and airflow. Avoid excessive nitrogen. Remove infected wood at pruning. Early season preventive sprays are critical.'),

('Podosphaera xanthii', 'Powdery Mildew of Cucurbits', 'fungal', ARRAY['Cucumber','Zucchini','Pumpkin','Melon','Squash'], 'White powdery colonies on upper and lower leaf surfaces. Leaf yellowing and defoliation. Reduces fruit quality and marketable yield significantly.', 'Warm dry conditions, moderate humidity, poor air circulation. Does not require free water for infection.', 'Dry warm conditions. Temperature 20-30C. Low light intensity from shading.', 'Sulfur, triazoles (myclobutanil, tebuconazole), QoI (azoxystrobin), SDHI (penthiopyrad) fungicides.', 'Resistant varieties available. Plant in well-ventilated areas. Avoid excessive nitrogen. Scout from early in the season.'),

('Plasmopara viticola', 'Downy Mildew of Grape', 'oomycete', ARRAY['Grape'], 'Yellow oily spots on upper leaf surface. White downy sporulation on leaf undersides. Infected berries become purple then brown and shrivelled. Oil spots are diagnostic feature.', 'Temperatures 13-28C (optimum 25C), free water for 3+ hours post-rain. Post-rainfall sporulation abundant.', 'Rain events over 10mm. Warm temperatures above 13C. Prolonged leaf wetness. Spring and early summer peak risk.', 'Protectant fungicides (Mancozeb, copper) before rain. Curative products (Ridomil, Forum, Acrobat). Apply on 7-10 day schedule during risk periods from budburst.', 'Apply first spray at 10-15cm shoot growth in spring. Monitor rain events and temperatures. Remove infected leaves. Maintain good canopy airflow.'),

('Venturia inaequalis', 'Apple Scab', 'fungal', ARRAY['Apple','Crab Apple'], 'Olive-brown scab lesions on leaves, fruit and shoots. Severe infections cause leaf distortion and defoliation. Russeted and cracked fruit. Premature fruit drop.', 'Cool wet weather in spring ascospore season. 6-28C with over 10 hours leaf wetness. Primary infection from overwintered leaf litter.', 'Wet spring conditions. Extended leaf wetness periods over 10 hours. Rain events during primary season spring.', 'Apply from budbreak. Protectants (Mancozeb, Captan) before rain. Curative fungicides (triazoles, QoI) post-infection. SDHI products for extended protection period.', 'Rake and destroy fallen leaves. Resistant varieties available. Spray scheduling based on Mills table. Good air movement through orchard.'),

('Monilinia spp.', 'Brown Rot of Stone Fruit and Pome Fruit', 'fungal', ARRAY['Peach','Nectarine','Plum','Cherry','Apple','Pear','Apricot'], 'Brown rotting lesions on fruit. Characteristic concentric rings of grey sporulation. Blossom blight in spring. Twig cankers. Mummified fruit persisting on tree.', 'Warm wet conditions at flowering. Rain or dew at harvest. Mechanical damage provides infection sites for fungus.', 'Rain during flowering period. Humid conditions near harvest. Temperature 20-25C.', 'Apply at flowering and pre-harvest. Triazoles (tebuconazole, myclobutanil), anilinopyrimidines (cyprodinil), SDHI products. Remove mummies and infected wood at pruning.', 'Remove mummified fruit in winter. Prune for airflow. Avoid wounding fruit at harvest. Post-harvest treatments reduce storage rots significantly.'),

('Colletotrichum spp.', 'Anthracnose', 'fungal', ARRAY['Avocado','Mango','Strawberry','Bean','Grape','Capsicum','Chilli','Papaya'], 'Dark sunken lesions on fruit, stems and leaves. Orange-pink spore masses (salmon coloured) in lesions. Blossom blighting. Post-harvest fruit rots with quiescent infections.', 'Warm humid conditions 20-30C, rain or heavy dew. Wound sites. Pre-harvest quiescent infections activated post-harvest.', 'Warm wet weather. Rain splash. Temperatures 20-30C. High relative humidity above 90%.', 'Copper, Mancozeb, DMI fungicides, QoI strobilurins. Post-harvest hot water or fungicide dips. Remove infected material promptly.', 'Good sanitation. Avoid overhead irrigation. Handle fruit carefully at harvest. Post-harvest treatments essential for tropical fruit export.'),

('Peronospora destructor', 'Downy Mildew of Onion', 'oomycete', ARRAY['Onion','Garlic','Leek','Shallot'], 'Pale oval lesions on leaves. Grey-violet sporulation on leaf surface especially at night. Leaf collapse. Bulb discolouration in severe cases.', 'Cool temperatures 13-18C, extended leaf wetness over 6 hours, dense plantings.', 'Cool wet nights with morning dew. Extended leaf wetness overnight. High humidity above 90%.', 'Apply Mancozeb, Chlorothalonil (contact) or Ridomil, Forum (systemic) on 7-14 day schedule in wet conditions.', 'Avoid excessive nitrogen. Improve air circulation. Avoid overhead irrigation. Use certified seed and sets.'),

('Septoria tritici', 'Septoria Leaf Blotch of Wheat', 'fungal', ARRAY['Wheat','Triticale'], 'Tan-coloured lesions on leaves with small black fruiting bodies (pycnidia). Pale lesion centres. Starts on lower leaves and progresses upward. Can cause severe yield loss in wet seasons.', 'Cool wet conditions 10-20C. Rain splash spreads spores. Prolonged wet periods.', 'Rain events. Cool wet conditions. Extended leaf wetness. Temperature 10-20C.', 'Apply triazole, strobilurin or SDHI fungicides at flag leaf stage. Seed dressing for primary inoculum reduction.', 'Plant resistant varieties. Avoid continuous wheat. Apply foliar fungicide from GS31-65 in wet seasons.'),

('Pyrenophora teres', 'Net Blotch of Barley', 'fungal', ARRAY['Barley'], 'Net-like dark brown reticulations on leaves. Oval lesions with distinct brown netting pattern. Severe blighting and potential for lodging in affected crops.', 'Cool wet weather. Infected stubble and seed-borne inoculum. Conditions 10-25C.', 'Wet conditions with temperatures 10-25C. Infected barley stubble present.', 'Fungicide seed treatment. Apply strobilurin (Cabrio), triazole (Folicur) or SDHI at flag leaf stage. Avoid infected stubble carry-over.', 'Rotate away from barley for 2 years. Bury stubble. Use resistant varieties. Apply seed treatment at sowing.'),

('Alternaria brassicae', 'Alternaria Dark Leaf Spot of Brassica', 'fungal', ARRAY['Canola','Broccoli','Cauliflower','Cabbage','Mustard'], 'Dark brown-black spots with yellow halo on leaves and pods. Concentric rings visible on spots. Pod lesions lead to premature seed shatter and yield loss.', 'Wet conditions particularly during late vegetative and pod stages. Temperatures 24-29C.', 'Rain, dew, high humidity. Warm days and cool moist nights. Temperatures 24-29C.', 'Apply strobilurin (Amistar), triazole (Score) fungicides before pod stage. Mancozeb as contact protectant.', 'Use clean certified seed. Rotate away from brassicas. Apply protectant fungicides from late flowering stage.'),

('Rhizoctonia solani', 'Rhizoctonia Root Rot and Bare Patch', 'fungal', ARRAY['Wheat','Barley','Canola','Bean','Potato','Beet'], 'Spear-tip browning of seminal roots. Bare patches in paddock at establishment. Infected seedlings fail to emerge or collapse shortly after emergence. Dark brown root lesions.', 'Wet cold soils, high soil organic matter from previous crop, moist conditions during establishment. pH 6-7.', 'Cold wet soil at sowing. Compacted or waterlogged soil. Temperature 10-18C at sowing time.', 'Flutriafol or azoxystrobin seed dressings. Thiram or captan seed treatments. Good soil drainage. Delay planting until soils warm above 10C.', 'Avoid waterlogged soils. Use fungicide seed treatments. Crop rotation with pasture breaks to reduce inoculum. Use tolerant varieties where available.'),

('Phytophthora cinnamomi', 'Phytophthora Root Rot and Dieback', 'oomycete', ARRAY['Avocado','Macadamia','Ornamental','Protea'], 'Fine root rot and death. Yellowing, wilting and death of shoots and branches. Collar rot at base of stem. Phytophthora ooze visible in avocado.', 'Wet waterlogged soil conditions. High soil moisture. Movement of infested soil or water between sites.', 'Heavy rain, waterlogging, flooding. Warm wet soil conditions. Soil temperature above 20C.', 'Phosphonate applications (Aliette, phosphorous acid) as trunk injections or foliar sprays. Improve drainage. No curative soil treatment available.', 'Avoid waterlogging. Use resistant rootstocks for avocado. Prevent movement of infested soil. Raise soil pH to 7 to reduce disease severity.'),

('Fusarium graminearum', 'Fusarium Head Blight of Wheat', 'fungal', ARRAY['Wheat','Barley','Triticale','Oats'], 'Bleached spikelets tombstoning at anthesis. Pink-salmon sporulation at base of infected spikelet. Mycotoxin contamination (DON deoxynivalenol). Shrivelled and lightweight grain.', 'Warm wet conditions 25-30C during flowering. Rain from anthesis to early grain fill.', 'Rain during flowering. Warm humid conditions post-anthesis. Temperature 25-30C.', 'Apply Prosaro at 50% anthesis. Must be applied within 72 hours of initial infection. Timing at flowering is critical for efficacy.', 'Bury infected stubble. Avoid continuous wheat. Select moderately resistant varieties. Plan spray program around flowering date and weather forecast.'),

('Puccinia polysora', 'Southern Corn Rust', 'fungal', ARRAY['Maize','Sweet Corn'], 'Abundant small orange-brown pustules mainly on upper leaf surfaces. Rapid spread in warm conditions. Can cause severe yield loss in susceptible hybrids within weeks.', 'Warm temperatures 25-30C, leaf wetness, susceptible hybrids, wind dispersal from northern Australia.', 'Warm humid conditions. Temperature 25-32C. Rain and dew. Wind events spreading spores southward.', 'Foliar fungicides (strobilurin, triazole) at early detection. Resistant hybrids are primary protection.', 'Plant resistant hybrids. Monitor for rust pustule appearance from December. Apply fungicide before 5% leaf area affected.'),

('Pyricularia oryzae', 'Rice Blast', 'fungal', ARRAY['Rice'], 'Diamond-shaped leaf lesions with grey-white centre and brown border. Neck rot causes panicle blast and head drop. Collar and node infections in severe outbreaks.', 'Cool nights, temperatures 19-27C, high humidity, susceptible varieties, high nitrogen applications.', 'Cool nights with dew. Prolonged leaf wetness. High humidity. Wind assisting spore dispersal.', 'Tricyclazole or isoprothiolane applied at first signs. Strobilurins (Amistar) for leaf blast. Panicle protection timing is critical.', 'Resistant varieties are primary control. Avoid high nitrogen applications. Manage water levels carefully. Apply preventive fungicide at heading stage.'),

('Xanthomonas perforans', 'Bacterial Spot of Tomato and Capsicum', 'bacterial', ARRAY['Tomato','Capsicum'], 'Small water-soaked lesions on leaves turning dark with yellow halo. Raised scab-like spots on fruit. Defoliation in severe cases. Angular lesions on leaves.', 'Warm temperatures 24-30C, rain or overhead irrigation, wounds from insects or tools, soil splash.', 'Rain, overhead irrigation. Warm humid conditions. Temperature 24-30C.', 'Copper hydroxide or copper oxychloride applied on 7-10 day schedule. Begin sprays preventively in wet conditions. Streptomycin restricted use.', 'Use disease-free certified seed. Avoid overhead irrigation. Handle transplants carefully. Copper-based protectants from transplant establishment.'),

('Pseudomonas syringae pv. tomato', 'Bacterial Speck of Tomato', 'bacterial', ARRAY['Tomato'], 'Small dark brown spots surrounded by yellow halo on leaves. Water-soaked spots on fruit turning dark. Symptoms similar to bacterial spot but under cooler conditions.', 'Cool wet conditions 18-24C, rain and wind, overhead irrigation, wounds from tools or insects.', 'Cool wet weather. Rain and strong winds. Temperature 18-24C. Spring and autumn conditions.', 'Copper hydroxide or copper oxychloride as protectant sprays every 7-10 days in wet weather.', 'Use certified disease-free seed. Avoid overhead irrigation. Reduce nitrogen applications. Copper protectant program from transplant.'),

('Leptosphaeria maculans', 'Blackleg of Canola', 'fungal', ARRAY['Canola','Mustard'], 'Pale spots with dark border on seedling leaves (phoma spots). Stem canker at crown base. Girdling of stem. Premature ripening and lodging at harvest.', 'Wet conditions at seedling stage for leaf infection. Autumn rains allow spore release from stubble.', 'Rain at seedling stage from cotyledon to 3 leaf stage. Infected stubble releasing spores after autumn rainfall.', 'Seed treatment (Thiram, thiabendazole). Foliar triazoles when phoma spots appear. Harvest before lodging occurs.', 'Rotate away from canola for 3+ years. Bury or burn stubble. Use resistant varieties (check blackleg rating). Apply seed treatment. Monitor for phoma leaf spots at seedling stage.'),

('Xanthomonas axonopodis pv. citri', 'Citrus Canker', 'bacterial', ARRAY['Citrus','Orange','Lemon','Lime','Grapefruit'], 'Raised corky tan-coloured lesions on leaves, fruit and stems. Yellow halos around lesions. Premature fruit drop. Reduced fruit quality.', 'Warm wet conditions 25-30C, wind-driven rain, new flush growth, Asian citrus leafminer wounds.', 'Warm humid conditions. Wind-driven rain. New growth flush. Temperature 25-30C.', 'Copper-based bactericides applied preventively. Windbreaks. Leafminer control. Certified planting material.', 'Use certified disease-free trees. Install windbreaks. Control Asian citrus leafminer. Copper spray program. Exotic pest - report outbreaks to biosecurity authorities.'),

('Botrytis allii', 'Neck Rot of Onion', 'fungal', ARRAY['Onion','Shallot'], 'Soft brown rot at neck region after harvest. Grey-brown sporulation. Sclerotia on outer scales. Collapse of neck during curing and storage.', 'Wet harvest conditions, poorly cured bulbs, damage at harvest. Disease is latent at harvest.', 'Wet conditions near harvest. Rain preventing field curing. High humidity in storage.', 'Apply iprodione or tebuconazole pre-harvest. Ensure thorough field curing. Avoid bruising at harvest.', 'Apply fungicide sprays in last 3-4 weeks before harvest. Allow complete field curing before storage. Proper storage conditions essential.'),

('Sphaerotheca pannosa', 'Powdery Mildew of Peach and Rose', 'fungal', ARRAY['Peach','Nectarine','Rose'], 'White powdery patches on young shoots, leaves and flowers. Distortion and stunting of new shoots. Leaves roll and turn brown. Fruit russeting.', 'Warm dry conditions 18-25C, poor airflow, susceptible varieties, new growth flushes.', 'Warm dry periods. Moderate temperatures. Day-night temperature fluctuations.', 'Sulfur sprays, triazoles (myclobutanil), QoI strobilurins. Apply at first signs and continue on 7-14 day schedule.', 'Prune for air circulation. Avoid excessive nitrogen. Plant resistant varieties. Early season sprays when new growth emerges.'),

('Colletotrichum acutatum', 'Anthracnose of Strawberry', 'fungal', ARRAY['Strawberry'], 'Dark sunken lesions on fruit. Crown rot and runner lesions. Root rot in severe cases. Affects fruit at all stages from green to ripe.', 'Warm humid conditions 25-30C, overhead irrigation, rain, propagation via infected runners.', 'Warm wet conditions. Rain splash. Overhead irrigation. Temperature 25-30C.', 'Azoxystrobin, trifloxystrobin or Switch for fruit protection. Remove infected fruit promptly. Avoid overhead irrigation during fruiting.', 'Use certified disease-free runners. Avoid overhead irrigation during fruiting. Remove infected fruit immediately. Renovation practices post-harvest.'),

('Phytophthora cactorum', 'Crown Rot and Leather Rot', 'oomycete', ARRAY['Strawberry','Apple','Pear','Walnut'], 'Crown rot with reddish-brown infected crown tissue. Wilting and collapse. Root rot. Fruit rot called leather rot in apple and pepper skin in strawberry.', 'Cool wet soils, waterlogging, compacted soils. pH below 6. Root damage from any source.', 'Wet conditions. Heavy rain. Waterlogged soils. Temperature 12-20C.', 'Metalaxyl or mefenoxam soil drenches. Phosphonate for apple leather rot. Improve drainage.', 'Improve drainage. Raised beds. Avoid planting in wet low-lying areas. Use certified disease-free runners.'),

('Didymella rabiei', 'Ascochyta Blight of Chickpea', 'fungal', ARRAY['Chickpea'], 'Angular water-soaked lesions on leaves. Dark brown lesions on stems, petioles and pods. Pale centre with dark border on lesions. Pod infection causes seed discolouration.', 'Wet conditions at any growth stage. Rain, overhead irrigation, cool temperatures 15-25C.', 'Rain events. Cool wet conditions. Temperature 15-25C. Infected debris present from previous crop.', 'Apply triazole (Score, Amistar Top) or strobilurin fungicides. Seed dressings at sowing. Begin sprays at first signs of disease.', 'Use certified clean seed. Apply seed treatment (mancozeb, carboxin). Rotate away from chickpea. Avoid overhead irrigation. Plant resistant varieties where available.'),

('Barley Yellow Dwarf Virus', 'Barley Yellow Dwarf', 'viral', ARRAY['Wheat','Barley','Oats','Triticale','Rye'], 'Yellow or red discolouration of leaf tips progressing down leaf. Stunted plants. Delayed heading. Reduced grain fill. Root damage reducing water and nutrient uptake.', 'High aphid populations transmitting virus. Mild temperatures favouring aphid colonisation of crops.', 'Mild autumn conditions favouring aphid flight. Wet seasons with high aphid pressure. Warm dry springs.', 'Control aphid vectors with insecticides (Confidor, Karate). Seed treatments with thiamethoxam or imidacloprid provide early season protection.', 'Sow certified virus-tested seed. Control aphid vectors from crop emergence. Plant as early as possible in season. Aphicide seed treatment in high-risk seasons.'),

('Tomato Spotted Wilt Virus', 'Tomato Spotted Wilt', 'viral', ARRAY['Tomato','Capsicum','Lettuce','Onion','Peanut','Potato'], 'Bronze-brown ring spots on leaves and fruit. Stunted plants. Necrotic streaking on stems. Distorted fruit with ring and line patterns.', 'Thrips populations high. Warm dry conditions favouring thrips build-up. Susceptible hosts present.', 'Hot dry conditions building thrips populations. Wind events aiding thrips dispersal between crops.', 'Control western flower thrips vectors using spinosad or Delegate. Resistant varieties available (Sw5 and Tsw resistance genes). Remove and destroy infected plants.', 'Screen glasshouses. Use reflective mulches to deter thrips. Plant resistant varieties. Control thrips before plants become infected. Remove alternate weed hosts.'),

('Cucumber Mosaic Virus', 'Cucumber Mosaic', 'viral', ARRAY['Cucumber','Zucchini','Capsicum','Tomato','Lettuce','Celery','Banana'], 'Mosaic mottling and yellowing. Leaf distortion and stunting. Fruit mosaic and distortion. Necrotic streaking in some host species.', 'Aphid populations high. Many weed hosts present. Warm conditions favouring aphid colonisation.', 'Warm conditions in spring and autumn when aphid vectors are most active.', 'Control aphid vectors with insecticides. No chemical control of virus itself. Resistant varieties available. Remove infected plants.', 'Control aphids. Remove weed hosts. Plant resistant varieties. Reflective mulches deter aphids. Mineral oil sprays reduce aphid transmission efficiency.'),

('Fusarium oxysporum f.sp. cubense TR4', 'Panama Disease Tropical Race 4 of Banana', 'fungal', ARRAY['Banana','Cavendish Banana'], 'Yellow lower leaves that collapse and hang. Purple internal discolouration of corm is diagnostic feature. Entire plant death. No recovery once infected occurs.', 'Warm soils above 24C, acidic soils, susceptible Cavendish varieties, movement of infected soil or water.', 'Warm tropical conditions. Soil temperatures above 24C. Wet conditions promoting root damage.', 'No effective chemical treatment. Quarantine and destruction of infected material. Management only through exclusion and strict biosecurity.', 'Strict biosecurity - no soil movement from affected areas. Use certified clean planting material. Test soil and water. Report suspect plants to biosecurity authorities immediately.'),

('Phytophthora parasitica', 'Phytophthora Trunk Rot of Citrus', 'oomycete', ARRAY['Citrus','Orange','Lemon','Grapefruit','Mandarin'], 'Brown gummosis and bark scaling at base of trunk and root crown. Water-soaked bark. Foliage yellowing and dieback. Phytophthora exudate visible at collar.', 'Waterlogged soils, trunk wounding, high-budded trees, warm wet soil conditions near trunk.', 'Wet waterlogged soil. Warm soil temperatures. High rainfall periods.', 'Phosphonate trunk injections or foliar applications (Aliette, phosphorous acid). Improve drainage. Avoid burying graft union.', 'Plant on raised beds. Avoid waterlogging. Do not bury graft union. Use tolerant rootstocks. Apply phosphonate trunk injections annually.'),

('Colletotrichum gloeosporioides', 'Anthracnose of Mango and Avocado', 'fungal', ARRAY['Mango','Avocado'], 'Dark pre-harvest blossom blight. Post-harvest fruit rot. Dark sunken spots on fruit. Tip dieback on shoots and stems.', 'High humidity during flowering and fruit development. Rain events. Warm temperatures 25-30C.', 'Rain and humidity during flowering. Warm wet conditions during fruit development. Temperature 25-30C.', 'Mancozeb, copper applications from flowering through development. Post-harvest treatments (hot water, imazalil, thiabendazole) for export fruit.', 'Begin sprays at panicle emergence. Cover sprays until 3 weeks before harvest. Post-harvest dips critical for export fruit.'),

('Mycosphaerella fijiensis', 'Black Sigatoka of Banana', 'fungal', ARRAY['Banana'], 'Dark streaks on leaf undersurfaces progressing to premature leaf death. Much more aggressive than Yellow Sigatoka. Severe yield loss if uncontrolled.', 'Warm humid tropical conditions. High rainfall. Dense plantings restricting airflow.', 'Warm humid conditions. High rainfall. Temperature 25-30C.', 'Intensive fungicide spray program (aerial or ground). Rotation of FRAC groups. Systemic triazoles and strobilurins essential for control.', 'Disease-free planting material. Resistant varieties emerging. Strict spray program with resistance management.'),

('Phytophthora ramorum', 'Sudden Oak Death / Ramorum Blight', 'oomycete', ARRAY['Ornamental','Nursery Plants','Rhododendron'], 'Leaf blight and twig dieback. Bleeding cankers on stems. Rapid plant death in susceptible hosts. Wide host range including many ornamentals.', 'Cool wet conditions, 10-25C, rain, overhead irrigation, nursery trade movement.', 'Cool wet conditions. Extended wet periods. Rain splash. Temperature 10-25C.', 'Phosphonate, metalaxyl fungicides. Strict hygiene. Quarantine infected material. Notify authorities if suspected.', 'Exotic pest in Australia - strict biosecurity. Use certified planting material. Report suspect cases to biosecurity.'),

('Peronospora brassicae', 'Downy Mildew of Brassica', 'oomycete', ARRAY['Cabbage','Broccoli','Cauliflower','Brussels Sprouts','Brassica'], 'Yellow angular lesions on upper leaf surface. White downy sporulation on underside. Seedling collapse. Head and curd discolouration in mature plants.', 'Cool 10-18C, high humidity, extended leaf wetness, seedlings particularly susceptible.', 'Cool moist nights. Extended leaf wetness. High humidity. Dense plantings in seedbed.', 'Metalaxyl seed treatment for seedlings. Foliar applications of Ridomil, Mancozeb for established plants.', 'Use treated seed. Avoid overcrowding in seedbeds. Improve air circulation. Remove infected plant debris.'),

('Cercospora beticola', 'Cercospora Leaf Spot of Beet', 'fungal', ARRAY['Beet','Silverbeet','Spinach'], 'Circular tan spots with red-purple border on leaves. White spore masses in leaf spots. Severe defoliation reduces photosynthesis and yield significantly.', 'Warm temperatures 25-30C, prolonged leaf wetness, dense canopy restricting airflow.', 'Warm humid conditions. Rain and dew. Temperature 25-30C.', 'Triazole fungicides (tebuconazole), strobilurins (azoxystrobin). Mancozeb as protectant.', 'Crop rotation. Resistant varieties. Avoid overhead irrigation where possible. Apply fungicide preventatively in wet weather.'),

('Peronospora farinosa', 'Downy Mildew of Spinach', 'oomycete', ARRAY['Spinach','Silverbeet'], 'Yellow areas on upper leaf surface. Purple-grey downy sporulation on leaf undersides. Plant growth stunted. Rapid crop loss in cool wet conditions.', 'Cool 10-18C, humid conditions, extended leaf wetness, crowded plantings.', 'Cool moist nights. Extended leaf wetness. High humidity.', 'Metalaxyl or mefenoxam-based fungicides. Mancozeb as contact protectant.', 'Resistant varieties available. Improve air circulation. Avoid overhead irrigation.'),

('Spongospora subterranea', 'Powdery Scab of Potato', 'physiological', ARRAY['Potato'], 'Powdery scab pustules on tuber surface. Internal necrotic lesions called spraing. Root galls visible. Canker on stolons in wet conditions.', 'Cool wet soils, poor drainage, soil pH below 6.5, infected seed tubers.', 'Cool waterlogged soils. Temperatures 12-18C. Heavy rain after planting.', 'No effective chemical control. Fungicide seed treatment reduces primary inoculum. Metalaxyl-based drenches may reduce crown rot symptoms in some situations.', 'Use certified disease-free seed. Avoid infected soil areas. Rotate away from potato for 5+ years. Maintain soil pH 6.5-7.0.'),

('Diaporthe phaseolorum var. meridionalis', 'Stem Canker of Soybean', 'fungal', ARRAY['Soybean'], 'Reddish-brown lesions at base of petioles. Stem canker and internal stem browning. Premature plant death with leaf retention on dead plant.', 'Warm humid conditions during vegetative stages. Infected crop debris from previous season.', 'Warm wet conditions during vegetative growth stages.', 'Triazole or strobilurin foliar applications. Seed treatment fungicides.', 'Rotate crops. Resistant varieties. Seed treatment. Manage stubble through burying or burning.'),

('Peronospora tabacina', 'Blue Mould of Tobacco', 'oomycete', ARRAY['Tobacco'], 'Pale green to yellow spots on upper leaf surface. Blue-grey sporulation on underside. Rapid defoliation. Systemic infection of seedlings.', 'Cool 15-22C, high humidity, crowded seedlings, poor ventilation in seedbeds.', 'Cool moist conditions. High humidity. Crowded seedbeds.', 'Metalaxyl or mefenoxam seed and seedling treatments. Downy mildew fungicides from transplant.', 'Well-ventilated seedbeds. Adequate plant spacing. Resistant varieties.'),

('Plenodomus lingam', 'Blackleg of Canola (Aggressive)', 'fungal', ARRAY['Canola'], 'Pale spots with dark border on leaves. Crown canker at soil level. Girdling of stem at crown leading to lodging and harvest losses.', 'Wet conditions at seedling stage. Infected stubble. Warm autumn conditions.', 'Rain at seedling stage. Infected stubble present. Autumn rainfall events releasing spores.', 'Triazole fungicides (propiconazole, tebuconazole) at seedling stage. Seed treatment essential.', 'Rotate away from canola 3+ years. Use resistant varieties (check blackleg resistance rating). Apply seed treatment. Monitor for phoma spots.'),

('Pyrenopeziza brassicae', 'Light Leaf Spot of Canola', 'fungal', ARRAY['Canola'], 'Pale green spots on upper leaves. White sporulation in spots. Infected pods with white pustules. Stem and pod lesions.', 'Cool wet conditions 5-15C, high humidity, winter and spring.', 'Cool wet winter and spring conditions. Extended leaf wetness.', 'Triazole and strobilurin fungicides. Apply preventively in cool wet seasons.', 'Resistant varieties. Rotate away from canola. Apply seed treatment.'),

('Sclerotinia minor', 'Lettuce Drop', 'fungal', ARRAY['Lettuce','Endive','Celery'], 'Soft watery rot at soil level. White cottony mycelium at plant base. Small brown-black sclerotia (smaller than S. sclerotiorum). Plant collapses.', 'Cool wet soil, temperatures 10-20C, prolonged soil moisture, high organic matter.', 'Cool wet conditions. Soil moisture high. Temperature 10-20C.', 'PCNB soil applications. Iprodione or boscalid drench. Improve drainage and soil aeration.', 'Avoid waterlogged areas. Raise beds. Long rotations. Solarise soil between crops.'),

('Ophiosphaerella herpotricha', 'Summer Patch of Turf', 'fungal', ARRAY['Turf','Kentucky Bluegrass','Fine Fescue'], 'Circular yellow to brown patches in summer. Roots blackened with take-all pattern. Rings and crescent shapes in severe outbreaks.', 'Warm soil temperatures above 18C, soil compaction, wet then dry conditions.', 'Hot dry periods following wet conditions. Soil temperatures above 18C. High nitrogen applications.', 'Propiconazole, fenarimol, iprodione applied preventively in spring. Improve drainage and aeration.', 'Deep irrigation, low nitrogen applications. Improve drainage. Apply preventive fungicide in spring before soil heats.'),

('Gaeumannomyces graminis', 'Take-all of Wheat and Barley', 'fungal', ARRAY['Wheat','Barley','Oats'], 'Black rot of crown and roots. Bleached heads (whiteheads) scattered through crop. Plants easily pulled up. Brown-black discolouration of root and crown tissue.', 'Moist alkaline soils above pH 6.5. Continuous cereal cropping. Warm wet soils.', 'Warm moist soil conditions. Alkaline soil pH above 7. Wet seasons.', 'Silthiofam (Latitude) seed treatment provides partial control. Fluquinconazole seed treatment. Rotation is most effective management.', 'Break with non-cereal crop for 1-2 years. Soil acidification where appropriate. Seed treatment in high-risk paddocks. Avoid shallow sowing.'),

('Pythium spp.', 'Pythium Damping-off and Root Rot', 'oomycete', ARRAY['Vegetable','Ornamental','Turf','Wheat','Canola'], 'Pre-emergence damping-off - seed rot before emergence. Post-emergence - seedling collapse at soil level (wire stem). Root discolouration brown. Water-soaked stem base.', 'Cool wet soils, poor drainage, overcrowded seedlings, excessive irrigation.', 'Wet soils. Cool temperatures 10-20C. Waterlogging. Heavy soils.', 'Metalaxyl, mefenoxam (Ridomil) or etridiazole seed treatments and soil drenches. Improve drainage.', 'Avoid waterlogging. Improve drainage. Use treated seed. Sow into warm soils. Avoid overcrowding seedlings.');
