/*
  # Add more US EPA-registered chemicals - Part 3

  1. Modified Table
    - `agro_chemicals` - Additional US products to reach 120+

  2. Products Added
    - Additional herbicides, fungicides, insecticides for diverse crops
*/

INSERT INTO agro_chemicals (product_name, active_ingredient, chemical_group, mode_of_action, formulation_type, category, target_type, manufacturer, registered_crops, target_issues, application_rate, withholding_period, reentry_period, label_notes, resistance_notes, apvma_registration, registration_number, label_link, country) VALUES
('Harness MAX', 'Acetochlor + Atrazine + Mesotrione', 'Chloroacetamide + Triazine + HPPD', 'VLCFA + PSII + HPPD (Group 15+5+27)', 'SC', 'herbicide', 'weed', 'Bayer', ARRAY['corn'], ARRAY['Palmer amaranth', 'waterhemp', 'morningglory', 'foxtail', 'lambsquarters'], '2.5 qt/acre', 'None listed', '24 hours', 'Three-mode pre/early-post corn herbicide.', 'Three modes reduce resistance risk', '', 'EPA 524-615', '', 'US'),
('Fierce EZ', 'Flumioxazin + Pyroxasulfone', 'PPO + Isoxazoline', 'PPO + VLCFA (Group 14+15)', 'SC', 'herbicide', 'weed', 'Valent', ARRAY['soybeans', 'corn'], ARRAY['waterhemp', 'Palmer amaranth', 'marestail', 'ragweed', 'pigweed'], '6 fl oz/acre', 'Pre-emergence', '12 hours', 'Liquid formulation of Fierce. Easy to use.', 'Group 14+15', '', 'EPA 59639-180', '', 'US'),
('Reviton', 'Tiafenacil', 'PPO Inhibitor', 'PPO Inhibitor (Group 14)', 'SC', 'herbicide', 'weed', 'UPL', ARRAY['soybeans', 'corn', 'cotton', 'wheat'], ARRAY['marestail', 'Palmer amaranth', 'waterhemp', 'lambsquarters', 'kochia'], '2 fl oz/acre', 'Burndown pre-plant', '12 hours', 'Fast-acting PPO burndown. Visible results in hours.', 'Group 14', '', 'EPA 70506-378', '', 'US'),
('Kyro', 'Tiafenacil + Glufosinate', 'PPO + Glutamine synthetase', 'PPO + GS (Group 14+10)', 'SL', 'herbicide', 'weed', 'UPL', ARRAY['soybeans', 'corn', 'cotton'], ARRAY['Palmer amaranth', 'waterhemp', 'marestail', 'morningglory', 'ragweed'], '32 fl oz/acre', 'Burndown pre-plant', '12 hours', 'Two-mode burndown for resistant weeds.', 'Group 14+10', '', 'EPA 70506-401', '', 'US'),
('Willowood Azoxy 2SC', 'Azoxystrobin', 'Strobilurin', 'QoI (Group 11)', 'SC', 'fungicide', 'disease', 'Willowood', ARRAY['corn', 'soybeans', 'wheat', 'peanuts', 'vegetables', 'potatoes'], ARRAY['gray leaf spot', 'frogeye leaf spot', 'early blight', 'Septoria', 'rust'], '6-15 fl oz/acre', '14-30 days', '4 hours', 'Generic azoxystrobin. Broad crop label.', 'Group 11. Max 2-4 apps per season.', '', 'EPA 87290-42', '', 'US'),
('Topguard EQ', 'Flutriafol + Azoxystrobin', 'Triazole + Strobilurin', 'DMI + QoI (Group 3+11)', 'SC', 'fungicide', 'disease', 'FMC', ARRAY['corn', 'soybeans', 'wheat', 'barley', 'sorghum'], ARRAY['gray leaf spot', 'northern corn leaf blight', 'rust', 'frogeye leaf spot', 'Septoria'], '7 fl oz/acre', '21-30 days', '12 hours', 'Two-mode fungicide for row crops.', 'Group 3+11', '', 'EPA 279-3577', '', 'US'),
('Proline 480SC', 'Prothioconazole', 'Triazole', 'DMI (Group 3)', 'SC', 'fungicide', 'disease', 'Bayer', ARRAY['wheat', 'barley', 'soybeans', 'corn', 'peanuts'], ARRAY['fusarium head blight', 'Septoria', 'tan spot', 'rust', 'white mold'], '5.7 fl oz/acre', '30 days', '12 hours', 'Premium triazole. Strong FHB activity.', 'Group 3', '', 'EPA 264-862', '', 'US'),
('Aproach Prima', 'Picoxystrobin + Cyproconazole', 'Strobilurin + Triazole', 'QoI + DMI (Group 11+3)', 'SC', 'fungicide', 'disease', 'Corteva', ARRAY['corn', 'soybeans', 'wheat', 'barley'], ARRAY['gray leaf spot', 'frogeye leaf spot', 'rust', 'Septoria', 'net blotch'], '6.8 fl oz/acre', '30-45 days', '12 hours', 'Two-way row crop fungicide.', 'Group 11+3', '', 'EPA 62719-623', '', 'US'),
('Xyway LFR', 'Flutriafol', 'Triazole', 'DMI (Group 3)', 'SC', 'fungicide', 'disease', 'FMC', ARRAY['corn', 'soybeans', 'wheat'], ARRAY['Aspergillus ear rot', 'gray leaf spot', 'SDS', 'Rhizoctonia', 'early-season diseases'], '3 fl oz/acre', 'In-furrow at planting', '12 hours', 'In-furrow fungicide. Novel delivery.', 'Group 3 - in-furrow application', '', 'EPA 279-3559', '', 'US'),
('Miravis Ace', 'Pydiflumetofen + Propiconazole', 'SDHI + Triazole', 'SDHI + DMI (Group 7+3)', 'SC', 'fungicide', 'disease', 'Syngenta', ARRAY['wheat', 'barley', 'oats'], ARRAY['fusarium head blight', 'Septoria', 'rust', 'tan spot', 'net blotch'], '13.7 fl oz/acre', '30 days', '12 hours', 'Strong FHB suppression with novel SDHI.', 'Group 7+3', '', 'EPA 100-1631', '', 'US'),
('Abound 2SC', 'Azoxystrobin', 'Strobilurin', 'QoI (Group 11)', 'SC', 'fungicide', 'disease', 'Syngenta', ARRAY['vegetables', 'tree fruits', 'grapes', 'potatoes', 'berries'], ARRAY['downy mildew', 'powdery mildew', 'early blight', 'anthracnose', 'botrytis'], '12-15 fl oz/acre', '0-14 days', '4 hours', 'Specialty crop strobilurin. Very broad label.', 'Group 11. Limit apps per season.', '', 'EPA 100-1098', '', 'US'),
('Forum', 'Dimethomorph', 'CAA fungicide', 'Cellulose synthesis (Group 40)', 'SC', 'fungicide', 'disease', 'BASF', ARRAY['grapes', 'vegetables', 'potatoes', 'hops'], ARRAY['downy mildew', 'late blight', 'Phytophthora'], '6 fl oz/acre', '0-14 days', '12 hours', 'Oomycete-specific. Must tank-mix.', 'Group 40. Always tank-mix.', '', 'EPA 7969-205', '', 'US'),
('Endura', 'Boscalid', 'SDHI', 'Succinate dehydrogenase inhibitor (Group 7)', 'WG', 'fungicide', 'disease', 'BASF', ARRAY['vegetables', 'berries', 'tree fruits', 'grapes', 'canola'], ARRAY['botrytis', 'white mold', 'sclerotinia', 'alternaria', 'brown rot'], '6.5-11 oz/acre', '0-14 days', '12 hours', 'SDHI for botrytis and white mold in horticulture.', 'Group 7. Rotate with other modes.', '', 'EPA 7969-231', '', 'US'),
('Omega 500F', 'Fluazinam', 'Phenylpyridinamine', 'Oxidative phosphorylation uncoupler (Group 29)', 'SC', 'fungicide', 'disease', 'Syngenta', ARRAY['potatoes', 'peanuts', 'vegetables'], ARRAY['white mold', 'sclerotinia', 'late blight', 'southern blight'], '8 fl oz/acre', '14 days', '12 hours', 'Contact fungicide. Unique mode of action.', 'Group 29 - low resistance risk', '', 'EPA 100-1168', '', 'US'),
('Torino', 'Cyflufenamid', 'Phenylacetamide', 'Unknown (Group U13)', 'SC', 'fungicide', 'disease', 'Gowan', ARRAY['grapes', 'cucurbits', 'apples', 'berries', 'hops'], ARRAY['powdery mildew'], '3.4 fl oz/acre', '0-14 days', '4 hours', 'Specific powdery mildew fungicide. Novel mode.', 'Group U13 - unique target', '', 'EPA 10163-328', '', 'US'),
('Quintec', 'Quinoxyfen', 'Quinoline', 'Signal transduction (Group 13)', 'SC', 'fungicide', 'disease', 'Corteva', ARRAY['grapes', 'hops', 'cucurbits'], ARRAY['powdery mildew'], '4-6 fl oz/acre', '14 days', '12 hours', 'Preventative powdery mildew only.', 'Group 13 - apply preventatively only', '', 'EPA 62719-398', '', 'US'),
('Regalia', 'Reynoutria sachalinensis extract', 'Botanical', 'Plant defense inducer (Group P5)', 'SC', 'fungicide', 'disease', 'Marrone Bio', ARRAY['vegetables', 'grapes', 'berries', 'tree fruits', 'hops'], ARRAY['powdery mildew', 'downy mildew', 'botrytis', 'bacterial spot'], '1-4 qt/acre', '0 days', '4 hours', 'Biopesticide. Organic-approved. Triggers plant defense.', 'P5 - biological. No resistance.', '', 'EPA 84059-3', '', 'US'),
('Intrepid 2F', 'Methoxyfenozide', 'Diacylhydrazine', 'Ecdysone agonist (Group 18)', 'SC', 'insecticide', 'pest', 'Corteva', ARRAY['tree fruits', 'vegetables', 'cotton', 'soybeans', 'grapes'], ARRAY['codling moth', 'armyworm', 'loopers', 'leafrollers', 'beet armyworm'], '8-16 fl oz/acre', '14 days', '4 hours', 'Selective IGR. Only lepidoptera. IPM-safe.', 'Group 18', '', 'EPA 62719-442', '', 'US'),
('Altacor', 'Chlorantraniliprole', 'Diamide', 'Ryanodine receptor modulator (Group 28)', 'WDG', 'insecticide', 'pest', 'FMC', ARRAY['tree fruits', 'grapes', 'vegetables', 'nuts', 'berries'], ARRAY['codling moth', 'oriental fruit moth', 'leafrollers', 'caterpillars', 'cherry fruit worm'], '3-4.5 oz/acre', '3-14 days', '4 hours', 'Dry granular diamide for tree fruit. Good rain-fastness.', 'Group 28', '', 'EPA 279-3382', '', 'US'),
('Voliam Xpress', 'Lambda-cyhalothrin + Chlorantraniliprole', 'Pyrethroid + Diamide', 'Sodium channel + Ryanodine (Group 3A+28)', 'ZC', 'insecticide', 'pest', 'Syngenta', ARRAY['corn', 'soybeans', 'cotton', 'vegetables'], ARRAY['corn earworm', 'armyworm', 'stink bugs', 'rootworm adults', 'bollworm'], '9 fl oz/acre', '21 days', '24 hours', 'Dual-mode broad-spectrum.', 'Group 3A+28', '', 'EPA 100-1320', '', 'US'),
('Hero EW', 'Bifenthrin + Zeta-cypermethrin', 'Pyrethroids', 'Sodium channel modulators (Group 3A)', 'EW', 'insecticide', 'pest', 'FMC', ARRAY['corn', 'soybeans', 'cotton', 'wheat', 'sorghum'], ARRAY['stink bugs', 'corn earworm', 'armyworm', 'aphids', 'plant bugs'], '4-10 fl oz/acre', '21 days', '12 hours', 'Dual-pyrethroid for enhanced efficacy on stink bugs.', 'Group 3A (two AIs)', '', 'EPA 279-3377', '', 'US'),
('Danitol 2.4EC', 'Fenpropathrin', 'Pyrethroid', 'Sodium channel modulator (Group 3A)', 'EC', 'insecticide', 'pest', 'Valent', ARRAY['tree fruits', 'grapes', 'vegetables', 'cotton', 'strawberries'], ARRAY['mites', 'stink bugs', 'lygus', 'thrips', 'psylla', 'leafhoppers'], '10-16 fl oz/acre', '14-21 days', '24 hours', 'Pyrethroid with strong mite activity.', 'Group 3A', '', 'EPA 59639-35', '', 'US'),
('Exirel', 'Cyantraniliprole', 'Diamide', 'Ryanodine receptor modulator (Group 28)', 'SC', 'insecticide', 'pest', 'FMC', ARRAY['vegetables', 'tree fruits', 'grapes', 'berries', 'potatoes'], ARRAY['diamondback moth', 'Colorado potato beetle', 'thrips', 'whitefly', 'leafminers'], '13.5 fl oz/acre', '1-3 days', '12 hours', 'Next-gen diamide with sucking pest activity.', 'Group 28', '', 'EPA 279-3516', '', 'US'),
('Verdepryn 100SL', 'Cyclaniliprole', 'Diamide', 'Ryanodine receptor modulator (Group 28)', 'SL', 'insecticide', 'pest', 'SePRO', ARRAY['vegetables', 'tree fruits', 'berries', 'grapes'], ARRAY['thrips', 'leafminers', 'whitefly', 'caterpillars', 'beetles'], '7-11 fl oz/acre', '1-3 days', '4 hours', 'Broad diamide for specialty crops.', 'Group 28', '', 'EPA 89442-20', '', 'US')
ON CONFLICT DO NOTHING;
